
Processing file "alt_threading.ss"
Parsing alt_threading.ss ...
Parsing /home/khanh/hg/para5/sleekex/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure fac$int... 
Procedure fac$int SUCCESS
Checking procedure increment$cell... 
Procedure increment$cell SUCCESS
Checking procedure main$... 
assert:alt_threading.ss:50: 2:  : ok


Procedure main$ SUCCESS
Halting Reduce... 
Stop Omega... 30 invocations 
0 false contexts at: ()

Total verification time: 0.29 second(s)
	Time spent in main process: 0.04 second(s)
	Time spent in child processes: 0.25 second(s)
