/usr/local/bin/mona

Processing file "parallel_tree_search.ss"
Parsing parallel_tree_search.ss ...
Parsing ../../../../prelude_vp.ss ...
Translating global variables to procedure parameters...
Checking procedure para_search$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure para_search$node~int~boolean SUCCESS
Checking procedure para_search2$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure para_search2$node~int~boolean SUCCESS
Checking procedure search$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure search$node~int~boolean SUCCESS

0 false contexts at: ()

Total verification time: 2.2 second(s)
	Time spent in main process: 1.54 second(s)
	Time spent in child processes: 0.66 second(s)
