
Processing file "parallelCount.ss"
Parsing parallelCount.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure parallelCount$node2~int2... 
Procedure parallelCount$node2~int2 SUCCESS
Checking procedure parallelCount2$node2~int2... 
Procedure parallelCount2$node2~int2 SUCCESS
Halting Reduce... 
Stop Omega... 109 invocations 
0 false contexts at: ()

Total verification time: 1.32 second(s)
	Time spent in main process: 1.01 second(s)
	Time spent in child processes: 0.31 second(s)
