/usr/local/bin/z3

Processing file "parallel_fibonacci2.ss"
Parsing parallel_fibonacci2.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting z3... 
Translating global variables to procedure parameters...
Checking procedure para_fib$int~int... 
Procedure para_fib$int~int SUCCESS
Checking procedure para_fib2$int~int... 
Procedure para_fib2$int~int SUCCESS
Checking procedure seq_fib$int... 
Procedure seq_fib$int SUCCESS
Checking procedure seq_fib2$int~int... 
Procedure seq_fib2$int~int SUCCESS
Stop z3... 113 invocations 
0 false contexts at: ()

Total verification time: 0.4 second(s)
	Time spent in main process: 0.32 second(s)
	Time spent in child processes: 0.08 second(s)
