
Processing file "parallelCount.ss"
Parsing parallelCount.ss ...
Parsing /home/khanh/hg/para5/sleekex/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure parallelCount$node2~int2... 
Procedure parallelCount$node2~int2 SUCCESS
Checking procedure parallelCount2$node2~int2... 
Procedure parallelCount2$node2~int2 SUCCESS
Halting Reduce... 
Stop Omega... 109 invocations 
0 false contexts at: ()

Total verification time: 0.59 second(s)
	Time spent in main process: 0.19 second(s)
	Time spent in child processes: 0.4 second(s)
