/usr/local/bin/mona

Processing file "parallel_tree_search.ss"
Parsing parallel_tree_search.ss ...
Parsing ../../../../prelude_vp.ss ...
Translating global variables to procedure parameters...
Checking procedure para_search$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure para_search$node~int~boolean SUCCESS
Checking procedure para_search2$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure para_search2$node~int~boolean SUCCESS
Checking procedure search$node~int~boolean... 
Mona is running ... 

Mona is running ... 

Procedure search$node~int~boolean SUCCESS

0 false contexts at: ()

Total verification time: 3.99 second(s)
	Time spent in main process: 2.69 second(s)
	Time spent in child processes: 1.3 second(s)
