
Processing file "parallelCount2.ss"
Parsing parallelCount2.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure parallelCount$node2~int... 
Procedure parallelCount$node2~int SUCCESS
Checking procedure parallelCount2$node2~int... 
Procedure parallelCount2$node2~int SUCCESS
Checking procedure seqCount$node2~int... 
Procedure seqCount$node2~int SUCCESS
Stop Omega... 174 invocations 
0 false contexts at: ()

Total verification time: 0.55 second(s)
	Time spent in main process: 0.48 second(s)
	Time spent in child processes: 0.07 second(s)
