
Processing file "parallelCount.ss"
Parsing parallelCount.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure parallelCount$node2~int2... 
Procedure parallelCount$node2~int2 SUCCESS
Checking procedure parallelCount2$node2~int2... 
Procedure parallelCount2$node2~int2 SUCCESS
Checking procedure seqCount$node2~int2... 
Procedure seqCount$node2~int2 SUCCESS
Stop Omega... 174 invocations 
0 false contexts at: ()

Total verification time: 0.65 second(s)
	Time spent in main process: 0.59 second(s)
	Time spent in child processes: 0.06 second(s)
