
Processing file "parallel_merge_sort.ss"
Parsing parallel_merge_sort.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure count$node... 
Procedure count$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure merge$node~node... 
assert:parallel_merge_sort.ss:73: 4:  : ok


Procedure merge$node~node SUCCESS
Checking procedure split_func$node~int... 
Procedure split_func$node~int SUCCESS
Checking procedure parallel_merge_sort$node~node... 
Procedure parallel_merge_sort$node~node SUCCESS
Checking procedure parallel_merge_sort2$node~node... 
Procedure parallel_merge_sort2$node~node SUCCESS
Checking procedure seq_merge_sort$node~node... 
Procedure seq_merge_sort$node~node SUCCESS
Stop Omega... 421 invocations 
4 false contexts at: ( (65,3)  (65,10)  (61,2)  (61,9) )

Total verification time: 1.64 second(s)
	Time spent in main process: 1.42 second(s)
	Time spent in child processes: 0.22 second(s)
