
Processing file "threads.ss"
Parsing threads.ss ...
Parsing ../../../../prelude_vp.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure fac$int... 
Procedure fac$int SUCCESS
Checking procedure join_sum_thread$node~int~int... 
Procedure join_sum_thread$node~int~int SUCCESS
Checking procedure make_tree$int... 
Procedure make_tree$int SUCCESS
Checking procedure start_sum_thread$node~int... 
Procedure start_sum_thread$node~int SUCCESS
Checking procedure main$... 
Procedure main$ SUCCESS
Checking procedure tree_compute_sum_facs$node... 
Procedure tree_compute_sum_facs$node SUCCESS
Checking procedure summator$node~int... 
Procedure summator$node~int SUCCESS
Halting Reduce... 
Stop Omega... 135 invocations 
0 false contexts at: ()

Total verification time: 0.71 second(s)
	Time spent in main process: 0.43 second(s)
	Time spent in child processes: 0.28 second(s)
