EX="./override_one.sh"
$EX hip/ex12c1a-varperm-simple.ss
$EX hip/ex12c1b-varperm-simple.ss
$EX hip/ex12c1-varperm-simple.ss
$EX hip/ex12c2-varperm-simple.ss
$EX hip/ex12c-varperm-simple.ss
$EX hip/ex12-varperm-simple.ss
$EX hip/ex14-varperm-block.ss
$EX hip/ex15a-lend-heap.ss
$EX hip/ex15b-lend-heap.ss
$EX hip/ex15c-lend-heap.ss
$EX hip/ex15d-lend-heap.ss
$EX hip/ex15-lend-heap.ss
$EX hip/ex16-lend.ss
$EX hip/ex2c-latch-wrong.ss
$EX hip/ex2-latch-seq.ss
$EX hip/ex2z-latch-simple.ss
$EX hip/ex3-latch-par.ss
$EX hip/ex4a1-latch-par-simple.ss
$EX hip/ex4a-latch-par.ss
$EX hip/ex4b-latch-par-with-varperm.ss
$EX hip/ex4c1-latch-par-no-varperm.ss
$EX hip/ex4c2-latch-par-with-varperm.ss
$EX hip/ex4c-latch-par-with-varperm.ss
$EX hip/ex4d1-bind.ss
$EX hip/ex4d-bind.ss
$EX hip/ex4-latch-par.ss
$EX hip/ex4-latch-simple.ss
$EX hip/ex4-par-simple.ss
$EX hip/ex6-thread-var-perm.ss
$EX hip/ex7-race-error.ss
$EX ho/deadpool.ss
$EX ho/fibonacci.ss
$EX ho/inst2.ss
$EX ho/inst.ss
$EX ho/latch2.ss
$EX ho/latch-exp1.ss
$EX ho/latch-exp2.ss
$EX ho/latch.ss
$EX ho/ll-bug.ss
$EX ho/lock-exp2.ss
$EX ho/lock-exp3.ss
$EX ho/lock-exp4.ss
$EX ho/lock-exp.ss
$EX ho/mapreduce.ss
$EX ho/msg2a.ss
$EX ho/msg2.ss
$EX ho/msg3a.ss
$EX ho/msg3b.ss
$EX ho/msg3-d1.ss
$EX ho/msg3.ss
$EX ho/msg4a.ss
$EX ho/msg4b.ss
$EX ho/msg4.ss
$EX ho/msg5.ss
$EX ho/msg-d2.ss
$EX ho/msg.ss
$EX ho/multi-join1.ss
$EX ho/multi-join2.ss
$EX ho/parallel-mergesort.ss
$EX ho/parallel-quicksort.ss
$EX ho/poly-msg4b.ss
$EX ho/thrd-or.ss
$EX ho/thread2a.ss
$EX ho/thread2.ss
$EX ho/thread-dead.ss
$EX ho/threadpool.ss
$EX ho/thread-split.ss
$EX ho/thread.ss
$EX vp/ex11a-cdl.ss
$EX vp/ex11b1-err-perm-bind.ss
$EX vp/ex11b2-ok-perm-bind.ss
$EX vp/ex11c-cell-read-heap.ss
$EX vp/ex11-cdl.ss
$EX vp/ex12a-bind-lend-err.ss
$EX vp/ex12-bind-lend.ss
$EX vp/ex13a1-err-fork-thread.ss
$EX vp/ex13a2-err-fork-thread.ss
$EX vp/ex13a3-err-fork-thread.ss
$EX vp/ex13a-err-fork-thread.ss
$EX vp/ex13b-err-fork-thread.ss
$EX vp/ex13-fork-thread.ss
$EX vp/ex14-err-fork-thread.ss
$EX vp/ex37c-ho_task_decompose.ss
$EX vp/ex37d-ho_task_decompose.ss
$EX vp/ex37-task_decompose.ss
$EX vp/ex42-simple-csl.ss
$EX vp/prelude_thrd.ss
$EX web/cdl-ex1a-fm.ss
$EX web/cdl-ex1a-simple.ss
$EX web/cdl-ex1b-simple.ss
$EX web/cdl-ex1-fm.ss
$EX web/cdl-ex2-fm.ss
$EX web/cdl-ex3a-fm.ss
$EX web/cdl-ex3-fm.ss
$EX web/cdl-ex4a-race.ss
$EX web/cdl-ex4-race.ss
$EX web/cdl-ex5a-deadlock.ss
$EX web/cdl-ex5-deadlock.ss