EX="./slk_test_ex.sh ../sleek"
$EX hip/ex11-split-cnt.slk
$EX hip/ex12a-varperm-simple.slk
$EX hip/ex12b-varperm-simple.slk
$EX hip/ex12c3-simple.slk
$EX hip/ex13a-lend.slk
$EX hip/ex13b-lend.slk
$EX hip/ex13-lend.slk
$EX hip/ex14a-lend-node.slk
$EX hip/ex14-lend-node.slk
$EX hip/ex15-lend-heap.slk
$EX hip/ex1-latch-simple.slk
$EX hip/ex2a-latch.slk
$EX hip/ex2b-latch.slk
$EX hip/ex4d1-bind.slk
$EX hip/ex5-varperm-test.slk
$EX ho/bag-of-pairs.slk
$EX ho/concrete-bags.slk
$EX ho/concrete.slk
$EX ho/cyclic-check.slk
$EX ho/latch2.slk
$EX ho/latch4.slk
$EX ho/latch.slk
$EX ho/lemma-prop0a.slk
$EX ho/lemma-prop0.slk
$EX ho/lemma-prop1.slk
$EX ho/lemma-prop2.slk
$EX ho/lemma-prop.slk
$EX ho/msg2a.slk
$EX ho/msg2b.slk
$EX ho/msg2.slk
$EX ho/msg3a.slk
$EX ho/msg3b.slk
$EX ho/msg3c.slk
$EX ho/msg3-d1.slk
$EX ho/msg3.slk
$EX ho/msg5a.slk
$EX ho/msg5.slk
$EX ho/msg-d2.slk
$EX ho/msg.slk
$EX ho/parahip1.slk
$EX ho/parahip2.slk
$EX ho/parahip3.slk
$EX ho/split-cnt.slk
$EX ho/test.slk
$EX ho/thread2a.slk
$EX ho/thread2.slk
$EX ho/thread3.slk
$EX ho/thread-dead.slk
$EX ho/thread.slk
$EX ho/thread-split2.slk
$EX ho/thread-split3a.slk
$EX ho/thread-split3.slk
$EX ho/thread-split.slk
$EX ho/wait2.slk
$EX ho/wait2z.slk
$EX ho/wait3.slk
$EX ho/wait.slk
$EX ho/waits-pred.slk
$EX ho/waits.slk
$EX slk/bug-3a-ho-vars.slk
$EX slk/bug-3b-ho-vars.slk
$EX slk/bug-3-ho-vars.slk
$EX slk/bug-4a-ho-null.slk
$EX slk/bug-4-ho-vars.slk
$EX slk/bug-6a-covariant-latch.slk
$EX slk/bug-6b1-latchout-simple.slk
$EX slk/bug-6b2-latchout-simple.slk
$EX slk/bug-6b3-latchout-simple.slk
$EX slk/bug-6b4-latchout-simple.slk
$EX slk/bug-6b-latchout-simple.slk
$EX slk/bug-6c-latchout-simple.slk
$EX slk/bug-6d-latchout-simple.slk
$EX slk/bug-6e3-latchin-simple.slk
$EX slk/bug-6e4-latchin-simple.slk
$EX slk/bug-6e5-latchin-simple.slk
$EX slk/bug-6e7-latchin-simple.slk
$EX slk/bug-6-latch.slk
$EX slk/bug-8a1-lemma-norm.slk
$EX slk/bug-8a2-lemma-norm.slk
$EX slk/bug-8a-lemma-norm.slk
$EX slk/cnt.slk
$EX slk/err.slk
$EX slk/ex-3-ho-vars.slk
$EX slk/ex-4-ho-vars.slk
$EX slk/ex-5-false.slk
$EX slk/ex-6-ho-pred.slk
$EX slk/ex-6-ho-pure.slk
$EX slk/ex-6-ho-split.slk
$EX slk/ex-6-latch.slk
$EX slk/ex-7-latchout.slk
$EX slk/ex-8-lemma-norm.slk
$EX slk/ex-9-varperm.slk
$EX slk/ho_vars.slk
$EX slk/latch_old.slk
$EX slk/latch.slk
$EX slk/lemma-prop.slk
$EX vp/ex12a-bind-lend.slk
$EX vp/ex12b-lend.slk
$EX vp/ex37d1-ho.slk
$EX vp/vperm.slk
