diff res/sleek1.res res/sleek1.new
diff res/sleek2.res res/sleek2.new
diff res/sleek3.res res/sleek3.new
diff res/sleek4.res res/sleek4.new
diff res/sleek6.res res/sleek6.new
diff res/sleek7.res res/sleek7.new
diff res/sleek8.res res/sleek8.new
diff res/sleek9.res res/sleek9.new
diff res/sleek10.res res/sleek10.new
diff res/infer1.res res/infer1.new
diff res/infer2.res res/infer2.new
diff res/infer3.res res/infer3.new
diff res/infer4.res res/infer4.new
diff res/infer5.res res/infer5.new
diff res/infer6.res res/infer6.new
diff res/infer7.res res/infer7.new
diff res/infer8.res res/infer8.new
diff res/infer9.res res/infer9.new
diff res/infer10.res res/infer10.new
diff res/infer11.res res/infer11.new
diff res/infer12.res res/infer12.new
diff res/infer13.res res/infer13.new
diff res/infer14.res res/infer14.new
diff res/infer15.res res/infer15.new
diff res/ann1.res res/ann1.new
diff res/imm1.res res/imm1.new
diff res/imm2.res res/imm2.new
diff res/imm3.res res/imm3.new
diff res/imm4.res res/imm4.new
diff res/imm-hard.res res/imm-hard.new

