./dd -w res/sleek1.res res/sleek1.new
./dd -w res/sleek2.res res/sleek2.new
./dd -w res/sleek3.res res/sleek3.new
./dd -w res/sleek4.res res/sleek4.new
./dd -w res/sleek6.res res/sleek6.new
./dd -w res/sleek7.res res/sleek7.new
./dd -w res/sleek8.res res/sleek8.new
./dd -w res/sleek9.res res/sleek9.new
./dd -w res/sleek10.res res/sleek10.new
./dd -w res/infer1.res res/infer1.new
./dd -w res/infer2.res res/infer2.new
./dd -w res/infer3.res res/infer3.new
./dd -w res/infer4.res res/infer4.new
./dd -w res/infer5.res res/infer5.new
./dd -w res/infer6.res res/infer6.new
./dd -w res/infer7.res res/infer7.new
./dd -w res/infer8.res res/infer8.new
./dd -w res/infer9.res res/infer9.new
./dd -w res/infer10.res res/infer10.new
./dd -w res/infer11.res res/infer11.new
./dd -w res/infer12.res res/infer12.new
./dd -w res/infer13.res res/infer13.new
./dd -w res/infer14.res res/infer14.new
./dd -w res/infer15.res res/infer15.new
./dd -w res/ann1.res res/ann1.new
./dd -w res/imm1.res res/imm1.new
./dd -w res/imm2.res res/imm2.new
./dd -w res/imm3.res res/imm3.new
./dd -w res/imm4.res res/imm4.new
./dd -w res/imm-hard.res res/imm-hard.new

