../../sleek 1.slk > 1.res
../../sleek 2.slk > 2.res
../../sleek 3.slk > 3.res
../../sleek 4.slk > 4.res
../../sleek 5.slk > 5.res
../../sleek 6.slk > 6.res
../../sleek 7.slk > 7.res
../../sleek 8.slk > 8.res
../../sleek todo.slk > todo.res
