EX="./slk_test_ex.sh ../sleek"
$EX bugs/ann1.slk
$EX bugs/baga-test.slk
$EX bugs/im1a.slk
$EX bugs/im1.slk
$EX bugs/imm1.slk
$EX bugs/imm3.slk
$EX bugs/imm-ls-1.slk
$EX bugs/sleek0220.slk
$EX bugs/sleek0221.slk
$EX bugs/sleek0222.slk
$EX bugs/sleek0223.slk
$EX bugs/sleek0224.slk
$EX bugs/sleek02.slk
$EX bugs/sleek04.slk
$EX bugs/sleek05.slk
$EX bugs/sleek10_noimm.slk
$EX bugs/sleek10_oneimm.slk
$EX bugs/symb-diff.slk
$EX field/field4a.slk
$EX field/field4b.slk
$EX field/field4c.slk
$EX field/field4.slk
$EX field/field.slk
$EX hip/test1.slk
$EX hip/test2.slk
$EX hip/test31.slk
$EX hip/test3.slk
$EX inf/cell-3c1.slk
$EX inf/cell-3c2.slk
$EX inf/cell-3c3.slk
$EX inf/cell-3c4.slk
$EX inf/cell-3c.slk
$EX inf/cell.slk
$EX inf-imm/inf1_0.slk
$EX inf-imm/inf1.slk
$EX inf-imm/inf2.slk
$EX inf/lend-1.slk
$EX inf/lend-2a.slk
$EX inf/lend-2.slk
$EX inf/lend-3a.slk
$EX inf/lend-3b.slk
$EX inf/lend-3.slk
$EX inf/rel1.slk
$EX inf/tst1.slk
$EX inf/tst2.slk
$EX norm/field1.slk
$EX norm/field2.slk
$EX norm/field3.slk
$EX norm/field.slk
$EX norm/norm1.slk
$EX norm/norm2.slk
$EX norm/norm3.slk
$EX norm/norm4.slk
$EX norm/norm5.slk
$EX norm/norm6.slk
$EX norm/norm7.slk
$EX slk/simp-2.slk
$EX slk/simp.slk
$EX slk/sleek01.slk
$EX slk/sleek02.slk
