EX="./c_no_one.sh "
$EX Acc_fold.ml collect_atomic_heap_chain
$EX Acc_fold.ml collect_heap_chains
$EX Acc_fold.ml encode_h_formula
$EX Acc_fold.ml equal_heap_chain_code
$EX Acc_fold.ml try_fold_once
$EX Acc_fold.ml detect_fold_sequence
$EX Astsimp.ml gen_primitives
$EX Astsimp.ml convert_heap2
$EX Astsimp.ml convert_struc2
$EX Astsimp.ml gen_name_pairs_struc
$EX Astsimp.ml order_views
$EX Astsimp.ml join_hull
$EX Astsimp.ml remove_disj_clauses
$EX Astsimp.ml need_break_continue
$EX Astsimp.ml prepare_labels
$EX Astsimp.ml add_case_coverage
$EX Astsimp.ml line_split
$EX Astsimp.ml splitter
$EX Astsimp.ml move_instantiations
$EX Astsimp.ml formula_case_inference
$EX Astsimp.ml view_case_inference
$EX Astsimp.ml case_inference
$EX Astsimp.ml trans_prog
$EX Astsimp.ml trim_unsat
$EX Astsimp.ml trans_data
$EX Astsimp.ml form_body_inv_baga
$EX Astsimp.ml form_body_inv_baga_enum
$EX Astsimp.ml helper_unfold
$EX Astsimp.ml check_under
$EX Astsimp.ml add_param_ann_constraints_struc
$EX Astsimp.ml trans_view
$EX Astsimp.ml trans_views
$EX Astsimp.ml fill_one_base_case
$EX Astsimp.ml trans_hp
$EX Astsimp.ml trans_axiom
$EX Astsimp.ml compute_base_case
$EX Astsimp.ml set_materialized_prop
$EX Astsimp.ml find_m_prop_heap
$EX Astsimp.ml find_trans_view_name
$EX Astsimp.ml find_node_vars
$EX Astsimp.ml find_materialized_prop
$EX Astsimp.ml find_materialized_vars
$EX Astsimp.ml set_pre_flow
$EX Astsimp.ml trans_loop_proc
$EX Astsimp.ml add_perm_to_spec
$EX Astsimp.ml trans_one_coercion
$EX Astsimp.ml find_view_name
$EX Astsimp.ml trans_exp
$EX Astsimp.ml trans_args
$EX Astsimp.ml trans_case_coverage
$EX Astsimp.ml trans_var
$EX Astsimp.ml add_pre
$EX Astsimp.ml trans_copy_spec_4caller
$EX Astsimp.ml compact_nodes_with_same_name_in_h_formula
$EX Astsimp.ml compact_nodes_with_same_name_in_struc
$EX Astsimp.ml linearize_formula
$EX Astsimp.ml linearize_one_formula
$EX Astsimp.ml trans_pure_formula
$EX Astsimp.ml trans_pure_b_formula
$EX Astsimp.ml trans_pure_exp
$EX Astsimp.ml case_normalize_renamed_formula
$EX Astsimp.ml match_exp
$EX Astsimp.ml linearize_heap
$EX Astsimp.ml case_normalize_formula
$EX Astsimp.ml case_normalize_helper
$EX Astsimp.ml case_normalize_coerc
$EX Astsimp.ml rename_exp
$EX Astsimp.ml case_rename_var_decls
$EX Astsimp.ml check_eprim_in_struc_formula
$EX Astsimp.ml case_normalize_proc
$EX Astsimp.ml case_normalize_barrier 
$EX Astsimp.ml case_normalize_program
$EX Astsimp.ml prune_inv_inference_formula
$EX Astsimp.ml filter_pure_conj_list
$EX Astsimp.ml hull_invs
$EX Astsimp.ml comp
$EX Astsimp.ml compute_invariants
$EX Astsimp.ml split_one_branch
$EX Astsimp.ml collect_constr
$EX Astsimp.ml pick_pures
$EX Astsimp.ml sel_prune_conds
$EX Astsimp.ml safe_test
$EX Astsimp.ml get_safe_prune_conds
$EX Astsimp.ml view_prune_inv_inference
$EX Astsimp.ml barrier_prune_inv_inference
$EX Astsimp.ml pred_prune_inference
$EX Astsimp.ml prune_bar
$EX Astsimp.ml mark_rec_and_der_order
$EX Astsimp.ml mark_der_order
$EX Astsimp.ml mark_rec_and_call_order
$EX Astsimp.ml mark_call_order
$EX Astsimp.ml f_gen_base
$EX Astsimp.ml one_entail
$EX Astsimp.ml one_ctx_entail
$EX Astsimp.ml prep_t
$EX Astsimp.ml prep_grp
$EX Astsimp.ml trans_bdecl 
$EX Astsimp.ml process_pred_def_4_iast
$EX Astsimp.ml convert_pred_to_cast
$EX Astsimp.ml plugin_inferred_iviews
$EX Auxnorm.ml maybe_merge
$EX Auxnorm.ml norm_disj_tree
$EX Auxnorm.ml formula_of_tree
$EX Auxnorm.ml norm_disj
$EX Cast.ml merge_mater_props
$EX Cast.ml subst_coercion
$EX Cast.ml look_up_hp_def_raw
$EX Cast.ml look_up_hp_decl_data_name
$EX Cast.ml add_raw_hp_rel
$EX Cast.ml collect_rhs_view
$EX Cast.ml is_self_rec_rhs
$EX Cast.ml look_up_view_baga
$EX Cast.ml look_up_extn_info_rec_field
$EX Cast.ml look_up_coercion_def_raw
$EX Cast.ml case_of_coercion
$EX Cast.ml look_up_coercion_with_target
$EX Cast.ml check_proper_return
$EX Cast.ml vdef_fold_use_bc
$EX Cast.ml vdef_lemma_fold
$EX Cast.ml get_xpure_one
$EX Cast.ml any_xpure_1
$EX Cast.ml look_up_one
$EX Cast.ml add_uni_vars_to_view
$EX Cast.ml add_term_nums_proc_scc
$EX Cast.ml look_up_cont_args
$EX Cast.ml look_up_inst_args
$EX Cast.ml get_mut_vars_bu
$EX Cast.ml get_emp_map
$EX Cast.ml is_complex_entailment_4graph
$EX Cast.ml is_touching_view
$EX Cast.ml is_segmented_view
$EX Cast.ml is_tail_recursive_view
$EX Cast.ml collect_subs_from_view_node
$EX Cast.ml collect_subs_from_view_formula
$EX Cast.ml unfold_base_case_formula
$EX Cast.ml compute_view_residents
$EX Cast.ml compute_view_forward_backward_info
$EX Cast.ml is_resourceless_h_formula
$EX Cast.ml data_dependency_graph_of_exp
$EX Cformula.ml isAnyConstFalse
$EX Cformula.ml isStrictConstTrue
$EX Cformula.ml mkEList_no_flatten
$EX Cformula.ml is_eq_view_name
$EX Cformula.ml is_eq_view_spec
$EX Cformula.ml is_sat_mem_formula
$EX Cformula.ml is_mem_mem_formula
$EX Cformula.ml isTrivTerm
$EX Cformula.ml is_coercible
$EX Cformula.ml substitute_flow_in_f
$EX Cformula.ml mkAndFlow
$EX Cformula.ml mkStarMinusH
$EX Cformula.ml combine_and_pure
$EX Cformula.ml mkstar_combine
$EX Cformula.ml mkAnd_pure
$EX Cformula.ml get_node_annot_args
$EX Cformula.ml get_node_var
$EX Cformula.ml get_view_modes
$EX Cformula.ml h_add_origins
$EX Cformula.ml h_add_perm
$EX Cformula.ml add_origs_to_first_node
$EX Cformula.ml add_origins
$EX Cformula.ml set_lhs_case
$EX Cformula.ml base_formula_of_struc_formula
$EX Cformula.ml h_fv_node
$EX Cformula.ml h_fv
$EX Cformula.ml f_top_level_vars_struc
$EX Cformula.ml f_top_level_vars
$EX Cformula.ml subst_avoid_capture
$EX Cformula.ml subst_avoid_capture_pure
$EX Cformula.ml subst_avoid_capture_h
$EX Cformula.ml add_mix_formula_to_struc_formula
$EX Cformula.ml add_mix_formula_to_formula
$EX Cformula.ml subst_one_by_one
$EX Cformula.ml subst_b
$EX Cformula.ml subst_one_by_one
$EX Cformula.ml subst_one_by_one_pure
$EX Cformula.ml subst_one_by_one
$EX Cformula.ml normalize_replace
$EX Cformula.ml normalize_combine_star
$EX Cformula.ml normalize_only_clash_rename
$EX Cformula.ml split_components
$EX Cformula.ml add_quantifiers
$EX Cformula.ml push_struc_exists
$EX Cformula.ml push_exists
$EX Cformula.ml cformula.elim_exists
$EX Cformula.ml simplify_aux
$EX Cformula.ml simplify_pure_f
$EX Cformula.ml simplify_pure_f_old
$EX Cformula.ml elim_exists_es_his
$EX Cformula.ml CF.rename_bound_vars
$EX Cformula.ml propagate_perm_formula
$EX Cformula.ml rename_struc_clash_bound_vars
$EX Cformula.ml compose_formula
$EX Cformula.ml compose_formula
$EX Cformula.ml get_var_type
$EX Cformula.ml flatten_struc_formula
$EX Cformula.ml partition_hprel_flow
$EX Cformula.ml is_unknown_f
$EX Cformula.ml struc_elim_exist
$EX Cformula.ml extract_unk_hprel
$EX Cformula.ml extract_hrel_head_w_args
$EX Cformula.ml is_only_viewnode
$EX Cformula.ml  look_up_ptr_args_data_node
$EX Cformula.ml look_up_rev_reachable_ptr_args
$EX Cformula.ml  elim_unused_pure
$EX Cformula.ml prune_irr_neq_formula
$EX Cformula.ml check_imm_mis
$EX Cformula.ml  mkAnd_pure_pre_struc_formula
$EX Cformula.ml elim_useless_term_struc
$EX Cformula.ml look_up_reachable_ptrs_f
$EX Cformula.ml look_up_reachable_ptrs_w_alias
$EX Cformula.ml look_up_reachable_first_reachable_view
$EX Cformula.ml look_up_reachable_ptrs_sf
$EX Cformula.ml partition_heap_consj
$EX Cformula.ml get_hp_rel_name_formula
$EX Cformula.ml get_vnodes
$EX Cformula.ml get_vptrs
$EX Cformula.ml get_dptrs
$EX Cformula.ml struc_formula_trans_heap_node
$EX Cformula.ml CF.do_unfold_view
$EX Cformula.ml CF.do_unfold_hp_def
$EX Cformula.ml get_hp_rel_vars_h_formula
$EX Cformula.ml generate_xpure_view
$EX Cformula.ml annotate_dl
$EX Cformula.ml drop_views_formula
$EX Cformula.ml drop_view_struc_formula
$EX Cformula.ml drop_view_paras_formula
$EX Cformula.ml drop_view_paras_struc_formula
$EX Cformula.ml xpure_for_hnodes_f
$EX Cformula.ml is_only_neqNull
$EX Cformula.ml get_args_neqNull
$EX Cformula.ml get_neqNull
$EX Cformula.ml remove_neqNulls_f
$EX Cformula.ml remove_neqNull_redundant_hnodes_hf
$EX Cformula.ml remove_neqNull_redundant_hnodes_f
$EX Cformula.ml remove_com_pures
$EX Cformula.ml drop_hrel_f
$EX Cformula.ml combine_length_geq
$EX Cformula.ml subst_hrel_f
$EX Cformula.ml subst_hrel_hview_f
$EX Cformula.ml ins
$EX Cformula.ml drop_dups
$EX Cformula.ml extract_rec_extn
$EX Cformula.ml classify_formula_branch
$EX Cformula.ml extend_view_nodes
$EX Cformula.ml extract_abs_formula_branch
$EX Cformula.ml isFailCtx
$EX Cformula.ml gen_rand
$EX Cformula.ml gen_lor
$EX Cformula.ml cmb_lor
$EX Cformula.ml gen_ror
$EX Cformula.ml is_error_flow
$EX Cformula.ml is_mayerror_flow
$EX Cformula.ml get_failure_es_ft
$EX Cformula.ml get_must_failure
$EX Cformula.ml get_failure_list_partial_context
$EX Cformula.ml get_failure_partial_context
$EX Cformula.ml convert_maymust_failure_to_value_orig
$EX Cformula.ml convert_must_failure_4_list_failesc_context
$EX Cformula.ml is_inferred_pre_ctx
$EX Cformula.ml remove_dupl_false
$EX Cformula.ml collect_term_err_list_partial_context
$EX Cformula.ml add_infer_rel_to_estate
$EX Cformula.ml add_infer_pure_to_ctx
$EX Cformula.ml add_infer_pure_to_list_context
$EX Cformula.ml failesc_context_simplify
$EX Cformula.ml list_failesc_context_simplify
$EX Cformula.ml succ_context_of_failesc_context
$EX Cformula.ml or_context_list
$EX Cformula.ml pop_esc_level_list
$EX Cformula.ml simplify_ctx_elim_false_dupl
$EX Cformula.ml union_context_left
$EX Cformula.ml or_list_context
$EX Cformula.ml isSuccessListPartialCtx
$EX Cformula.ml isSuccessListFailescCtx
$EX Cformula.ml remove_true_conj_mix_formula
$EX Cformula.ml remove_dupl_conj_eq_mix_formula
$EX Cformula.ml remove_dupl_conj_eq_formula
$EX Cformula.ml list_partial_context_union
$EX Cformula.ml list_failesc_context_union
$EX Cformula.ml merge_esc
$EX Cformula.ml merge_failesc_context_or
$EX Cformula.ml list_partial_context_or
$EX Cformula.ml list_failesc_context_or
$EX Cformula.ml compose_context_formula
$EX Cformula.ml normalize_es
$EX Cformula.ml normalize_clash_es
$EX Cformula.ml formula_of_context
$EX Cformula.ml formula_trace_of_context
$EX Cformula.ml join_star_conjunctions_opt
$EX Cformula.ml split_star_conjunctions
$EX Cformula.ml type_of_formula
$EX Cformula.ml struc_to_view_un_s
$EX Cformula.ml struc_to_formula
$EX Cformula.ml struc_to_prepost
$EX Cformula.ml case_to_disjunct
$EX Cformula.ml push_pure
$EX Cformula.ml keep_hrel
$EX Cformula.ml extract_hvar_f
$EX Cformula.ml get_hvar
$EX Cformula.ml drop_hvar
$EX Cformula.ml subst_one_hvar_hf
$EX Cformula.ml subst_one_hvar
$EX Cformula.ml subst_hvar
$EX Cformula.ml subst_hvar_es
$EX Cformula.ml transform_formula
$EX Cformula.ml transform_formula_w_perm
$EX Cformula.ml transform_formula_w_perm
$EX Cformula.ml push_exists_context
$EX Cformula.ml add_path_id
$EX Cformula.ml normalize_max_renaming_list_failesc_context_4_bind
$EX Cformula.ml normalize_max_renaming_list_failesc_context
$EX Cformula.ml clear_entailment_history_es
$EX Cformula.ml clear_entailment_history
$EX Cformula.ml conv_elim_res
$EX Cformula.ml splitter_failesc_context
$EX Cformula.ml add_to_estate_with_steps
$EX Cformula.ml split_struc_formula
$EX Cformula.ml filter_branches
$EX Cformula.ml get_view_branches
$EX Cformula.ml propagate_perm_struc_formula
$EX Cformula.ml propagate_perm_struc_formula
$EX Cformula.ml add_to_subst
$EX Cformula.ml enable_imm_last_phase
$EX Cformula.ml simplify_formula 
$EX Cformula.ml merge_partial_h_formula
$EX Cformula.ml simp_ann
$EX Cformula.ml get_pre_post_invs
$EX Cformula.ml get_or_post
$EX Cformula.ml lax_impl_of_post
$EX Cformula.ml lax_impl_of_struc_post
$EX Cformula.ml collect_term_ann_for_svcomp_competion
$EX Cformula.ml norm_struc_with_lexvar
$EX Cformula.ml add_inf_cmd_struc
$EX Cformula.ml add_inf_post_struc
$EX Cformula.ml prepost_of_init
$EX Cformula.ml prepost_of_finalize
$EX Cformula.ml prepost_of_acquire
$EX Cformula.ml prepost_of_release
$EX Cformula.ml compose_formula_and
$EX Cformula.ml norm_one_formula_vperm
$EX Cformula.ml norm_formula_vperm
$EX Cformula.ml norm_struc_vperm
$EX Cformula.ml partLS
$EX Cformula.ml extractLS
$EX Cformula.ml removeLS
$EX Cformula.ml translate_level_formula
$EX Cformula.ml translate_level_eqn_formula
$EX Cformula.ml translate_waitlevel_formula
$EX Cformula.ml translate_waitS_rel
$EX Cformula.ml translate_set_comp_rel
$EX Cformula.ml infer_lsmu_formula
$EX Cformula.ml infer_lsmu_struc_formula
$EX Cformula.ml collect_heap_args_formula
$EX Cformula.ml collect_heap_args_context
$EX Cformula.ml trans_flow_formula
$EX Cformula.ml trans_flow_struc_formula
$EX Cformula.ml find_barr
$EX Cformula.ml get_bar_conds
$EX Cformula.ml trivFlowDischarge
$EX Cformula.ml is_emp_term
$EX Cformula.ml convert_to_mut
$EX Cformula.ml convert_to_mut
$EX Cformula.ml is_no_heap_struc_formula
$EX Cformula.ml force_elim_exists
$EX Cformula.ml project_h_formula_num
$EX Cformula.ml project_body_num
$EX Cformula.ml subst_hvar_struc
$EX Cformula.ml subst_struc_pre
$EX Cfout.ml rearrange_h_formula
$EX Cfout.ml rearrange_formula
$EX Cfout.ml rearrange_entailment
$EX Cfout.ml simplify_failesc_context_list
$EX Cfout.ml tidy_print
$EX Cfsolver.ml Solver.get_equations_sets
$EX Cfutil.ml sau.get_pos
$EX Cfutil.ml checkeq_view_node_with_null
$EX Cfutil.ml elim_null_vnodes
$EX Cfutil.ml elim_eqnull
$EX Cfutil.ml fresh_data_v
$EX Cfutil.ml simplify_htrue
$EX Cfutil.ml collect_consit_model
$EX Cfutil.ml is_unsat_heap_model
$EX Cfutil.ml keep_data_view_hpargs_nodes
$EX Cfutil.ml obtain_reachable_formula
$EX Cfutil.ml checkeq_reach_heap
$EX Cfutil.ml find_dependent_hps
$EX Cfutil.ml hp_defs_topo_sort
$EX Cfutil.ml classify_equiv_hp_defs
$EX Cfutil.ml SAU.build_subst_comm
$EX Cfutil.ml SAU.expose_expl_closure_eq_null
$EX Cfutil.ml SAU.expose_expl_eqs
$EX Cfutil.ml smart_subst_new
$EX Cfutil.ml unfold_non_rec_views
$EX Cfutil.ml is_unsat
$EX Cfutil.ml check_separation_unsat
$EX Cfutil.ml cfutil_tp_imply
$EX Cfutil.ml is_horm_h_formula
$EX Cfutil.ml check_tail_rec_rec_lemma
$EX Cfutil.ml poss_prune_pred
$EX Cfutil.ml need_cycle_checkpoint
$EX Cfutil.ml need_cycle_checkpoint_fold
$EX Cfutil.ml is_seg_view2_fold_form
$EX Cfutil.ml is_seg_view_br_fold_form
$EX Cfutil.ml seg_fold_view2
$EX Cfutil.ml seg_fold_view_br
$EX Cfutil.ml need_cycle_checkpoint_unfold
$EX Cfutil.ml get_shortest_length_base
$EX Cfutil.ml norm_seg_split
$EX Cfutil.ml check_seg_split_pred
$EX Cfutil.ml subst_rel_def
$EX Cfutil.ml get_ptrs_connected_w_args_f
$EX Cfutil.ml slice_framing_heaps
$EX Cfutil.ml slice_frame
$EX Cfutil.ml update_f
$EX Cfutil.ml xpure_graph_pto
$EX Cfutil.ml oa_node2view
$EX Cfutil.ml norm_rename_clash_args_node
$EX Cfutil.ml transform_bexpr
$EX Cfutil.ml partition_error_es
$EX Cfutil.ml obtain_subsume_es
$EX Checkeq.ml checkeq_formulas
$EX Checkeq.ml checkeq_formulas_one
$EX Checkeq.ml check_or
$EX Checkeq.ml checkeq_h_formulas
$EX Checkeq.ml check_spec_var
$EX Checkeq.ml add_map_rel
$EX Checkeq.ml checkeq_p_formula
$EX Checkeq.ml match_equiv_bform
$EX Checkeq.ml check_equiv_bform
$EX Checkeq.ml check_equiv_bform
$EX Checkeq.ml match_equiv_notform
$EX Checkeq.ml checkeq_formulas_with_diff_mt
$EX Checkeq.ml checkeq_formulas_with_diff
$EX Checkeq.ml checkeq_formulas_one_with_diff
$EX Checkeq.ml checkeq_h_formulas_with_diff
$EX Checkeq.ml checkeq_mix_formulas_with_diff
$EX Checkeq.ml checkeq_p_formula_with_diff
$EX Checkeq.ml check_equiv_2f
$EX Checkeq.ml check_equiv_constr
$EX Checkeq.ml check_constrs
$EX Checkeq.ml check_equiv_2fc_with_diff
$EX Checkeq.ml check_equiv_constr_with_diff
$EX Checkeq.ml check_constrs_with_diff_step1
$EX Checkeq.ml check_constrs_with_diff
$EX Checkeq.ml process_spairs
$EX Checkeq.ml check_equiv_def
$EX Checkeq.ml match_def
$EX Checkeq.ml check_defs
$EX Checkeq.ml checkeq_defs_with_diff
$EX Checkeq.ml check_subsume_defs
$EX Checkeq.ml update_lib
$EX Cilparser.ml collect_goto_label_in_fundec
$EX Cilparser.ml normalize_goto_fundec
$EX Cilparser.ml translate_typ
$EX Cilparser.ml translate_lval
$EX Cilparser.ml translate_exp
$EX Cilparser.ml translate_hip_exp
$EX Cilparser.ml helper_formula
$EX Cilparser.ml helper_h_formula
$EX Classic.ml heap_entail_rhs_htrue
$EX CleanUp.ml cleanUpFormulas
$EX CleanUp.ml cleanUpFormulas
$EX Context.ml action_get_holes
$EX Context.ml choose_context
$EX Context.ml view_mater_match
$EX Context.ml choose_full_mater_coercion
$EX Context.ml coerc_mater_match
$EX Context.ml spatial_ctx_extract
$EX Context.ml update_field_ann
$EX Context.ml update_ann
$EX Context.ml imm_split_lhs_node
$EX Context.ml exists_candidate_lemma
$EX Context.ml coerc_mater_match_with_unk_hp
$EX Context.ml coerc_mater_match_gen
$EX Context.ml lookup_lemma_action
$EX Context.ml process_one_match_accfold
$EX Context.ml process_one_match
$EX Context.ml process_matches
$EX Context.ml choose_match
$EX Context.ml sort_wt
$EX Context.ml sort_wt_new
$EX Context.ml group_equal_actions
$EX Context.ml compute_actions
$EX Context.ml need_check_cyclic
$EX Coqinf.ml get_inf_vars
$EX Coqinf.ml coqpure_to_coq_inf
$EX Coqinf.ml coq_inf_to_coqpure
$EX Coqinf.ml cpure_to_coqpure
$EX Coqinf.ml coqpure_to_cpure
$EX Coqinf.ml drop_quant
$EX Coqinf.ml drop_forall_inf
$EX Coqinf.ml close_form_cpure
$EX Coqinf.ml check_sat_coq
$EX Coqinf.ml check_imply_coq
$EX Coqinf.ml qe_fixpoint
$EX Coq.ml coq_of_formula
$EX Coq.ml stack coq prover
$EX Coq.ml stop coq prover
$EX Coq.ml coqwrite
$EX Coq.ml coqimplyops
$EX Coq.ml coqsimplops
$EX Cpgraph.ml get_frame
$EX Cpgraph.ml get_prune_frame
$EX Cpgraph.ml prune_irr_neq
$EX Cpgraph.ml prune_irr_neq_ll
$EX Cpgraph.ml prune_irr_neq_new
$EX Cprinter.ml pr_list_open_sep
$EX Cprinter.ml  string_of_proc_decl_list
$EX Cpure.ml eq_xpure_view
$EX Cpure.ml isConsTrue
$EX Cpure.ml can_be_aliased_aux
$EX Cpure.ml pure_ptr_equations_aux
$EX Cpure.ml is_float_formula
$EX Cpure.ml trans_eq_bform
$EX Cpure.ml trans_const_bforms
$EX Cpure.ml is_formula_arith
$EX Cpure.ml pure_mkAnd
$EX Cpure.ml pure_mkAndList
$EX Cpure.ml pure_mkOr
$EX Cpure.ml pure_mkStupidOr
# $EX Cpure.ml mkNot
$EX Cpure.ml mkExists_with_simpl
$EX Cpure.ml pure_mkExists
$EX Cpure.ml split_conjunctions
$EX Cpure.ml eqExp_f
$EX Cpure.ml build_relation
$EX Cpure.ml diff svl
$EX Cpure.ml fresh_old_name
$EX Cpure.ml subst_avoid_capture
$EX Cpure.ml b_apply_subs
$EX Cpure.ml e_apply_subs_list
$EX Cpure.ml b_subst
$EX Cpure.ml split_ex_quantifiers_rec
$EX Cpure.ml get_subst_equation_formula
$EX Cpure.ml get_subst_equation_b_formula 
$EX Cpure.ml get_all_vv_eqs
$EX Cpure.ml list_of_conjs
$EX Cpure.ml filter_redundant
$EX Cpure.ml elim_exists
$EX Cpure.ml [cpure]elim_exists
$EX Cpure.ml add_gte0_for_mona
$EX Cpure.ml add_flow_interval
$EX Cpure.ml add_flow_var_pf
$EX Cpure.ml add_flow_var
$EX Cpure.ml eq_spec_var_aset
$EX Cpure.ml filter_var
$EX Cpure.ml filter_var_new
$EX Cpure.ml find_rel_constraints
$EX Cpure.ml elim_idents
$EX Cpure.ml drop_varperm_formula
$EX Cpure.ml wrap_exists_svl
$EX Cpure.ml compute_constraint_relation
$EX Cpure.ml simp_mult
$EX Cpure.ml split_sums
$EX Cpure.ml purge_mult
$EX Cpure.ml b_form_simplify 
$EX Cpure.ml arith_simplify LHS
$EX Cpure.ml transform_formula
$EX Cpure.ml CP.norm_exp
$EX Cpure.ml  get_bform_eq_args_with_const
$EX Cpure.ml fast_imply
$EX Cpure.ml imply_disj_orig
$EX Cpure.ml imply_one_conj_orig
$EX Cpure.ml imply_conj_orig
$EX Cpure.ml filter_disj
$EX Cpure.ml cpure::norm_two_sides
$EX Cpure.ml cpure::norm_exp
$EX Cpure.ml cpure::norm_formula
$EX Cpure.ml is_linear_formula
$EX Cpure.ml is_linear_formula
$EX Cpure.ml elim_exists_with_simpl
$EX Cpure.ml has_level_constraint
$EX Cpure.ml filter_constraint_type
$EX Cpure.ml filter_constraint_type
$EX Cpure.ml filter_ante
$EX Cpure.ml filter_ante_wo_rel
$EX Cpure.ml get_equi_vars
$EX Cpure.ml elim_equi_ante
$EX Cpure.ml slice_formula
$EX Cpure.ml refine_one_must
$EX Cpure.ml find_all_failures
$EX Cpure.ml find_must_failures
$EX Cpure.ml check_maymust_failure
$EX Cpure.ml simplify_filter_ante
$EX Cpure.ml bfv_with_slicing_label
$EX Cpure.ml group_related_vars
$EX Cpure.ml dnf_to_list
$EX Cpure.ml compute_instantiations
$EX Cpure.ml add_ann_constraints
$EX Cpure.ml is_neq_null_exp
$EX Cpure.ml neg_eq_neq
$EX Cpure.ml neg_neq
$EX Cpure.ml get_neq_null_svl
$EX Cpure.ml check_dang_or_null_exp
$EX Cpure.ml get_list_rel_args
$EX Cpure.ml get_rel_id
$EX Cpure.ml is_rel_in_vars
$EX Cpure.ml assumption_filter
$EX Cpure.ml is_cyclic_rel
$EX Cpure.ml drop_rel_formula
$EX Cpure.ml memoise_formula_ho
$EX Cpure.ml memoise_rel_formula
$EX Cpure.ml restore_rel_formula
$EX Cpure.ml simplify_disj_new
$EX Cpure.ml add_term_nums_pure
$EX Cpure.ml extr_subs
$EX Cpure.ml has_e_tscons
$EX Cpure.ml has_b_tscons
$EX Cpure.ml has_tscons
$EX Cpure.ml tpd_drop_perm
$EX Cpure.ml tpd_drop_nperm
$EX Cpure.ml split_disjunctions_deep
$EX Cpure.ml split_disjunctions_deep
$EX Cpure.ml drop_exists_pure
$EX Cpure.ml get_rel_args
$EX Cpure.ml subst_rel_args
$EX Cpure.ml get_eqs_rel_args
$EX Cpure.ml extractLS_pure
$EX Cpure.ml removeLS_pure
$EX Cpure.ml translate_level_eqn_pure
$EX Cpure.ml translate_level_pure
$EX Cpure.ml infer_level_pure
$EX Cpure.ml infer_lsmu_pure
$EX Cpure.ml translate_waitlevel_p_formula
$EX Cpure.ml translate_waitlevel_b_formula
$EX Cpure.ml drop_locklevel_pure
$EX Cpure.ml translate_waitlevel_pure
$EX Cpure.ml drop_bag_formula_weak
$EX Cpure.ml is_bag_constraint_weak
$EX Cpure.ml translate_tup2_pure
$EX Cpure.ml translate_tup2_imply
$EX Cpure.ml is_concrete_bag_pure
$EX Cpure.ml get_concrete_bag_pure
$EX Cpure.ml apply_concrete_bag_pure
$EX Cpure.ml concretize_bag_pure
$EX Cpure.ml from_cylic_to_acyclic_rel_pure
$EX Cpure.ml extract_rel_pure
$EX Cpure.ml extract_cyclic_rel_pure
$EX Cpure.ml check_concrete_cyclic_rel_pure
$EX Cpure.ml has_cyclic_rel_pure
$EX Cpure.ml has_acyclic_rel_pure
$EX Cpure.ml has_waitS_rel_pure
$EX Cpure.ml has_concrete_rel_pure
$EX Cpure.ml create_waitS_rel
$EX Cpure.ml create_acyclic_rel
$EX Cpure.ml translate_acyclic_pure
$EX Cpure.ml translate_waitS_pure
$EX Cpure.ml translate_set_comp_pure
$EX Cpure.ml find_closure
$EX Cpure.ml find_closure_pure_formula
$EX Cpure.ml prune_irr_neq
$EX Cpure.ml is_irr_eq
$EX Cpure.ml checkeq
$EX Cpure.ml get_cmp_form
$EX Cpure.ml extract_eq_clauses_lbl_lst
$EX Cpure.ml drop_dupl
$EX Cpure.ml force_all_vv_eqs
$EX Cpure.ml expand_eqs
$EX Cpure.ml check_pointer_dis_sat
$EX Cpure.ml simpl_equalities
$EX Cpure.ml trans_formula_templ
$EX Cpure.ml annot_arg_to_imm_ann_list
$EX Cpure.ml update_positions_for_imm_view_params
$EX Cpure.ml update_positions_for_annot_view_params
$EX Cpure.ml  prune_relative_unsat_disj
$EX Cpure.ml nonlinear_var_list_formula
$EX Cpure.ml overapp_ptrs
$EX Cpure.ml collect_all_constraints
$EX Cpure.ml CP.transform_bexpr
$EX Cpure.ml check_non_determinism
$EX Cpure_pred.ml extract_outer_inner
$EX Cpure_pred.ml extract_list_exp_min_max_exp
$EX Cpure_pred.ml norm_exp_min_max2
$EX Cpure_pred.ml norm_exp_min_max
$EX Cpure_pred.ml mk_formula_from_tmp
$EX Cputil.ml hloc_enum_to_symb
$EX Cputil.ml get_aset
$EX Cputil.ml sel_subst
$EX Csvutil.ml get_aset
$EX Csvutil.ml comp_aliase
$EX CvpermUtils.ml norm_vperm_sets
$EX CvpermUtils.ml merge_vperm_sets
$EX CvpermUtils.ml combine_vperm_sets
$EX CvpermUtils.ml subst_par
$EX CvpermUtils.ml subst_one
$EX Cvutil.ml build_subs_4_evars
$EX Cvutil.ml compute_subs_mem
$EX Cvutil.ml compatible_ann
$EX Cvutil.ml extract_callee_view_info
$EX Cvutil.ml is_inconsistent
$EX Cvutil.ml extract_actual_args_view_info
$EX Cvutil.ml specialize_view_info
$EX Cvutil.ml build_vis
$EX Cvutil.ml process_vis
$EX Cvutil.ml view_unsat_check_topdown
$EX Cvutil.ml xpure_spec_view_inv
$EX Cvutil.ml h_formula_2_mem
$EX Cvutil.ml formula_2_mem
$EX Cvutil.ml xpure_heap_enum_baga
$EX Cvutil.ml conv_from_ef_disj
$EX Cvutil.ml xpure_symbolic_slicing
$EX Cvutil.ml partition
$EX Cvutil.ml check
$EX Cvutil.ml check_consistency
$EX Cvutil.ml xpure_perm
$EX Cvutil.ml xpure_symbolic_baga2
$EX Cvutil.ml xpure_heap_symbolic_i
$EX Cvutil.ml filter_prun_cond
$EX Cvutil.ml filter_formula_memo
$EX Cvutil.ml heap_prune_preds
$EX Cvutil.ml helper_formulas
$EX Cvutil.ml prune_preds
$EX Cvutil.ml prune_pred_struc
$EX Cvutil.ml remove_imm_from_formula
$EX Cvutil.ml get_oa_node_view
$EX Cvutil.ml crop_h_formula
$EX Da.ml case_analysis
$EX Da.ml get_spec_cases
$EX Da.ml find_rel_args_groups
$EX Derive.ml partition_extn_svl
$EX Derive.ml trans_view_one_derv
$EX Derive.ml trans_view_one_spec
$EX Derive.ml trans_view_dervs
$EX Derive.ml leverage_self_info
$EX Derive.ml expose_pure_extn_one_view
$EX Derive.ml expose_pure_extn
$EX Exc.ml compute_hierarchy_aux
$EX Exc.ml get_hash2
$EX Exc.ml get_hash
$EX Excore.ml simplify_with_label_omega
$EX Excore.ml ex_elim_clause
$EX Excore.ml ex_elim_baga
$EX Excore.ml ef_conv_disj
$EX Excore.ml mk_star_disj
$EX Excore.ml ef_unsat
$EX Excore.ml ef_elim_exists
$EX Excore.ml ef_imply
$EX Excore.ml partition
$EX Excore.ml ex_mk_star
$EX Excore.ml ex_unsat
$EX Excore.ml ef_elim_exists
$EX Excore.ml ex_merge_disj
$EX Excore.ml ex_lst_imply_pair
$EX Excore.ml ex_syn_imply
$EX Excore.ml ex_epure_disj_syn_imply
$EX Excore.ml ex_imply_disj
$EX Excore.ml I.mk_star_disj
$EX Excore.ml ex_subst_epure
$EX Excore.ml ex_subst_epure_disj
$EX Excore.ml ex_mk_epure
$EX Expure.ml widen_disj
$EX Expure.ml build_ef_heap_formula
$EX Expure.ml build_ef_heap_formula_with_pure
$EX Expure.ml build_ef_pure_formula
$EX Expure.ml build_ef_formula
$EX Expure.ml build_ef_view
$EX Expure.ml fix_test
$EX Expure.ml fix_ef
$EX Expure.ml is_ep_exp_arith
$EX Expure.ml is_ep_b_form_arith
$EX Expure.ml is_ep_pformula_arith
$EX Expure.ml is_ep_cformula_arith
$EX Expure.ml is_ep_view_arith
$EX Fixcalc.ml fixcalc_of_spec_var
$EX Fixcalc.ml fixcalc_of_pure_formula
$EX Fixcalc.ml subst_inv_lower_view
$EX Fixcalc.ml compute_invs_fixcalc
$EX Fixcalc.ml compute_heap_pure_inv
$EX Fixcalc.ml  compute_inv
$EX Fixcalc.ml compute_pure_inv
$EX Fixcalc.ml compute_def
$EX Fixcalc.ml compute_fixpoint_aux
$EX Fixcalc.ml extract_inv_helper
$EX Fixcalc.ml partition_comm_diff
$EX Fixcalc.ml do_reduce
$EX Fixcalc.ml fixc_reduce_disj_one_rel
$EX Fixcalc.ml fixc_preprocess
$EX Fixpoint.ml get_inv
$EX Fixpoint.ml elim_heap
$EX Fixpoint.ml simplify_post
$EX Fixpoint.ml simplify_pre
$EX Fixpoint.ml simplify_relation
$EX Fixpoint.ml check_defn
$EX Fixpoint.ml pre_calculate
$EX Fixpoint.ml pre_rel_fixpoint
$EX Fixpoint.ml update_with_td_fp
$EX Fixpoint.ml rel_fixpoint_wrapper
$EX Frame.ml generate_framing_holes
$EX Frame.ml prune_framing_heaps
$EX Frame.ml prune_framing_heaps_formula
$EX Frame.ml subst_framing_heaps_formula
$EX Frame.ml generate_framing_heaps_es
$EX Frame.ml subst_framing_heaps_ctx
$EX Frame.ml extract_frame_heap
$EX Frame.ml recover_framing_heaps_formula
$EX Frame.ml recover_framing_heaps_ctx
$EX Frame.ml look_up_emp_cond
$EX Frame.ml get_non_emp
$EX Frame.ml revert_emp_abs
$EX Frame.ml force_spatial_no_dups
$EX Frame.ml force_spatial_transitive
$EX Frame.ml force_no_disctinct_loop_free
$EX Frame.ml topo_sort
$EX Frame.ml combine_dependent_components
$EX Frame.ml update_alias_comp
$EX Frame.ml norm_dups_pred
$EX Frame.ml heap_normal_form
$EX Globalvars.ml find_read_write_global_var_proc
$EX Globalvars.ml trans_global_to_param
$EX Hgraph.ml look_up_end_of_edges
$EX Hgraph.ml set_pto_edges
$EX Hgraph.ml find_close_chains
$EX Hgraph.ml classify_merge_throw_chains
$EX Hgraph.ml update_hv_lbl
$EX Hgraph.ml from_var_to_hv
$EX Hgraph.ml add_vertex
$EX Hgraph.ml  build_init_ls_vertex
$EX Hgraph.ml build_init_edges
$EX Hgraph.ml build_ls_adj
$EX Hgraph.ml list_to_ar
$EX Hgraph.ml check_overlapping_sccs
$EX Hgraph.ml build_scc
$EX Hgraph.ml recover_mutrec
$EX Hgraph.ml topo_sort
$EX Hgraph.ml combine_dependent_components
$EX Hgraph.ml build_comps
$EX Hgraph.ml do_chain_merge_hv
$EX Hgraph.ml do_merge_throw_hv
$EX Hgraph.ml update_chain_adjs
$EX Hgraph.ml update_merge_throw_chain_adjs
$EX Hgraph.ml merge_alias_hv
$EX Hgraph.ml merge_emp_chains
$EX Hgraph.ml force_spatial_no_dups
$EX Hgraph.ml force_spatial_transitive
$EX Hgraph.ml dfs_no_loop
$EX Hgraph.ml do_force_no_disctinct_loop_free
$EX Hgraph.ml force_no_distinct_loop
$EX Hgraph.ml force_loop_helper
$EX Hgraph.ml find_case_split
$EX Hgraph.ml norm_graph
$EX Hgraph.ml find_homo_vertex_map
$EX Hgraph.ml check_non_empty_direct_loop
$EX Hgraph.ml check_one_src_edge
$EX Hgraph.ml check_homo_edges
$EX Hgraph.ml check_homomorphism
$EX Iast.ml find_close_ids
$EX Iast.ml get_mut_vars
$EX Iast.ml genESpec
$EX Iast.ml extract_mut_args
$EX Iast.ml look_up_all_fields
$EX Iast.ml subs_heap_type_env
$EX Iast.ml collect_data_view_from_struc
$EX Iast.ml collect_data_view_from_formula
$EX Iast.ml collect_data_view_from_h_formula
$EX Iast.ml collect_data_view_from_pure_formula
$EX Iast.ml collect_data_view_from_pure_bformula
$EX Iast.ml find_data_view
$EX Iast.ml syn_data_name
$EX Iast.ml fixpt_data_name
$EX Iast.ml update_fixpt
$EX Iast.ml set_check_fixpt
$EX Iast.ml data_name_of_view
# $EX Iast.ml add_edge
$EX Iast.ml exists_path
$EX Iast.ml build_exc_hierarchy
$EX Iast.ml look_up_field_ann
$EX Iast.ml exists_return
$EX Iast.ml exists_while_return
$EX Iast.ml exists_return_val
$EX Iast.ml get_return_exp
$EX Iast.ml detect_invoke
$EX IastUtil.ml rename_exp
$EX IastUtil.ml create_progfreeht_of_prog
$EX IastUtil.ml merge1
$EX IastUtil.ml add_globalv_to_mth_prog
$EX IastUtil.ml pre_process_of_iprog
$EX Icontext.ml ranking_frozen_mutrec_preds
$EX Icontext.ml icompute_action_pre
$EX Iformula.ml mkHeapNode
$EX Iformula.ml fv_ann_formula
$EX Iformula.ml struc_split_fv
$EX Iformula.ml struc_split_fv
$EX Iformula.ml formula_to_struc_formula
$EX Iformula.ml IF.rename_bound_vars
$EX Iformula.ml float_out_thread_one_formula
$EX Iformula.ml float_out_thread
$EX Iformula.ml float_out_thread_struc_formula
$EX Iformula.ml add_h_formula_to_pre
$EX Iformula.ml add_formula_to_post
$EX Iformula.ml wrap_post_struc_ex
$EX Iformula.ml struc_formula_trans_heap_node
$EX Iformula.ml struc_formula_drop_heap_node
$EX Iformula.ml normal_formula
$EX Iformula.ml struc_formula_collect_pre_hprel
$EX Iformula.ml IF.transform_h_formula
$EX Iformula.ml IF.transform_formula
$EX Iformula.ml IF.transform_struc_formula
$EX Iformula.ml transform_bexp_hf
$EX Immutable.ml subtype_ann_pair
$EX Immutable.ml subtype_ann_gen
$EX Immutable.ml is_lend_h_formula
$EX Immutable.ml is_lend
$EX Immutable.ml mkTempRes
$EX Immutable.ml normalize_h_formula
$EX Immutable.ml Immutable.insert_wr_phase
$EX Immutable.ml Immutable.insert_rd_phase
$EX Immutable.ml propagate_imm_formula
$EX Immutable.ml propagate_imm_h_formula
$EX Immutable.ml remaining_ann
$EX Immutable.ml consumed_list_ann
$EX Immutable.ml merge_ann_formula_list
$EX Immutable.ml collect_ann_info_from_formula
$EX Immutable.ml restore_tmp_res_ann
$EX Immutable.ml remaining_ann
$EX Immutable.ml restore_tmp_res_ann
$EX Immutable.ml restore_tmp_ann
$EX Immutable.ml restore_tmp_ann
$EX Immutable.ml push_crt_holes_list_ctx
$EX Immutable.ml compute_ann_list
$EX Immutable.ml normalize_field_ann_heap_node
$EX Immutable.ml normalize_field_ann_formula
$EX Immutable.ml normalize_field_ann_struc_formula
$EX Immutable.ml icollect_imm
$EX Immutable.ml split_view_args
$EX Immutable.ml split_sv
$EX Immutable.ml compatible_at_field_lvl
$EX Immutable.ml compatible_nodes
$EX Immutable.ml merge_data_node_w_view_node
$EX Immutable.ml merge_alias_nodes_h_formula
$EX Immutable.ml merge_alias_nodes_formula
$EX Immutable.ml merge_alias_nodes_struc_formula
$EX Infer.ml simplify_conjs
$EX Infer.ml remove_infer_vars_partial
$EX Infer.ml is_inferred_pre_list_context
$EX Infer.ml collect_rel_list_partial_context
$EX Infer.ml get_args_h_formula
$EX Infer.ml is_elem_of
$EX Infer.ml infer_heap_nodes
$EX Infer.ml i.simplify
$EX Infer.ml simplify_disjs
$EX Infer.ml detect_lhs_rhs_contra
$EX Infer.ml infer_pure_m_1
$EX Infer.ml infer_pure_top_level
$EX Infer.ml lhs_simplifier_tp
$EX Infer.ml detect_lhs_rhs_contra2
$EX Infer.ml infer_collect_rel
$EX Infer.ml generate_linking_svl
$EX Infer.ml find_guard
$EX Infer.ml find_undefined_selective_pointers
$EX Infer.ml get_prog_vars
$EX Infer.ml get_history_nodes
$EX Infer.ml simplify_lhs_rhs
$EX Infer.ml lookup_eq_hprel_ass
$EX Infer.ml  generate_error_constraints
$EX Infer.ml update_es
$EX Infer.ml infer_for_unfold
$EX Infer.ml add_infer_hp_contr_to_list_context
$EX Infinity.ml infinity.normalize_exp
$EX Infinity.ml split_inf_add
$EX Infinity.ml contains_inf
$EX Infinity.ml infinity.simplify_b_formula
$EX Infinity.ml convert_inf_to_var
$EX Infinity.ml contains_inf_eq
$EX Infinity.ml find_inf_subs
$EX Infinity.ml find_inf_bounded
$EX Infinity.ml find_neginf_bounded
$EX Infinity.ml sub_inf_list
$EX Infinity.ml find_equiv_all
$EX Infinity.ml normalize_inf_formula
$EX Infinity.ml normalize_inf_formula_sat
$EX Infinity.ml INF-norm-imply
$EX Infinity.ml fixed_point_pai_num
$EX Infinity.ml gen_instants
$EX Infinity.ml elim_forall_inf
$EX Infinity.ml elim_inf_forall
$EX Infinity.ml elim_inf_exists
$EX Infinity.ml elim_forall_exists_inf
# $EX Ipure.ml mkAnd
$EX Ipure.ml find_closure_pure
$EX Ipure.ml mkAndList_opt
$EX Ipure.ml transform_exp
$EX Ipure.ml transform_b_formula
$EX Ipure.ml IP.transform_formula
$EX Ipure.ml is_bexp
$EX Ipure.ml transform_bexp_p
$EX Ipure.ml transform_bexp
$EX Label_aggr.ml build_eset_of_conj_formula
$EX Label_aggr.ml mk_exists_eset
$EX Label_aggr.ml norm_lbl_lst
$EX Label_aggr.ml extract_eset_of_lbl_lst
$EX Label.ml get_labels
$EX Label_only.ml overlap
$EX Label_only.ml is_fully_compatible_imply
$EX Label_only.ml is_fully_compatible_sat
$EX Label_only.ml is_part_compatible
$EX Label_only.ml Label_compare
$EX Label_only.ml is_part_compatible_sat
$EX Label_only.ml is_part_compatible_imply
$EX Lemma.ml generate_lemma
$EX Lemma.ml final_inst_analysis_view
$EX Lemma.ml generate_lemma_4_views
$EX Lemma.ml update_store_with_repo
$EX Lemma.ml manage_unsafe_lemmas
$EX Lemma.ml sa_infer_lemmas
$EX Lemma.ml process_list_lemma
$EX Lemma.ml LEM.do_unfold_view
$EX Lemma.ml normalize_view_branch
$EX Lemma.ml refine_nontail_coerc_body_heap
$EX Lemma.ml refine_tail_coerc_body_heap
$EX Lemma.ml generate_view_lemmas
$EX Lemma.ml generate_view_rev_rec_lemmas
$EX Lemproving.ml run_entail_check
$EX Lemproving.ml process_coercion_check
$EX Lemproving.ml check_coercion
$EX Lemproving.ml add_exist_heap_of_struc
$EX Lemproving.ml check_coercion_struc
$EX Lemproving.ml check_left_coercion
$EX Lemproving.ml check_right_coercion
$EX Lemproving.ml sa_verify_lemma
$EX Lem_store.ml add_coercion
$EX Lem_store.ml pop_coercion
$EX Lemsyn.ml gen_lemma
$EX Lemsyn.ml gen_lemma_infer
$EX Lemutil.ml checkeq_sem
$EX Lemutil.ml norm_checkeq_views
$EX Log.ml add_sleek_logging
$EX Log.ml proof_log_to_text_file
$EX Log.ml sleek_log_to_text_file
$EX Log.ml process_proof_logging
$EX Lp.ml lp_norm_formula
$EX Lp.ml lp_get_model
$EX Main.ml process_primitives
$EX Main.ml process_includes
$EX Mathematica.ml send_and_receive
$EX Mathematica.ml check_formula
$EX Mathematica.ml is_linear_formula
$EX Mathematica.ml strengthen_formula
$EX Mathematica.ml negate_formula
$EX Mathematica.ml is_sat_no_cache
$EX Mathematica.ml is_sat_ops
$EX Mathematica.ml is_sat
$EX Mathematica.ml is_valid
$EX Mathematica.ml imply_no_cache
$EX Mathematica.ml imply_ops
$EX Mathematica.ml imply
$EX Mcpure.ml fold_aset
$EX Mcpure.ml group_mem_by_fv
$EX Mcpure.ml regroup_memo_group
$EX Mcpure.ml subst_avoid_capture_memo
$EX Mcpure.ml m_apply_par
$EX Mcpure.ml pure_bag_equations_aux
$EX Mcpure.ml ptr_equations_aux_mp
$EX Mcpure.ml get_subst_equation_memo_formula
$EX Mcpure.ml memo_apply_one_exp
$EX Mcpure.ml fold_mem_lst_to_lst_gen
$EX Mcpure.ml fold_mem_lst_to_lst_gen_slicing
$EX Mcpure.ml fold_mem_lst_to_lst
$EX Mcpure.ml fold_mem_lst_m
$EX Mcpure.ml filter_merged_cons
$EX Mcpure.ml merge_mems_m
$EX Mcpure.ml memoise_add_pure_aux 
$EX Mcpure.ml memoise_add_pure_N_m
$EX Mcpure.ml memoise_add_pure_P_m
$EX Mcpure.ml create_memo_group_wrapper
$EX Mcpure.ml anon_partition
$EX Mcpure.ml create_memo_group
$EX Mcpure.ml split_mem_grp
$EX Mcpure.ml memo_pure_push_exists_eq
$EX Mcpure.ml split_eqs
$EX Mcpure.ml memo_pure_push_exists_slice
$EX Mcpure.ml memo_pure_push_exists_all
$EX Mcpure.ml memo_pure_push_exists_m
$EX Mcpure.ml memo_norm
$EX Mcpure.ml simpl_memo_pure_formula
$EX Mcpure.ml memo_changed
$EX Mcpure.ml transform_memo_formula
$EX Mcpure.ml slow_imply
$EX Mcpure.ml elim_redundant_cons
$EX Mcpure.ml elim_redundant_slice
$EX Mcpure.ml elim_redundant
$EX Mcpure.ml fast_memo_imply
$EX Mcpure.ml is_ineq_linking_memo_group
$EX Mcpure.ml is_sat_memo_sub_no_ineq_slicing_complete
$EX Mcpure.ml mimply_process_ante
$EX Mcpure.ml pick_relevant_lhs_constraints
$EX Mcpure.ml mimply_conj
$EX Mcpure.ml imply_memo
$EX Mcpure.ml mix_of_pure
$EX Mcpure.ml regroup_memo_group
$EX Mcpure.ml merge_mems 
$EX Mcpure.ml memo_pure_push_exists
$EX Mcpure.ml ptr_equations_with_null
$EX Mcpure.ml ptr_equations_without_null
$EX Mcpure.ml filter_useless_memo_pure
$EX Mcpure.ml fold_mem_lst
$EX Mcpure.ml memoise_add_pure_N
$EX Mcpure.ml memoise_add_pure_P
$EX Mcpure.ml simpl_memo_pure_formula
$EX Mcpure.ml memo_arith_simplify
$EX Mcpure.ml get_all_vv_eqs_mix
$EX Mcpure.ml mix_cons_filter
$EX Mcpure.ml memo_drop_rel
$EX Mcpure.ml find_closure_mix_formula
$EX Mcpure.ml remove_dupl_conj_mix_formula
$EX Mcpure.ml extractLS_mix_formula
$EX Mcpure.ml removeLS_mix_formula
$EX Mcpure.ml remove_level_mix_formula
$EX Mcpure.ml translate_level_mix_formula
$EX Mcpure.ml translate_level_eqn_mix_formula
$EX Mcpure.ml infer_lsmu_mix_formula
$EX Mcpure.ml translate_waitlevel_mix_formula
$EX Mcpure.ml remove_disj_clauses
$EX Mem.ml split_heap
$EX Mem.ml check_mem_sat
$EX Mem.ml compact_data_nodes
$EX Mem.ml compact_view_nodes
$EX Mem.ml compact_nodes_with_same_name_in_h_formula
$EX Mem.ml compact_nodes_with_same_name_in_h_formula_top
$EX Mem.ml compact_nodes_with_same_name_in_formula
$EX Mem.ml ramify_starminus_in_h_formula
$EX Minisat.ml check_problem_through_file
$EX Minisat.ml minisat_is_sat
$EX Minisat.ml imply
$EX Mona.ml compute_order_formula
$EX Mona.ml solve_constraints
$EX Mona.ml sat_constraints
$EX Mona.ml new_order_formula
$EX Mona.ml preprocess_formula
$EX Mona.ml find_order_b_formula
$EX Mona.ml find_order_exp
$EX Mona.ml is_firstorder_mem
$EX Mona.ml mona_of_exp
$EX Mona.ml mona_of_exp_secondorder
$EX Mona.ml mona_of_b_formula
$EX Mona.ml equation
$EX Mona.ml mona_of_formula
$EX Mona.ml send_cmd_with_answer
$EX Mona.ml send_cmd_with_answer
$EX Mona.ml start
$EX Mona.ml check_answer
$EX Mona.ml create_file_for_mona
$EX Mona.ml write_to_file
$EX Mona.ml imply_sat_helper
$EX Mona.ml imply
$EX Mona.ml mona.is_sat_ops
$EX Musterr.ml find_all_failures
$EX Musterr.ml check_maymust_failure
$EX New-mona.ml is_firstorder_mem
$EX New-mona.ml mona_of_exp
$EX New-mona.ml mona_of_exp_secondorder
$EX New-mona.ml mona_of_b_formula
$EX New-mona.ml equation
$EX New-mona.ml mona_of_formula
$EX New-mona.ml mona.imply
$EX Norm.ml norm_elim_useless_para
$EX Norm.ml norm_elim_useless
$EX Norm.ml view_to_hprel
$EX Norm.ml hprel_to_view
$EX Norm.ml look_for_anonymous_h_formula
$EX Norm.ml convert_anonym_to_exist_formula
$EX Norm.ml recover_view_decl
$EX Norm.ml norm_extract_common_one_view
$EX Norm.ml cont_process_branch
$EX Norm.ml cont_para_analysis
$EX Norm.ml norm_ann_seg_opz
$EX Norm.ml merge_contexts
$EX Norm.ml convert_substitution_helper
$EX Norm.ml back_ptr_of_heap
$EX Norm.ml convert_formula_to_linear
$EX Norm.ml convert_vdef_to_linear
$EX Omega.ml check_formula
$EX Omega.ml send_and_receive
$EX Omega.ml is_sat_ops
$EX Omega.ml is_sat
$EX Omega.ml is_sat_with_check
$EX Omega.ml is_sat_with_check
$EX Omega.ml is_valid
$EX Omega.ml omega.imply_ops_1
$EX Omega.ml [omega.ml]imply_ops_1
$EX Omega.ml match_vars
$EX Omega.ml trans_bool
$EX Omega.ml simplify_ops
$EX Omega.ml simplify
$EX Omega.ml pairwisecheck
$EX Omega.ml hull
$EX Omega.ml gist
$EX Perm.ml drop_tauto
$EX Pi.ml add_relation_to_formula
$EX Pi.ml add_post_relation
$EX Pi.ml add_pre_relation
$EX Pi.ml is_infer_shape
$EX Pi.ml is_infer_post
$EX Pi.ml is_infer_pre
$EX Pi.ml is_infer_others
$EX Pointers.ml modifies
$EX Pointers.ml subst_exp
$EX Pointers.ml trans_exp_ptr
$EX Pointers.ml trans_specs
$EX Pointers.ml compute_vars_to_delete
$EX Pointers.ml trans_proc_decl
$EX Pointers.ml trans_pointers
$EX Predicate.ml pure_of_heap_pred
$EX Predicate.ml trans_rels
$EX Predicate.ml heap_pred_of_pure
$EX Predicate.ml partition_extn_svl
$EX Predicate.ml extend_pred_one_derv
$EX Predicate.ml extend_pred_dervs
$EX Predicate.ml leverage_self_info
$EX Procutils.ml maybe_raise_and_catch_timeout
$EX Procutils.ml maybe_raise_and_catch_timeout
$EX Redlog.ml send_and_receive
$EX Redlog.ml check_formula
$EX Redlog.ml rl_of_formula
$EX Redlog.ml is_linear_formula
$EX Redlog.ml elim_exists_with_eq
$EX Redlog.ml elim_exists_with_ineq
$EX Redlog.ml elim_exist_quantifier
$EX Redlog.ml negate_formula
$EX Redlog.ml is_sat_no_cache
$EX Redlog.ml is_sat
$EX Redlog.ml is_valid
$EX Redlog.ml imply_no_cache
$EX Redlog.ml imply_ops
$EX Redlog.ml imply
$EX Redlog.ml simplify_with_redlog
$EX Rev_ast.ml rev_trans_formula
$EX Rev_ast.ml transform_hp_rels_to_iviews
$EX Sa2.ml find_imply_subst
$EX Sa2.ml subst_cs_w_other_cs
$EX Sa2.ml subst_cs
$EX Sa2.ml split_one
$EX Sa2.ml split_constr
$EX Sa2.ml elim_unused_pre_preds
$EX Sa2.ml elim_unused_post_preds
$EX Sa2.ml  combine_helper2
$EX Sa2.ml obtain_and_norm_def
$EX Sa2.ml combine_pdefs_pre
$EX Sa2.ml generalize_one_hp
$EX Sa2.ml get_pdef_body
$EX Sa2.ml subst_dep_groups
$EX Sa2.ml topo_sort
$EX Sa2.ml pardef_subst_fix:helper
$EX Sa2.ml pardef_subst_fix
$EX Sa2.ml generalize_hps_par_def
$EX Sa2.ml generalize_hps_cs_new
$EX Sa2.ml generalize_hp
$EX Sa2.ml match_hps_views
$EX Sa2.ml partition_constrs
$EX Sa2.ml infer_shapes_init_pre
$EX Sa2.ml infer_shapes_init_post
$EX Sa2.ml infer_shapes_from_fresh_obligation
$EX Sa2.ml infer_shapes_from_obligation
$EX Sa2.ml infer_shapes
$EX Sa2.ml infer_shapes_new
$EX Sa3.ml check_full_path_sensitive
$EX Sa3.ml find_imply_subst
$EX Sa3.ml subst_cs_w_other_cs
$EX Sa3.ml subst_cs
$EX Sa3.ml unfold_def_LHS
$EX Sa3.ml split_one
$EX Sa3.ml split_base_constr
$EX Sa3.ml get_par_defs_pre_fix
$EX Sa3.ml combine_helper2
$EX Sa3.ml obtain_and_norm_def
$EX Sa3.ml combine_pdefs_pre
$EX Sa3.ml generalize_one_hp
$EX Sa3.ml get_pdef_body
$EX Sa3.ml subst_dep_groups
$EX Sa3.ml topo_sort
$EX Sa3.ml pardef_subst_fix
$EX Sa3.ml pardef_subst_fix
$EX Sa3.ml def_subst_fix
$EX Sa3.ml def_subst_fix
$EX Sa3.ml generalize_hps_par_def
$EX Sa3.ml generalize_hps_cs_new
$EX Sa3.ml generalize_hp
$EX Sa3.ml collect_sel_hpdef
$EX Sa3.ml match_one_hp_views
$EX Sa3.ml match_hps_views
$EX Sa3.ml partition_constrs
$EX Sa3.ml infer_pre_synthesize
$EX Sa3.ml infer_pre_fix
$EX Sa3.ml infer_post_fix
$EX Sa3.ml infer_post_synthesize
$EX Sa3.ml infer_shapes_from_fresh_obligation
$EX Sa3.ml infer_shapes_from_obligation
$EX Sa3.ml infer_process_pre_preds
$EX Sa3.ml infer_shapes_proper
$EX Sa3.ml iprocess_action
$EX Sa3.ml infer_shapes_divide
$EX Sa3.ml infer_shapes_conquer
$EX Sa3.ml infer_shapes
$EX Sacore.ml generate_xpure_view_w_pos
$EX Sacore.ml generate_map
$EX Sacore.ml generate_xpure_view_hp
$EX Sacore.ml generate_map_unk_hp
$EX Sacore.ml generate_linking_full_hp
$EX Sacore.ml analize_unk_new
$EX Sacore.ml analize_unk_one
$EX Sacore.ml find_closure_post_hps
$EX Sacore.ml update_unk_one_constr
$EX Sacore.ml update_unk_one_constr
$EX Sacore.ml find_full_unk_hps
$EX Sacore.ml analize_unk
$EX Sacore.ml generate_hp_def_from_unk_hps
$EX Sacore.ml transform_unk_hps_to_pure
$EX Sacore.ml transform_xpure_to_pure
$EX Sacore.ml elim_dangling_conj_heap
$EX Sacore.ml do_elim_unused
$EX Sacore.ml detect_dangling_pred
$EX Sacore.ml sort_hps
$EX Sacore.ml is_inconsistent
$EX Sacore.ml unify_consj_pre
$EX Sacore.ml unify_branches_hpdef
$EX Sacore.ml unify_syntax_equiv_hpdef
$EX Sacore.ml unify_shape_equiv
$EX Sacore.ml check_equiv_wo_libs
$EX Sacore.ml do_unify
$EX Sacore.ml reverify_cond
$EX Sacore.ml norm_overr
$EX Sacore.ml check_pure_exist
$EX Sacore.ml pred_unify_inter
$EX Sacore.ml norm_elim_useless_paras
$EX Sacore.ml reclassify_pre_obligation
$EX Sacore.ml update_explicit_root
$EX Sacore.ml do_entail_check
$EX Sacore.ml shape_gist
$EX Sacore.ml shape_widening
$EX Sacore.ml gfp_iter
$EX Sacore.ml compute_gfp
$EX Sacore.ml lfp_gen_init
$EX Sacore.ml lfp_iter
$EX Sacore.ml elim_diverg_paras
$EX Sacore.ml mk_exp_root
$EX Sacore.ml compute_lfp
$EX Sacore.ml compute_lfp_def
$EX Sacore.ml pred_split_cands_one_branch
$EX Sacore.ml pred_split_cands
$EX Sacore.ml check_split_global
$EX Sacore.ml prove_right_implication
$EX Sacore.ml normalize_hp_defs
$EX Sacore.ml SAC.pure_ext
$EX Sacore.ml prove_split_cand
$EX Sacore.ml SAC.seg_split
$EX Sacore.ml pred_split_hp
$EX Sacore.ml pred_norm_disj
$EX Sa.ml elim_redundant_paras_lst_constr
$EX Sa.ml get_hp_split_cands
$EX Sa.ml check_split_global
$EX Sa.ml subst_constr_with_new_hps
$EX Sa.ml split_hp
$EX Sa.ml look_up_equiv
$EX Sa.ml gen_eqv
$EX Sa.ml update_unk_one_constr
$EX Sa.ml check_partial_def_eq
$EX Sa.ml find_defined_pointers_two_formulas
$EX Sa.ml elim_direct_root_pto
$EX Sa.ml add_xpure_dling
$EX Sa.ml collect_par_defs_one_side_one_hp_rhs
$EX Sa.ml collect_par_defs_one_side_one_hp_rhs
$EX Sa.ml collect_par_defs_one_side_one_hp
$EX Sa.ml collect_par_defs_two_side_one_hp
$EX Sa.ml collect_par_defs_recursive_hp
$EX Sa.ml collect_par_defs_unk_hps
$EX Sa.ml collect_par_defs_one_constr_new
$EX Sa.ml collect_partial_definitions
$EX Sa.ml simplify_constrs
$EX Sa.ml check_unsat
$EX Sa.ml do_simpl_nodes_match
$EX Sa.ml elim_irr_rhs_hps
$EX Sa.ml subst_cs_w_partial_defs
$EX Sa.ml find_imply_subst
$EX Sa.ml subst_cs_w_other_cs_new
$EX Sa.ml simple_unk_info_check
$EX Sa.ml subst_cs
$EX Sa.ml generalize_one_hp
$EX Sa.ml subst_dep_groups
$EX Sa.ml topo_sort
$EX Sa.ml pardef_subst_fix
$EX Sa.ml pardef_subst_fix
$EX Sa.ml def_subst_fix
$EX Sa.ml generalize_hps_par_def
$EX Sa.ml generalize_hps_cs
$EX Sa.ml get_unk_hps_relation
$EX Sa.ml generalize_pure_def_from_hpunk
$EX Sa.ml generalize_hp
$EX Sa.ml generate_hp_def_from_split
$EX Sa.ml generate_init_unk_hpdefs
$EX Sa.ml unify_branches_hpdef
$EX Sa.ml check_eq_hpdef
$EX Sa.ml match_hps_views
$EX Sa.ml collect_sel_hp_def
$EX Sa.ml infer_hps
$EX Sa.ml check_horm_data_decl
$EX Sa.ml build_horm_view
$EX Sa.ml generate_horm_view
$EX Saout.ml transform_hp_rels_to_iviews
$EX Saout.ml syn_hprel
$EX Saout.ml plugin_inferred_iviews
$EX Saout.ml trans_hprel_2_cview
$EX Saout.ml trans_formula_hp_2_view
$EX Saout.ml trans_formula_view_2_hp
$EX Saout.ml trans_hp_def_view_2_hp
$EX Saout.ml case_detection
$EX Saout.ml elim_dup_with_guard
$EX Saout.ml case_struc_formula_trans
$EX Saout.ml plug_shape_into_specs
$EX Sautil.ml close_def
$EX Sautil.ml combine_length_neq
$EX Sautil.ml find_close_hpargs
$EX Sautil.ml elim_eq_shorter_hpargs
$EX Sautil.ml get_hdnodes_hf
$EX Sautil.ml drop_get_hrel
$EX Sautil.ml drop_data_hrel_except
$EX Sautil.ml partition_hp_args
$EX Sautil.ml look_up_dups_node
$EX Sautil.ml find_defined_pointers
$EX Sautil.ml get_defined_eqs
$EX Sautil.ml get_raw_defined_w_pure
$EX Sautil.ml filter_var
$EX Sautil.ml keep_data_view_hrel_nodes
$EX Sautil.ml filter_eq_in_one_hp
$EX Sautil.ml smart_subst
$EX Sautil.ml simp_match_unknown
$EX Sautil.ml do_simpl_nodes_match
$EX Sautil.ml simp_match_hp_w_unknown
$EX Sautil.ml simplify_one_constr_b
$EX Sautil.ml simplify_constrs
$EX Sautil.ml find_well_defined_hp
$EX Sautil.ml split_guard_constrs
$EX Sautil.ml  detect_link_hp
$EX Sautil.ml split_base
$EX Sautil.ml find_well_eq_defined_hp
$EX Sautil.ml simp_matching
$EX Sautil.ml rename_hp_args
$EX Sautil.ml remove_pure_or_redundant_wg
$EX Sautil.ml equiv_unify
$EX Sautil.ml equiv_unify_wg
$EX Sautil.ml remove_subsumed_pure_formula
$EX Sautil.ml check_com_pre_eq_formula
$EX Sautil.ml apply_parttern
$EX Sautil.ml pattern_matching_with_guard
$EX Sautil.ml sort_hps
$EX Sautil.ml is_inconsistent
$EX Sautil.ml remove_irr_eqs
$EX Sautil.ml remove_dups_pardefs
$EX Sautil.ml remove_dups_pardefs_w_neqNull
$EX Sautil.ml remove_equiv_wo_unkhps_wg
$EX Sautil.ml  check_subset_h_fomula
$EX Sautil.ml remove_subset
$EX Sautil.ml  classify_post_fix
$EX Sautil.ml weaken_strengthen_special_constr_pre
$EX Sautil.ml simplify_one_formula
$EX Sautil.ml elim_useless_rec_preds
$EX Sautil.ml norm_hnodes_wg
$EX Sautil.ml norm_guard
$EX Sautil.ml generate_equiv_pdefs
$EX Sautil.ml drop_hp_arguments
$EX Sautil.ml process_one_f
$EX Sautil.ml get_min_common
$EX Sautil.ml find_root
$EX Sautil.ml check_root_accept_dang
$EX Sautil.ml check_root_accept_dang_fs
$EX Sautil.ml refine_dang
$EX Sautil.ml match_with_base
$EX Sautil.ml remove_dups_recursive
$EX Sautil.ml simplify_set_of_formulas_wg
$EX Sautil.ml do_fold_compare
$EX Sautil.ml SAU.norm_fold_seg
$EX Sautil.ml SAU.norm_unfold_seg
$EX Sautil.ml mk_hprel_def_wprocess
$EX Sautil.ml elim_not_in_used_args
$EX Sautil.ml mk_hprel_def_for_subs
$EX Sautil.ml get_longest_common_hnodes_list
$EX Sautil.ml find_closure_eq_null
$EX Sautil.ml find_closure_eq_wg
$EX Sautil.ml norm_conjH_f
$EX Sautil.ml get_sharing 
$EX Sautil.ml partition_common_diff
$EX Sautil.ml mkConjH_and_norm
$EX Sautil.ml simplify_disj
$EX Sautil.ml perform_conj_unify_post_wg
$EX Sautil.ml norm_heap_consj
$EX Sautil.ml norm_heap_consj_formula
$EX Sautil.ml norm_formula
$EX Sautil.ml compose_subs
$EX Sautil.ml succ_subst
$EX Sautil.ml  succ_subst_with_mutrec
$EX Sautil.ml refine_grp_helper
$EX Sautil.ml preprocess_rec_indp
$EX Sautil.ml get_last_ptr
$EX Sautil.ml succ_subst_with_rec_indp
$EX Sautil.ml look_up_subst_hpdef
$EX Sautil.ml succ_subst_hpdef
$EX Sautil.ml combine_hpdefs
$EX Sautil.ml get_pre_fwd
$EX Sautil.ml extract_fwd_pre_defs
$EX Sautil.ml generate_hp_def_from_unk_hps
$EX Sautil.ml transform_unk_hps_to_pure
$EX Sautil.ml partition_tupled
$EX Sautil.ml split_rhs
$EX Sautil.ml simp_tree_one_hp
$EX Sautil.ml simp_tree
$EX Sautil.ml match_one_hp_one_view
$EX Sautil.ml get_pre_post
$EX Sautil.ml cmp_list_subsume_int_rev
$EX Sautil.ml assumption_partition
$EX Sautil.ml pair_dang_constr_path
$EX Sautil.ml find_closed_sel_hp_def
$EX Sautil.ml combine_path_defs
$EX Sautil.ml reuse_equiv_hpdefs
$EX Sautil.ml filter_non_sel
$EX Sautil.ml combine_hpdef_flow
$EX Share_prover_w2.ml simpl
$EX Share_prover_w2.ml sleek_sat_wrapper
$EX Share_prover_w2.ml sleek_imply_wrapper
$EX Share_prover_w.ml simpl
$EX Share_prover_w.ml sleek_sat_wrapper
$EX Share_prover_w.ml sleek_imply_wrapper
$EX Sleekcore.ml check_equiv_list
$EX Sleekcore.ml SC.validate
$EX Sleekengine.ml proc_sleek_result_validate
$EX Sleekengine.ml process_lemma
$EX Sleekengine.ml process_list_lemma
$EX Sleekengine.ml process_data_def
$EX Sleekengine.ml convert_data_and_pred_to_cast
$EX Sleekengine.ml process_barrier
$EX Sleekengine.ml meta_to_struc_formula
$EX Sleekengine.ml Sleekengine.meta_to_formula
$EX Sleekengine.ml run_infer_one_pass
$EX Sleekengine.ml run_entail_check
$EX Sleekengine.ml print_entail_result
$EX Sleekengine.ml process_sat_check
$EX Sleekengine.ml process_entail_check_helper
$EX Sleekengine.ml process_check_norm
$EX Sleekengine.ml get_residue
$EX Sleek.ml parse_first
$EX Sleek.ml proc_one_def
$EX Sleek.ml parse
$EX Slicing.ml get_ctr_n
$EX Slicing.ml merge_mems_nx
$EX Slicing.ml create_memo_group
$EX Slsat.ml check_sat_empty_rhs_with_uo
$EX Smtsolver.ml smt_of_typ
$EX Smtsolver.ml smt_of_formula
$EX Smtsolver.ml smt_of_formula
$EX Smtsolver.ml check_formula
$EX Smtsolver.ml to_smt
$EX Smtsolver.ml smt_imply
$EX Smtsolver.ml smt.imply
$EX Smtsolver.ml is_sat_ops
$EX Smtsolver.ml is_sat
$EX Smtsolver.ml simplify
$EX Smtsolver.ml get_model
$EX Smtsolver.ml norm_model
$EX Solver.ml simple_imply
$EX Solver.ml subst_eqset
$EX Solver.ml pr_branches_subsume 
$EX Solver.ml split_linear_node_guided
$EX Solver.ml combine_context_and_unsat_now
$EX Solver.ml unfold_context_unsat_now
$EX Solver.ml unfold_failesc_context
$EX Solver.ml struc_unfold_heap
$EX Solver.ml unfold_heap
$EX Solver.ml split_universal
$EX Solver.ml normalize_to_CNF
$EX Solver.ml fold_op
$EX Solver.ml process_one
$EX Solver.ml process_fold_result
$EX Solver.ml process_one
$EX Solver.ml elim_exists_mix_formula
$EX Solver.ml elim_exists_memo_pure
$EX Solver.ml elim_exists_pure_branch
$EX Solver.ml entail_state_elim_exists
$EX Solver.ml find_unsat
$EX Solver.ml Solver.tp_syn
$EX Solver.ml elim_unsat_for_unfold
$EX Solver.ml elim_unsat_all
$EX Solver.ml elim_unsat 
$EX Solver.ml get_eqns_free
$EX Solver.ml subs_to_inst_vars
$EX Solver.ml get_eqns_expl_inst
$EX Solver.ml is_barrier_inconsistent_formula
$EX Solver.ml check_barrier_inconsistency_context_svl
$EX Solver.ml check_consistency_context
$EX Solver.ml heap_entail_struc_list_failesc_context
$EX Solver.ml heap_entail_struc_failesc_context
$EX Solver.ml heap_entail_struc_init_bug_inv
$EX Solver.ml heap_entail_struc_init
$EX Solver.ml heap_entail_struc
$EX Solver.ml sem_imply_add
$EX Solver.ml compose_thread_post_condition
$EX Solver.ml heap_entail_conjunct_lhs_struc
$EX Solver.ml heap_entail_split_rhs
$EX Solver.ml heap_entail_init
$EX Solver.ml heap_entail
$EX Solver.ml heap_entail_after_sat
$EX Solver.ml generate_action
$EX Solver.ml process_entail_state
$EX Solver.ml move_expl_inst_ctx_list
$EX Solver.ml move_expl_inst_estate
$EX Solver.ml move_impl_inst_estate
$EX Solver.ml coer_target
$EX Solver.ml check_one_target
$EX Solver.ml heap_entail_split_rhs_phases
$EX Solver.ml eliminate_exist_from_LHS
$EX Solver.ml one_ctx_entail
$EX Solver.ml heap_entail_rhs_nested_phase
$EX Solver.ml insert_ho_frame_in2_formula
$EX Solver.ml heap_entail_split_lhs_phases
$EX Solver.ml heap_entail_with_cont
$EX Solver.ml heap_entail_thread
$EX Solver.ml compute_thread_one_match
$EX Solver.ml compute_thread_matches
$EX Solver.ml process_thread_one_match
$EX Solver.ml process_thread_matches
$EX Solver.ml heap_entail_build_pure_check
$EX Solver.ml xpure_imply
$EX Solver.ml heap_infer_decreasing_wf
$EX Solver.ml subst_rel_by_def
$EX Solver.ml fold_fun_impt
$EX Solver.ml detect_false
$EX Solver.ml solve_ineq 
$EX Solver.ml solve_ineq_pure_formula 
$EX Solver.ml imply_formula_no_memo
$EX Solver.ml do_base_case_unfold_only
$EX Solver.ml do_unfold_for_classic_reasoning
$EX Solver.ml do_lhs_case
$EX Solver.ml do_match_inst_perm_vars
$EX Solver.ml generate_rel_formulas
$EX Solver.ml compute_matching_thread_nodes
$EX Solver.ml do_match
$EX Solver.ml match_one_ho_arg
$EX Solver.ml heap_entail_non_empty_rhs_heap
$EX Solver.ml existential_eliminator_helper
$EX Solver.ml inst_before_fold
$EX Solver.ml do_fold_w_ctx
$EX Solver.ml combine_results
$EX Solver.ml do_fold
$EX Solver.ml do_base_fold
$EX Solver.ml do_full_fold
$EX Solver.ml vdef_of_acc_fold
$EX Solver.ml do_acc_fold
$EX Solver.ml do_seg_fold
$EX Solver.ml push_hole_action
$EX Solver.ml advance_unfold
$EX Solver.ml comp_act
$EX Solver.ml do_infer_heap
$EX Solver.ml do_unmatched_rhs
$EX Solver.ml process_unfold
$EX Solver.ml rank_cand_list
$EX Solver.ml choose_best_candidate 
$EX Solver.ml solver_infer_lhs_contra_first_sat
$EX Solver.ml solver_infer_lhs_contra_list
$EX Solver.ml match_one_ho_arg_simple
$EX Solver.ml do_universal
$EX Solver.ml is_cycle_coer
$EX Solver.ml is_original_match
$EX Solver.ml rewrite_coercion
$EX Solver.ml apply_universal
$EX Solver.ml find_coercions
$EX Solver.ml do_coercion
$EX Solver.ml apply_left_coercion
$EX Solver.ml apply_left_coercion_complex
$EX Solver.ml test_frac_subsume
$EX Solver.ml test_frac_eq
$EX Solver.ml pick_up_node
$EX Solver.ml process_one_normalize
$EX Solver.ml normalize_base_perm
$EX Solver.ml find_one
$EX Solver.ml find_possible_matches
$EX Solver.ml prop_w_coers
$EX Solver.ml process_one_prop_w_coer
$EX Solver.ml apply_right_coercion
$EX Solver.ml elim_exists_exp
$EX Solver.ml elim_exists_exp_loop
$EX Solver.ml combine_struc
$EX Solver.ml normalize_entail_state_w_lemma
$EX Solver.ml prop_entail_state_w_lemma
$EX Solver.ml normalize_list_failesc_context_w_lemma
$EX Solver.ml heap_entail_struc_list_partial_context_init
$EX Solver.ml heap_entail_list_partial_context_init
$EX Solver.ml heap_entail_list_failesc_context_init
$EX Solver.ml verify_pre_is_sat
$EX Solver.ml normalize_frac_heap_shallow
$EX Soutil.ml detect_mem_leak_partial_ctx
$EX Soutil.ml detect_mem_leak
$EX Spass.ml spass_of_formula
$EX Spass.ml check_problem_through_file
$EX Spass.ml check_problem_through_stdin
$EX Spass.ml spass_imply
$EX Spass.ml smt.imply
$EX Spass.ml spass_is_sat
$EX Syn_checkeq.ml check_stricteq_hnodes
$EX Syn_checkeq.ml check_stricteq_vnodes
$EX Syn_checkeq.ml check_stricteq_hrels
$EX Syn_checkeq.ml  check_stricteq_h_fomula
$EX Syn_checkeq.ml checkeq_pure
$EX Syn_checkeq.ml check_relaxeq_formula
$EX Syn_checkeq.ml checkeq_formula_list
$EX Syn_checkeq.ml checkeq_formula_list
$EX Syn_checkeq.ml check_exists_cyclic_proofs
$EX Syn_checkeq.ml syntax_nodes_match
$EX Syn_checkeq.ml syntax_vnodes_match
$EX Syn_checkeq.ml syntax_contrb_lemma_end_null
$EX Template.ml collect_templ_assume_rhs
$EX Template.ml replace_eq_conseq
$EX Template.ml collect_templ_assume_conj_rhs
$EX Template.ml simplify_templ_ante
$EX Template.ml collect_templ_assume_disj_lhs
$EX Template.ml collect_templ_assume_init
$EX Template.ml gen_templ_constr_farkas
$EX Terminf.ml find_potential_lex_single_rank
$EX Terminf.ml infer_loop_status
$EX Terminf.ml infer_pre_cond_iter
$EX Terminf.ml infer_lex_template_res
$EX Term.ml check_term_measures
$EX Term.ml check_term_rhs
$EX Term.ml rank_phase_constr
$EX Term.ml phase_num_infer_one_scc
$EX Term.ml phase_num_infer_by_scc
$EX Term.ml add_phase_constr_by_scc
$EX Term.ml subst_phase_num_struc
$EX Term.ml phase_num_infer_whole_scc
$EX Term.ml check_loop_safety
$EX TermUtils.ml def_lbl
$EX TermUtils.ml strip_lexvar_mix_formula
$EX TermUtils.ml strip_lexvar_lhs
$EX Ti2.ml simplify_disj
$EX Ti2.ml get_full_disjoint_cond_list
$EX Ti2.ml merge_cases_tnt_case_spec
$EX Ti2.ml struc_formula_of_dead_path
$EX Ti2.ml merge_tnt_case_spec_into_struc_formula
$EX Ti2.ml flatten_case_struc
$EX Ti2.ml print_svcomp2015_result
$EX Ti2.ml find_scc_edges
$EX Ti2.ml partition_scc_list
$EX Ti2.ml solve_templ_assume
$EX Ti2.ml templ_rank_constr_of_rel
$EX Ti2.ml infer_abductive_cond
$EX Ti2.ml inst_lhs_trel_abd
$EX Ti2.ml infer_abductive_cond_list
$EX Ti2.ml elim_irrel_formula
$EX Ti2.ml proving_non_termination_one_trrel
$EX Ti2.ml proving_non_termination_trrels
$EX Ti2.ml proving_trivial_termination_one_vertex
$EX Ti2.ml proving_non_termination_scc
$EX Ti3.ml is_infer_term
$EX Ti.ml solve_base_trrels
$EX Ti.ml solve_turel_one_scc
$EX Tlutils.ml tl_normalize_mult
$EX Tlutils.ml tl_normalize_const_mult
$EX Tlutils.ml tl_is_same_degree
$EX Tlutils.ml term_list_of_formula
$EX Tlutils.ml tl_normalize_b_formula
$EX Tlutils.ml most_common_nonlinear_vars
$EX Tlutils.ml tl_get_model
$EX Tlutils.ml linearize_nonlinear_formula
$EX Tlutils.ml norm_sst_pos
$EX Tlutils.ml get_abs_model
$EX Tlutils.ml is_feasible_model
$EX Tlutils.ml search_model_ln
$EX Tlutils.ml get_model_ln
$EX Tlutils.ml tl_get_model
$EX Tlutils.ml find_eq_subst_formula
$EX Tpdispatcher.ml set_tp
$EX Tpdispatcher.ml is_list_constraint
$EX Tpdispatcher.ml elim_exists
$EX Tpdispatcher.ml cnv_ptr_to_int
$EX Tpdispatcher.ml is_ptr_ctr
$EX Tpdispatcher.ml to_ptr
$EX Tpdispatcher.ml cnv_int_to_ptr
$EX Tpdispatcher.ml norm_pure_result
$EX Tpdispatcher.ml build_labels_sat
$EX Tpdispatcher.ml merge_lbls
$EX Tpdispatcher.ml prune_labels_sat
$EX Tpdispatcher.ml build_branches_sat
$EX Tpdispatcher.ml sat_label_filter_helper
$EX Tpdispatcher.ml sat_label_filter
$EX Tpdispatcher.ml imply_label_filter
$EX Tpdispatcher.ml assumption_filter
$EX Tpdispatcher.ml norm_pure_input
$EX Tpdispatcher.ml simplify-syn
$EX Tpdispatcher.ml norm_var_name
$EX Tpdispatcher.ml tp_is_sat_no_cache
$EX  Tpdispatcher.ml tp_is_sat_perm_wrap
$EX Tpdispatcher.ml tp_is_sat_perm
$EX Tpdispatcher.ml sat_cache
$EX Tpdispatcher.ml tp_is_sat
$EX Tpdispatcher.ml norm_pure_input
$EX Tpdispatcher.ml simplify_omega
$EX Tpdispatcher.ml om_pairwisecheck
$EX Tpdispatcher.ml tp_pairwisecheck2
$EX Tpdispatcher.ml pairwisecheck
$EX Tpdispatcher.ml pairwisecheck_raw
$EX Tpdispatcher.ml TP.simplify
$EX Tpdispatcher.ml simplify_raw
$EX Tpdispatcher.ml simplify_2
$EX Tpdispatcher.ml hull
$EX Tpdispatcher.ml om_pairwisecheck
$EX Tpdispatcher.ml tp_pairwisecheck2
$EX Tpdispatcher.ml pairwisecheck
$EX Tpdispatcher.ml pairwisecheck_raw
$EX Tpdispatcher.ml om_gist
$EX Tpdispatcher.ml tp_imply_translate_cyclic
$EX Tpdispatcher.ml tp_imply_translate_waitS
$EX Tpdispatcher.ml tp_imply_concrete_rel
$EX Tpdispatcher.ml tp_imply_preprocess
$EX Tpdispatcher.ml tp_imply_no_cache
$EX Tpdispatcher.ml tp_wrap
$EX Tpdispatcher.ml tp_imply_perm
$EX Tpdispatcher.ml imply_cache
$EX Tpdispatcher.ml tp_imply
$EX Tpdispatcher.ml is_sat
$EX Tpdispatcher.ml imply_timeout 2
$EX Tpdispatcher.ml imply_timeout 3
$EX Tpdispatcher.ml memo_imply_timeout
$EX Tpdispatcher.ml mix_imply_timeout
$EX Tpdispatcher.ml simpl_imply_raw
$EX Tpdispatcher.ml is_sat_sub_no_with_slicing
$EX Tpdispatcher.ml is_sat_memo_sub_no_orig
$EX Tpdispatcher.ml is_sat_memo_sub_no_slicing
$EX Tpdispatcher.ml is_sat_memo_sub_no_ineq_slicing
$EX Tpdispatcher.ml is_sat_memo_sub_no
$EX Tpdispatcher.ml is_sat_mix_sub_no
$EX Tpdispatcher.ml imply_sub_no
$EX Tpdispatcher.ml imply_msg_no_no 
$EX Tpdispatcher.ml imply_raw
$EX Tpdispatcher.ml check_diff
$EX Translate_out_array_in_cpure_formula.ml remove_dupl_spec_var_list
$EX Translate_out_array_in_cpure_formula.ml mk_array_new_name
$EX Translate_out_array_in_cpure_formula.ml contain_array
$EX Translate_out_array_in_cpure_formula.ml normalize_not
$EX Translate_out_array_in_cpure_formula.ml normalize_or
$EX Translate_out_array_in_cpure_formula.ml normalize_to_lst
$EX Translate_out_array_in_cpure_formula.ml split_for_process
$EX Translate_out_array_in_cpure_formula.ml split_and_process
$EX Translate_out_array_in_cpure_formula.ml is_valid_forall
$EX Translate_out_array_in_cpure_formula.ml can_be_simplify
$EX Translate_out_array_in_cpure_formula.ml get_array_index_replacement
$EX Translate_out_array_in_cpure_formula.ml process_quantifier
$EX Translate_out_array_in_cpure_formula.ml standarize_one_formula
$EX Translate_out_array_in_cpure_formula.ml standarize_array_imply
$EX Translate_out_array_in_cpure_formula.ml translate_array_relation
$EX Translate_out_array_in_cpure_formula.ml translate_array_equality
$EX Translate_out_array_in_cpure_formula.ml split_formula
$EX Translate_out_array_in_cpure_formula.ml combine_formula
$EX Translate_out_array_in_cpure_formula.ml extract_translate_scheme
$EX Translate_out_array_in_cpure_formula.ml mk_array_free_formula
$EX Translate_out_array_in_cpure_formula.ml mk_array_free_formula_split
$EX Translate_out_array_in_cpure_formula.ml get_array_element_as_spec_var_list
$EX Translate_out_array_in_cpure_formula.ml process_exists_array
$EX Translate_out_array_in_cpure_formula.ml drop_array_formula
$EX Translate_out_array_in_cpure_formula.ml drop_array_quantifier
$EX Translate_out_array_in_cpure_formula.ml produce_aux_formula
$EX Translate_out_array_in_cpure_formula.ml new_translate_out_array_in_imply_split
$EX Translate_out_array_in_cpure_formula.ml new_translate_out_array_in_one_formula
$EX Translate_out_array_in_cpure_formula.ml new_translate_out_array_in_one_formula_split
$EX Translate_out_array_in_cpure_formula.ml mk_array_equal_formula
$EX Translate_out_array_in_cpure_formula.ml translate_back_array_in_one_formula
$EX Typechecker.ml check_bounded_one_measures
$EX Typechecker.ml check_bounded_term
$EX Typechecker.ml check_specs_infer
$EX Typechecker.ml infer_lock_invariant
$EX Typechecker.ml check_pre_post
$EX Typechecker.ml check_exp
$EX Typechecker.ml check Assign
$EX Typechecker.ml check Assign
$EX Typechecker.ml barrier entail
$EX Typechecker.ml barrier_failesc_context
$EX Typechecker.ml check_cast_body
$EX Typechecker.ml check_pre_post
$EX Typechecker.ml check_exp1
$EX Typechecker.ml check_par_case
$EX Typechecker.ml check_post
$EX Typechecker.ml lookup_called_procs
$EX Typechecker.ml check_prog
$EX Typeinfer.ml must_unify
$EX Typeinfer.ml must_unify_expect
$EX Typeinfer.ml unify_type
$EX Typeinfer.ml unify_expect_modify
$EX Typeinfer.ml sub_type
$EX Typeinfer.ml try_unify_view_type_args
$EX Typeinfer.ml get_spec_var_type_list_infer
$EX Vperm.ml clean_es_heap_list_failesc_ctx_for_par
$EX Vperm.ml compose_list_failesc_context_formula_for_par
$EX Vperm.ml compose_list_failesc_contexts_for_par
$EX Vperm.ml prepare_list_failesc_ctx_for_par
$EX Vperm.ml vperm_entail_set
$EX Vperm.ml vperm_entail_rhs
$EX Wrapper.ml wrap_two_bools
$EX Z3.ml smt_of_typ
$EX Z3.ml smt_of_formula
$EX Z3.ml smt_of_formula
$EX Z3.ml parse_model_to_pure_formula
$EX Z3.ml check_formula
$EX Z3.ml to_smt
$EX Z3.ml smt_imply
$EX Z3.ml smt.imply
$EX Z3.ml is_sat
$EX Z3.ml simplify
$EX Z3.ml get_model
$EX Z3.ml norm_model
$EX Z3m.ml z3m_val_to_int
