EX="./c_num_one.sh "
$EX Astsimp form_body_inv
$EX Astsimp case_normalize_struc_formula
$EX Cast subst_mater_list
$EX Cast subst_mater_list
$EX Cast look_up_view_def_raw
$EX Cast look_up_view_def
$EX C subst_mater_list
$EX C subst_mater_list
$EX C look_up_view_def_raw
$EX C look_up_view_def
$EX Cformula get_node_name
$EX Cformula normalize
$EX Cformula fold_context_left
$EX Cformula add_to_context
$EX CF get_node_name
# $EX Cprinter string_of_proc_decl 
$EX Csvutil alias
$EX Cvutil xpure_mem_enum
$EX Cvutil xpure_heap_mem_enum
$EX Cvutil xpure_symbolic
$EX Cvutil xpure_heap_i
$EX Cvutil xpure_heap_sym_i
$EX Cvutil xpure
$EX Infer filter_var
$EX Infer simplify_contra
$EX Infer infer_lhs_contra
$EX Infer infer_lhs_contra_estate
$EX Infer infer_pure_m
$EX Infer infer_collect_hp_rel
$EX Infer infer_collect_hp_rel_empty_rhs
$EX Infer infer_collect_hp_rel_classsic
$EX Label_only comb_norm
$EX LO comb_norm
$EX Lbl comb_norm
$EX Lemproving verify_lemma
$EX Mcpure imply_memo 2
$EX MCP imply_memo 2
$EX Musterr build_and_failures
$EX Omega omega_of_formula
$EX Omega omega_of_formula_old
$EX Procutils maybe_raise_timeout
$EX Sautil generate_hp_ass
$EX Sleekcore sleek_entail_check
$EX Solver unfold_struc_nth
$EX Solver unfold
$EX Solver unsat_base_nth
$EX Solver elim_unsat_es
$EX Solver elim_unsat_es_now
$EX Solver heap_entail_failesc_prefix_init
$EX Solver heap_entail_one_context_struc
$EX Solver heap_entail_after_sat_struc
$EX Solver helper_inner
$EX Solver heap_entail_one_context
$EX Solver early_hp_contra_detection
$EX Solver early_hp_contra_detection_add_to_list_context
$EX Solver early_pure_contra_detection
$EX Solver heap_entail_conjunct_lhs
$EX Solver heap_n_pure_entail
$EX Solver heap_entail_conjunct
$EX Solver heap_entail_conjunct_helper
$EX Solver heap_entail_build_mix_formula_check
$EX Solver heap_entail_empty_rhs_heap
$EX Solver imply_mix_formula
$EX Solver imply_mix_formula_no_memo
$EX Solver solver_detect_lhs_rhs_contra_all
$EX Solver solver_detect_lhs_rhs_contra
$EX Solver normalize_formula_w_coers
$EX Solver prop_formula_w_coers
$EX Solver heap_entail_struc_list_failesc_context_init
$EX Ti2 simplify
$EX Tpdispatcher simplify_a
$EX Tpdispatcher simplify_with_pairwise
$EX Tpdispatcher imply_one
$EX Tpdispatcher is_sat
$EX Tpdispatcher is_sat_sub_no_c
$EX Tpdispatcher is_sat_sub_no 
$EX TP simplify_a
$EX TP simplify_with_pairwise
$EX TP imply_one
$EX TP is_sat
$EX TP is_sat_sub_no_c
$EX TP is_sat_sub_no 
$EX Typeinfer node2_to_node
$EX TI node2_to_node
$EX Fixcalc compute_fixpoint
$EX Fixcalc compute_fixpoint_td
