ex="./add_prefix.sh" 
$ex acc_fold.ml
$ex astsimp.ml
$ex bind_inference.ml
$ex cfsolver.ml
$ex cfutil.ml
$ex checkeq.ml
$ex checks.ml
$ex cilparser.ml
$ex cjava.ml 
$ex classic.ml
$ex context.ml
$ex cpgraph.ml
$ex cpure_pred.ml
$ex cputil.ml
$ex csvutil.ml
$ex cvclite.ml
$ex cvpermUtils.ml
$ex cvutil.ml
$ex da.ml
$ex derive.ml
$ex drawing.ml
$ex env.ml
$ex exc.ml
$ex expure.ml
$ex fixbag.ml
$ex fixcalc.ml
$ex fixpoint.ml
$ex frame.ml
$ex ghip.ml
$ex globalvars.ml
$ex gui.ml
$ex gUtil.ml
$ex hgraph.ml
$ex hipUtil.ml
$ex hsprinter.ml 
$ex iastUtil.ml
$ex icontext.ml
$ex iincr.ml
$ex immutable.ml
$ex infer.ml
$ex infinity.ml
$ex inliner.ml
$ex iprinter.ml
$ex java.ml
$ex label_only.ml
$ex layout.ml
$ex lemma.ml
$ex lemproving.ml
$ex lemsyn.ml
$ex lemutil.ml
$ex libSleek.ml
$ex log.ml 
$ex lp.ml
$ex main.ml
$ex mcpure_D.ml
$ex mem.ml
$ex minisat.ml
$ex musterr.ml
$ex nativefront.ml
$ex new-mona.ml
$ex norm.ml
$ex old_cvc3.ml
$ex old_musterr.ml
$ex old-parser-w-fperm.ml
$ex old_smtsolver.ml
$ex others.ml
$ex parse_cmd.ml
$ex parse_fixbag.ml
$ex parse_fix.ml
$ex parser.ml
$ex parse_shape.ml
$ex piecewise.ml
$ex pi.ml
$ex pointers.ml
$ex predcomp.ml
$ex predicate.ml
$ex procutils.ml
$ex rank.ml
$ex rev_ast.ml
$ex rtc.ml
$ex sa2.ml
$ex sa3.ml
$ex sacore.ml
$ex sa.ml
$ex saout.ml
$ex sap.ml
$ex sautil.ml
$ex sleekcommons.ml
$ex sleekcore.ml
$ex sleekengine.ml
$ex sleek.ml
$ex slicing.ml
$ex slk2smt.ml
$ex slsat.ml
$ex solver.ml
$ex soutil.ml
$ex specutil.ml
$ex syn_checkeq.ml
$ex template.ml
$ex terminf.ml
$ex term.ml
$ex termUtils.ml
$ex test.ml
$ex ti2.ml
$ex ti.ml
$ex tlutils.ml
$ex tpdispatcher.ml
$ex tree_shares.ml
$ex typechecker.ml
$ex typeinfer.ml
$ex view_generator.ml
$ex vperm.ml
$ex xmlfront.ml
$ex z3m.ml