EX="./slk_diff_one.sh"
$EX draft/err1-test_for_infer.slk
$EX draft/err2a-test_for_infer.slk
$EX draft/err2b-test_for_infer.slk
$EX draft/err2-test_for_infer.slk
$EX draft/ex11d1-rel-update.slk
$EX draft/ex11d2-rel-update.slk
$EX draft/ex11d3-rel-update.slk
$EX draft/ex11e-update-prove.slk
$EX draft/ex12b1-update-arr.slk
$EX draft/ex12b2-update-arrvar.slk
$EX draft/ex12f1-simpliy-arr-issue.slk
$EX draft/ex12f-simpliy-arr-issue.slk
$EX draft/ex20-simplify.slk
$EX draft/ex3a-ato-err.slk
$EX draft/ex3-arr-infer.slk
$EX draft/ex3b-ato-err.slk
$EX draft/ex4b-working-check-arr.slk
$EX draft/ex4-check-arr.slk
$EX draft/ex5-oc-redundant.slk
$EX draft/ex6-infer-fail.slk
$EX draft/new_scheme_test.slk
$EX draft/sleek1.slk
$EX draft/test_for_infer.slk
$EX draft/x.slk
$EX test/ex5-infer-relation.slk
$EX test/ex6a-infer-rel-long.slk
$EX test/ex6-infer-rel-long.slk
$EX test/ex6-vs-ex7b.slk
$EX test/ex7a-whole-array-fixpt_working.slk
$EX test/ex7b-whole-array-fixpt_working.slk
$EX test/ex7c1-whole-array-fixpt_working.slk
$EX test/ex7c2-whole-array-fixpt_working.slk
$EX test/ex7-whole-array-fixpt.slk
$EX test/ex8-var-fixpt.slk
$EX test/t1_no_quantifier.slk
$EX test/test_for_infer.slk
