;; Emacs mode for ordered context-free grammar (OCFG)

(defun ocfg-mode ()
  (interactive)
  (kill-all-local-variables)
  (setq mode-name "ocfg")
  (setq major-mode 'sugar-mode)
  (setq comment-indent-function 'lisp-comment-indent)
  (setq comment-start "// ")
  (setq comment-start-skip "//+ *")
  (setq comment-end "")
  (setq font-lock-keywords '(
    ("= " 0 font-lock-builtin-face)
    ("< " 0 font-lock-builtin-face)
    ("> " 0 font-lock-builtin-face)
    ("'[^\\']*'" 0 font-lock-string-face)
    ("\\b[A-Z].*?:" 0 font-lock-doc-string-face)
    ("\\b[a-z].*?:" 0 font-lock-variable-name-face)
    ("//.*" 0 'font-lock-comment-face t)))
  (font-lock-mode 1))
