HIP=../../../hip
echo "sll-delete"
$HIP ll-delete.c  --pred-en-dangling --pred-en-equiv --sa-dp | grep  "verification time"
echo "sll-reverse"
$HIP sll-reverse.c --pred-en-dangling --pred-en-equiv  --sa-dp | grep  "verification time"
echo "sll-insert"
$HIP sll-insert.c --sa-dp  --pred-en-dangling --pred-en-equiv | grep  "verification time"
 echo "sll-last"
 $HIP sll-last-2.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "zip_paper_eq"
$HIP zip_paper_eq.c --pred-en-dangling --pred-en-equiv --sa-dp | grep  "verification time"
echo "zip_paper_leq"
$HIP zip_paper_leq.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
# echo "qsort-2.ss"
# $HIP qsort-2.ss   | grep  "verification time"
echo " sll-bubble.c"
$HIP sll-bubble.c --pred-disj-unify  --sa-dp  --pred-en-equiv | grep  "verification time"
echo "sll-insertsort.c"
$HIP sll-insertsort.c   --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "sll+head"
$HIP check-sll-head.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "sll+tail"
$HIP check-sll-tail.c   --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "skip-list2.ss"
$HIP skip2-list.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "skip-list3.ss"
$HIP skip3-list.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-sorted"
$HIP check-sorted.c  --sa-en-pure-field  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-CSll"
$HIP check-cll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "CSll"
$HIP cll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-CSllclls"
$HIP check-cllclls.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo " 0/1 SLLs"
$HIP sll-01-slls.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "sll2dll"
$HIP sll-dll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-dll"
$HIP check-dll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "dll-app"
$HIP dll-append_paper.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-cdll"
$HIP check-cdll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-cdll5clls"
$HIP check-cdll5clls.c   --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check-cdllcllsx2"
$HIP check-cdllcllsx2.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
# echo "dll-del"
# $HIP dll-del.ss  | grep  "verification time"
echo "bt-search-2.ss"
$HIP bt-search-2.c   --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "tree-parent.ss"
$HIP tree-2.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "rose-tree"
$HIP rose-sll-1.c   --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "swl"
$HIP swl.c --parser default   --sa-dp  --pred-en-equiv | grep  "verification time"
echo "check mcf"
$HIP check-mcf.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "tll"
$HIP tll.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
# echo "check tree+multi"
# $HIP check-multi-tree.ss   | grep  "verification time"
echo "check tll"
$HIP check-tll.c --parser default  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
echo "check tll-parent"
$HIP tll-parent.c  --sa-dp --pred-en-dangling --pred-en-equiv | grep  "verification time"
