HIP=../../../hip
echo "sll-delete"
$HIP ll-delete.c  -tp z3 --sa-dp --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "sll-reverse"
$HIP sll-reverse.c -tp z3 --sa-dp  --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "sll-insert"
$HIP sll-insert.c -tp z3 --sa-dp  --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "set-tail"
$HIP set-tail-2.c -tp z3 --sa-dp  --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
 echo "sll-last"
 $HIP sll-last-2.c  -tp z3  --sa-dp  --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "zip_paper_eq"
$HIP zip_paper_eq.c  -tp z3  --sa-dp --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "zip_paper_leq"
$HIP zip_paper_leq.c  -tp z3  --sa-dp  --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
# echo "qsort-2.ss"
# $HIP qsort-2.ss   | grep  "verification time"
echo " sll-bubble.c"
$HIP sll-bubble.c -tp z3 --pred-disj-unify  --sa-dp  --pred-seg-unify --pred-dis-dangling --pred-dis-useless-para | grep  "verification time"
echo "sll-insertsort.c"
$HIP sll-insertsort.c  -tp z3 --pred-dis-dangling  --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo "sll+head"
$HIP check-sll-head.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "sll+tail"
$HIP check-sll-tail.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "skip-list2.ss"
$HIP skip2-list.c  -tp z3 --pred-dis-dangling --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo "skip-list3.ss"
$HIP skip3-list.c -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check-sorted"
$HIP check-sorted.c -tp z3 --sa-en-pure-field  --sa-dp --pred-dis-dangling --pred-dis-useless-para  | grep  "verification time"
echo "check-CSll"
$HIP check-cll.c -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "CSll"
$HIP cll.c -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check-CSllclls"
$HIP check-cllclls.c -tp z3 --pred-dis-dangling --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo " 0/1 SLLs"
$HIP sll-01-slls.c  -tp z3 --pred-dis-dangling --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo "sll2dll"
$HIP sll-dll.c -tp z3  --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check-dll"
$HIP check-dll.c  -tp z3 --pred-dis-dangling --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo "dll-app"
$HIP dll-append_paper.c -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check-cdll"
$HIP check-cdll.c -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check-cdll5clls"
$HIP check-cdll5clls.c  -tp z3 --pred-dis-dangling --sa-dp  --pred-dis-useless-para | grep  "verification time"
echo "check-cdllcllsx2"
$HIP check-cdllcllsx2.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
# echo "dll-del"
# $HIP dll-del.ss  | grep  "verification time"
echo "bt-search-2.ss"
$HIP bt-search-2.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "tree-parent.ss"
$HIP tree-2.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "rose-tree"
$HIP rose-sll-1.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para  | grep  "verification time"
echo "swl"
$HIP swl.ss  -tp z3  --pred-dis-dangling  --sa-dp --pred-dis-useless-para  | grep  "verification time"
echo "check mcf"
$HIP check-mcf.c   -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "tll"
$HIP tll.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
# echo "check tree+multi"
# $HIP check-multi-tree.ss   | grep  "verification time"
echo "check tll"
$HIP check-tll.c -tp z3  --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
echo "check tll-parent"
$HIP tll-parent.c  -tp z3 --pred-dis-dangling  --sa-dp --pred-dis-useless-para | grep  "verification time"
