echo "sll-reverse"
../../hip sll-reverse.ss   | grep  "verification time"
# echo "sll-last"
# ../../hip sll-last-2.ss  | grep  "verification time"
echo "sll-insertsort.ss"
../../hip sll-insertsort.ss   | grep  "verification time"
# echo "qsort-2.ss"
# ../../hip qsort-2.ss   | grep  "verification time"
echo " sll-bubble.ss"
../../hip sll-bubble.ss --pred-en-oblg --pred-disj-unify | grep  "verification time"
echo "zip_paper_eq"
../../hip zip_paper_eq.ss  | grep  "verification time"
echo "sll+tail"
../../hip check-sll-tail.ss  | grep  "verification time"
echo "sll+head"
../../hip check-sll-head.ss  | grep  "verification time"
echo "skip-list.ss"
../../hip skip0.ss  | grep  "verification time"
echo "check-sorted"
../../hip check-sorted.ss  --sa-en-pure-field | grep  "verification time"
echo "CSll"
../../hip cll.ss  | grep  "verification time"
echo "check-CSll"
../../hip check-cll.ss  | grep  "verification time"
echo " 0/1 SLLs"
../../hip sll-01-slls.ss  | grep  "verification time"
echo "check-CSll-CSLLs"
../../hip check-cllclls.ss  | grep  "verification time"
echo "sll2dll"
../../hip sll-dll.ss  | grep  "verification time"
echo "check-dll"
../../hip check-dll.ss  | grep  "verification time"
echo "check-cdll"
../../hip check-cdll.ss  | grep  "verification time"
echo "check-cdllclls"
../../hip check-cdllclls.ss  | grep  "verification time"
echo "check-cdllcllsx2"
../../hip check-cdllcllsx2.ss  | grep  "verification time"
echo "check-cdllcllsplus2"
../../hip check-cdllcllsplus2.ss  | grep  "verification time"
echo "dll-app"
../../hip dll-append_paper.ss  | grep  "verification time"
# echo "dll-del"
# ../../hip dll-del.ss  | grep  "verification time"
echo "bt-search-2.ss"
../../hip bt-search-2.ss  | grep  "verification time"
echo "bt-go-left.ss"
../../hip bt-left2.ss  | grep  "verification time"
echo "tll"
../../hip tll.ss    | grep  "verification time"
echo "rose-tree"
../../hip rose-sll-1.ss    | grep  "verification time"
# echo "check tree+multi"
# ../../hip check-multi-tree.ss   | grep  "verification time"
echo "check mcf"
../../hip check-mcf.ss   | grep  "verification time"
echo "check tll"
../../hip check-tll.ss   | grep  "verification time"
