echo "sll-create"
../../hip sll-create.ss  | grep  "verification time"
echo "sll-deleteall"
../../hip sll-delete-all.ss | grep  "verification time"
echo "sll-search-delete"
../../hip sll-delete-if.ss | grep  "verification time"
echo "ll-append5.ss"
../../hip sll-append_paper.ss | grep  "verification time"
echo "sll-reverse"
../../hip sll-reverse.ss  | grep  "verification time"
echo "ll-insert"
../../hip sll-insert.ss  | grep  "verification time"
echo "sll-set-tail"
../../hip sll-tail-2.ss  | grep  "verification time"
echo "ll-get-next-next"
../../hip sll-get-next-next.ss --sa-dangling | grep  "verification time"
echo "sll-last"
../../hip sll-last-2.ss  | grep  "verification time"
echo "bubblesort.ss"
echo "mergesort.ss"
echo "insertsort.ss"
echo "qsort-2.ss"
../../hip qsort-2.ss  | grep  "verification time"
echo "sll+head"
../../hip single_paper.ss --en-pre-oblg | grep  "verification time"
echo "sll2dll"
../../hip sll-dll.ss | grep  "verification time"
echo "zip_paper_eq"
../../hip zip_paper_eq.ss | grep  "verification time"
echo "zip_paper_leq"
../../hip zip_paper_leq.ss | grep  "verification time"
echo " CSLLs"
echo " 0/1 SLLs"
echo "skip-list.ss"
echo "CSll"
../../hip cll.ss  | grep  "verification time"
echo "check-positive"
../../hip check-pos | grep  "verification time"
echo "check-sorted"
../../hip sorted.ss  | grep  "verification time"
echo "check-zip-eq.ss"
../../hip check-zip-eq.ss  | grep  "verification time"
echo "check-zip-leq.ss"
../../hip check-zip-leq.ss  | grep  "verification time"
echo "check-dll"
../../hip check-dll.ss  | grep  "verification time"
echo "dll-insert"
echo "dll-app"
../../hip dd-append_paper.ss  | grep  "verification time"
echo "dll-rev"
echo "dll-del0"
echo "Cdll"
echo "bt-count-1.ss"
../../hip bt-count-1.ss  | grep  "verification time"
echo "bt-trav.ss"
../../hip bt-trav.ss | grep  "verification time"
echo "bt-search-2.ss"
../../hip bt-search-2.ss | grep  "verification time"
echo "bt-left2.ss"
../../hip bt-left2.ss   | grep  "verification time"
echo "tree+parent"
../../hip tree.ss   | grep  "verification time"
echo "tll"
../../hip tll.ss   | grep  "verification time"
echo "avl-find"
echo "insertnobal"
echo "rbtree-find"
echo "rose-tree"
../../hip tree.ss   | grep  "verification time"
echo "tree-dsw"
echo "mcf"
echo "check tree+multi"
../../hip check-multi-tree.ss   | grep  "verification time"
echo "check mcf"
../../hip check-mcf.ss   | grep  "verification time"
echo "check tll"
../../hip check-tll.ss   | grep  "verification time"




