Procedure Compute_Base$barrier SUCCESS.
Procedure Compute_Normal$barrier SUCCESS.
Procedure Compute_Octree$barrier SUCCESS.
Procedure Compute_Opacity$barrier SUCCESS.
Procedure Init_Decomposition$int SUCCESS.
Procedure Init_Options$int~int SUCCESS.
Procedure Load_Map$ SUCCESS.
Procedure Load_Normal$ SUCCESS.
Procedure Load_Opacity$ SUCCESS.
Procedure Frame$barrier~barrier~int~int~int~int~int~int~int SUCCESS.
Procedure Normal_Compute$barrier SUCCESS.
Procedure Opacity_Compute$barrier SUCCESS.
Procedure Or_Neighbors_In_Base$barrier SUCCESS.
Procedure Ray_Trace$barrier~int~int SUCCESS.
Procedure Render$barrier~int~int SUCCESS.
Procedure f_r_1934_while_92_2$int~int~barrier~int~int~barrier SUCCESS.
Procedure Render_Loop$barrier~barrier~int~int~int SUCCESS.
Procedure getAdaptive$ SUCCESS.
Procedure getNumNodes$ SUCCESS.
Procedure getRotateSteps$ SUCCESS.
Procedure main$ SUCCESS.
