/* Generated by CIL v. 1.4.0 */
/* print_CIL_Input is true */

int main(void) 
  requires true
  ensures true
{
 int x ;

 {
 x = x + 1;
 x = x - 1;
 x = x + 2;
 x = x - 2;
 x = x * 2;
 x = x / 2;
 return (0);
}
}
