../../hip valid-1.ss > 1.n
../../hip valid-1a.ss > 1a.n
../../hip valid-1b.ss > 1b.n
../../hip valid-1c.ss > 1c.n
../../hip valid-1d.ss > 1d.n
../../hip valid-1e.ss --dis-phase-num > 1e.n
../../hip invalid-1.ss > w1.n
../../hip invalid-1a.ss > w1a.n
../../hip invalid-1b.ss > w1b.n
../../hip invalid-1c.ss > w1c.n
../../hip invalid-1d.ss > w1d.n
../../hip invalid-1e.ss > w1e.n
../../hip infer-1.ss > p1.n
../../hip infer-2.ss > p2.n
../../hip infer-3.ss > p3.n
../../hip infer-4.ss > p4.n
../../hip infer-6a.ss > p6a.n
../../hip infer-6b.ss > p6b.n
../../hip infer-gcd-1.ss > p-gcd-1.n
../../hip infer-gcd-2.ss > p-gcd-2.n
../../hip infer-mutual-1.ss > p-mutual-1.n
