echo "syn-mix-1"
../sleek syn-mix-1.slk --lem-en-syn  | grep  "Fail"
echo "syn-mix-2"
../sleek syn-mix-2.slk --lem-en-syn  | grep  "Fail"
echo "syn-ll"
../sleek syn-ll.slk    --lem-en-syn  | grep  "Fail"
echo "syn-lseg-1"
../sleek syn-lseg-1.slk --lem-en-syn     | grep  "Fail"
echo "syn-lseg-2"
../sleek syn-lseg-2.slk --lem-en-syn     | grep  "Fail"
echo "syn-dseg-new"
../sleek syn-dseg-new.slk --lem-en-syn     | grep  "Fail"
echo "syn-ls"
../sleek syn-ls.slk --lem-en-syn     | grep  "Fail"

