This test was automatically generated from the corresponding example in examples/working/.

  $ ../../../sleek.exe --dsd --en-inf --dis-eps infinity.slk | ./sleek_postprocess.sh 
  Entail 1: Fail
  Entail 2: Valid
  Entail 3: Valid
  Entail 4: Fail
  Entail 5: Valid
  Entail 6: Valid
  Entail 7: Fail
  Entail 8: Valid
  Entail 9: Valid
  Entail 10: Valid
  Entail 11: Fail
  Entail 12: Valid
  Entail 13: Valid
  Entail 14: Fail
  Entail 15: Fail
  Entail 16: Valid
  Entail 17: Fail
  Entail 18: Valid
  Entail 19: Fail
  Entail 20: Fail
  Entail 21: Valid
  Entail 22: Valid
  Entail 23: Fail
  Entail 24: Valid
  Entail 25: Fail
  Entail 26: Valid
  Entail 27: Valid
  Entail 28: Valid
  Entail 29: Valid
  Entail 30: Valid
  Entail 31: Valid
  Entail 32: Valid
  Entail 33: Valid
  Entail 34: Valid
  Entail 35: Valid
  Entail 36: Valid
  Entail 37: Valid
  Entail 38: Valid
  Entail 39: Valid
  Entail 40: Valid
  Entail 41: Fail
  Entail 42: Valid
  Entail 43: Valid
  Entail 44: Fail
  Entail 45: Valid
  Entail 46: Fail
  Entail 47: Valid
  Entail 48: Valid
  Entail 49: Valid
  Entail 50: Fail
  Entail 51: Fail
  Entail 52: Valid
  Entail 53: Fail
  Entail 54: Fail
  Entail 55: Valid
  Entail 56: Valid
  Entail 57: Valid
  Entail 58: Valid
  Entail 59: Valid
  Entail 60: Fail
  Entail 61: Fail
  Entail 62: Valid
  Entail 63: Valid
  Entail 64: Valid
  Entail 65: Fail
  Entail 66: Valid
  Entail 67: Valid
  Entail 68: Valid
  Entail 69: Valid
  Entail 70: Valid
  Entail 71: Fail
  Entail 72: Valid
  Entail 73: Fail
  Entail 74: Valid
  Entail 75: Valid
  Entail 76: Valid
  Entail 77: Valid
  Entail 78: Valid
