EX="./diff_one.sh"
$EX bugs/app.ss
$EX bugs/bind2.ss
$EX bugs/check-mcf-4.ss
$EX bugs/funny.ss
$EX bugs/i-app1.ss
$EX bugs/i-app.ss
$EX bugs/i-cll.ss
$EX bugs/ll-last2.ss
$EX bugs/ll-prepend.ss
$EX bugs/lsgA.ss
$EX bugs/lsgB1.ss
$EX bugs/lsgB.ss
$EX bugs/lsg.ss
$EX bugs/ltail.ss
$EX bugs/set-tail2.ss
$EX bugs/set-tail.ss
$EX bugs/sll-dll1a.ss
$EX bugs/sll-dll2.ss
$EX bugs/sll-dll3.ss
$EX bugs/sll-dll.ss
$EX bugs/tail-2.ss
$EX bugs/tail2.ss
$EX bugs/tail3.ss
$EX bugs/tail.ss
$EX bugs/tree-trav-1.ss
$EX bugs/tree-trav.ss
$EX cutpoint/ll-prepend.ss
$EX demo/app.ss
$EX demo/array-ll.ss
$EX demo/assert-1a.ss
$EX demo/assert-1.ss
$EX demo/assert2.ss
$EX demo/assert.ss
$EX demo/cll-inf.ss
$EX demo/cll.ss
$EX demo/cyc-llist-1.ss
$EX demo/cyc-lseg-2.ss
$EX demo/cyc-lseg-3.ss
$EX demo/cyc-lseg-4.ss
$EX demo/cyc-lseg-lem.ss
$EX demo/cyc-lseg.ss
$EX demo/cyc-tree-1.ss
$EX demo/dll-app-bug3.ss
$EX demo/dll-append2.ss
$EX demo/dll-append3.ss
$EX demo/dll-append.ss
$EX demo/dll-copy.ss
$EX demo/dll-create.ss
$EX demo/dll-findnback.ss
$EX demo/dll-rev.ss
$EX demo/dll-xisa-f.ss
$EX demo/foo-1.ss
$EX demo/foo1.ss
$EX demo/foo-2.ss
$EX demo/foo.ss
$EX demo/glist-1.ss
$EX demo/heapify.ss
$EX demo/id.ss
$EX demo/last-2.ss
$EX demo/last.ss
$EX demo/ll-back-1.ss
$EX demo/ll-back-2.ss
$EX demo/ll-back-3a.ss
$EX demo/ll-back-3.ss
$EX demo/ll-back-4.ss
$EX demo/ll-back.ss
$EX demo/ll-delete.ss
$EX demo/ll-ins-sort.ss
$EX demo/loop1.ss
$EX demo/loop-3.ss
$EX demo/loop-4.ss
$EX demo/loop.ss
$EX demo/marktree-bug-1.ss
$EX demo/marktree.ss
$EX demo/pair2.ss
$EX demo/pair-bug1.ss
$EX demo/pair-bug2.ss
$EX demo/pair.ss
$EX demo/queue.ss
$EX demo/ref-1.ss
$EX demo/rose-sll-1.ss
$EX demo/rose-sll.ss
$EX demo/rose-tree-inf0.ss
$EX demo/rose-tree-inf1.ss
$EX demo/rose-tree.ss
$EX demo/rose-tree-s.ss
$EX demo/schorr-waite-list.ss
$EX demo/schorr-waite.ss
$EX demo/set-tail-2.ss
$EX demo/set-tail.ss
$EX demo/simpl-tree-trav.ss
$EX demo/single-1p.ss
$EX demo/single-1.ss
$EX demo/single.ss
$EX demo/sll-dll-1.ss
$EX demo/sll-dll-2.ss
$EX demo/sll-dll-bug-1.ss
$EX demo/sll-reverse-1.ss
$EX demo/sll-reverse-2.ss
$EX demo/sll-reverse-3a.ss
$EX demo/sll-reverse-3.ss
$EX demo/sorted-1a.ss
$EX demo/sorted-1.ss
$EX demo/swl-0a.ss
$EX demo/swl-0b.ss
$EX demo/swl-0-set.ss
$EX demo/swl-0.ss
$EX demo/swl-1.ss
$EX demo/swl-2.ss
$EX demo/swl-3.ss
$EX demo/swl-4-addr-lbl2.ss
$EX demo/swl-4.ss
$EX demo/swl-5.ss
$EX demo/swl-h.ss
$EX demo/swl-h-v.ss
$EX demo/swl-i-sa.ss
$EX demo/swl-i.ss
$EX demo/swl-j1.ss
$EX demo/swl-j2.ss
$EX demo/swl-j.ss
$EX demo/swl-ok.ss
$EX demo/swl.ss
$EX demo/swt-0.ss
$EX demo/swt-1-set.ss
$EX demo/swt-1.ss
$EX demo/test1.ss
$EX demo/test-mut.ss
$EX demo/test-snd.ss
$EX demo/tll-2.ss
$EX demo/tll2.ss
$EX demo/tll3.ss
$EX demo/tll-if-2.ss
$EX demo/tll-if.ss
$EX demo/tll.ss
$EX demo/tree-1.ss
$EX demo/tree-2.ss
$EX demo/tree-3.ss
$EX demo/tree-conj-1.ss
$EX demo/tree.ss
$EX demo/two.ss
$EX demo/view_simp_bug.ss
$EX demo/view_simp.ss
$EX demo/xisa-remove1.ss
$EX demo/xisa-remove2.ss
$EX demo/xisa-remove.ss
$EX demo/zip1a.ss
$EX demo/zip-1.ss
$EX demo/zip-same.ss
$EX demo/zip.ss
$EX errors/alias.ss
$EX errors/c-next.ss
$EX errors/dll-insert1.ss
$EX errors/dll-next.ss
$EX errors/dll-prev.ss
$EX errors/ex1.ss
$EX errors/ex2.ss
$EX errors/ll-append.ss
$EX errors/ll-concat.ss
$EX errors/ll-delete.ss
$EX errors/ll-find.ss
$EX errors/ll-get-size.ss
$EX errors/ll-insert.ss
$EX errors/ll-last2.ss
$EX errors/ll-last.ss
$EX errors/ll-merge.ss
$EX errors/ll-next1.ss
$EX errors/ll-next2.ss
$EX errors/ll-next3.ss
$EX errors/ll-next4.ss
$EX errors/ll-next5.ss
$EX errors/ll-next6.ss
$EX errors/ll-next.ss
$EX errors/ll-nth.ss
$EX errors/ll-prepend.ss
$EX errors/ll-remove.ss
$EX errors/ll-reverse.ss
$EX errors/ll-size.ss
$EX errors/ll-traverse.ss
$EX errors/ll-val.ss
$EX errors/next2.ss
$EX errors/next-a.ss
$EX errors/next.ss
$EX errors/temp.ss
$EX errors/test1.ss
$EX errors/test.ss
$EX errors/tree-insert.ss
$EX errors/tree-max.ss
$EX errors/tree-min.ss
$EX errors/tree-rem.ss
$EX errors/tree-size.ss
$EX errors/tree-traverse.ss
$EX errors/tree-val.ss
$EX errors/v-next2.ss
$EX errors/v-next5a.ss
$EX errors/v-next5b1.ss
$EX errors/v-next5b.ss
$EX errors/v-next5.ss
$EX errors/v-next.ss
$EX hip2/bug-imm.ss
$EX hip2/cll-del.ss
$EX hip2/cll.ss
$EX hip2/foo.ss
$EX hip2/ll-del.ss
$EX hip2/ll-getnext2a.ss
$EX hip2/ll-getnext2.ss
$EX hip2/ll-getnext3.ss
$EX hip2/ll-getnext.ss
$EX hip/acycle-ll.ss
$EX hip/bst-1.ss
$EX hip/bt-count-1.ss
$EX hip/bt-search-1.ss
$EX hip/bt-search-2.ss
$EX hip/bt-trav.ss
$EX hip/cll-inf.ss
$EX hip/dll-insert1.ss
$EX hip/dll-insert.ss
$EX hip/ex1a.ss
$EX hip/ex1b.ss
$EX hip/ex1c.ss
$EX hip/ex1.ss
$EX hip/ex2.ss
$EX hip/fun-call.ss
$EX hip/ll_all10.ss
$EX hip/ll_all11.ss
$EX hip/ll_all_12.ss
$EX hip/ll_all_13a1.ss
$EX hip/ll_all_13a.ss
$EX hip/ll_all_13b.ss
$EX hip/ll_all_13c1.ss
$EX hip/ll_all_13c.ss
$EX hip/ll_all_13d.ss
$EX hip/ll_all_13e.ss
$EX hip/ll_all_13f.ss
$EX hip/ll_all_13.ss
$EX hip/ll_all_14.ss
$EX hip/ll_all_15.ss
$EX hip/ll_all1.ss
$EX hip/ll_all2a.ss
$EX hip/ll_all2b.ss
$EX hip/ll_all2c.ss
$EX hip/ll_all2.ss
$EX hip/ll_all3.ss
$EX hip/ll_all4.ss
$EX hip/ll_all5.ss
$EX hip/ll_all6.ss
$EX hip/ll_all7.ss
$EX hip/ll_all8.ss
$EX hip/ll_all9.ss
$EX hip/ll_all.ss
$EX hip/ll-app2.ss
$EX hip/ll-append10.ss
$EX hip/ll-append2.ss
$EX hip/ll-append3.ss
$EX hip/ll-append4.ss
$EX hip/ll-append5.ss
$EX hip/ll-append6a.ss
$EX hip/ll-append6.ss
$EX hip/ll-append7.ss
$EX hip/ll-append8.ss
$EX hip/ll-append9.ss
$EX hip/ll-append.ss
$EX hip/ll-app.ss
$EX hip/ll-delete2.ss
$EX hip/ll-delete.ss
$EX hip/ll-del.ss
$EX hip/ll-get-next2-norm.ss
$EX hip/ll-get-next-next.ss
$EX hip/ll-get-next.ss
$EX hip/ll-get-size.ss
$EX hip/ll-insert.ss
$EX hip/ll_ms.ss
$EX hip/ll-next2.ss
$EX hip/ll-next3.ss
$EX hip/ll-next4.ss
$EX hip/ll-next5err.ss
$EX hip/ll-next5.ss
$EX hip/ll-next6.ss
$EX hip/ll-pop-front.ss
$EX hip/ll-push-front.ss
$EX hip/ll-ret-first1.ss
$EX hip/ll-ret-first2.ss
$EX hip/ll-ret-first3.ss
$EX hip/ll-ret-first.ss
$EX hip/ll-reverse-byhand.ss
$EX hip/ll-reverse-incorrect_infer.ss
$EX hip/ll-reverse-norm.ss
$EX hip/ll-reverse.ss
$EX hip/ll-size.ss
$EX hip/ll.ss
$EX hip/ll-traverse_byhand.ss
$EX hip/ll-traverse.ss
$EX hip/s3.ss
$EX hip/skip-list.ss
$EX hip/tree-traverse-ERROR.ss
$EX hip/tree-traverse.ss
$EX hip/tree-trav.ss
$EX infer/ll-append.ss
$EX infer/ll.ss
$EX lemma/ll-insert-last.ss
$EX norm/llnth.ss
$EX norm/merge.ss
$EX norm/pure-extn.ss
$EX norm/zip1.ss
$EX norm/zip-2-norm.ss
$EX norm/zip-le-2.ss
$EX norm/zip-le.ss
$EX norm/zip-norm-2.ss
$EX norm/zip-norm.ss
$EX norm/zip_paper_eq-1.ss
$EX norm/zip_paper_eq-2.ss
$EX norm/zip_paper_eq.ss
$EX norm/zip.ss
$EX nov2013/ll-create.ss
$EX nov2013/lldel.ss
$EX nov2013/ll-del-val.ss
$EX nov2013/ll-last.ss
$EX nov2013/sll-bubble.ss
$EX nov2013/sll-find-sorted.ss
$EX nov2013/sll-find.ss
$EX paper/bt-count-1.ss
$EX paper/bt-left2.ss
$EX paper/bt-search-2.ss
$EX paper/bt-trav.ss
$EX paper/bug-imm-set-tail-2.ss
$EX paper/check-cdll5clls.ss
$EX paper/check-cdllcllsx2.ss
$EX paper/check-cdll.ss
$EX paper/check-cllclls.ss
$EX paper/check-cll.ss
$EX paper/check-dll-1.ss
$EX paper/check-dll-2a.ss
$EX paper/check-dll-2b.ss
$EX paper/check-dll-2.ss
$EX paper/check-dll.ss
$EX paper/check-mcf-2a.ss
$EX paper/check-mcf-2.ss
$EX paper/check-mcf-4.ss
$EX paper/check-mcf.ss
$EX paper/check-multi-tree.ss
$EX paper/check-pos.ss
$EX paper/check-sll-head.ss
$EX paper/check-sll-head-v.ss
$EX paper/check-sll-tail.ss
$EX paper/check-sorted-2.ss
$EX paper/check-sorted.ss
$EX paper/check-tll-2.ss
$EX paper/check-tll.ss
$EX paper/check-zip-eq.ss
$EX paper/check-zip-leq.ss
$EX paper/cll.ss
$EX paper/dll-append_paper.ss
$EX paper/last-2.ss
$EX paper/ll-delete.ss
$EX paper/qsort-2.ss
$EX paper/rose-sll-1.ss
$EX paper/set-tail-2.ss
$EX paper/single_paper.ss
$EX paper/skip0b.ss
$EX paper/skip0.ss
$EX paper/skip0-tree.ss
$EX paper/skip1.ss
$EX paper/skip-list-1-1.ss
$EX paper/skip-list.ss
$EX paper/sll-01-slls.ss
$EX paper/sll-append_paper.ss
$EX paper/sll-append.ss
$EX paper/sll-bubble.ss
$EX paper/sll-creat.ss
$EX paper/sll-delete-all.ss
$EX paper/sll-delete-if.ss
$EX paper/sll-dll.ss
$EX paper/sll-get-next-next.ss
$EX paper/sll-get-next.ss
$EX paper/sll-insertsort.ss
$EX paper/sll-insert.ss
$EX paper/sll-last-2.ss
$EX paper/sll-reverse.ss
$EX paper/tll.ss
$EX paper/tree-2.ss
$EX paper/tree.ss
$EX paper-v/bt-count-1-v.ss
$EX paper-v/bt-left2-v.ss
$EX paper-v/bt-search-2-v.ss
$EX paper-v/bt-trav-v.ss
$EX paper-v/check-cdll-v.ss
$EX paper-v/check-cll-v.ss
$EX paper-v/check-dll-1-v.ss
$EX paper-v/check-dll-2a-v.ss
$EX paper-v/check-dll-2b-v.ss
$EX paper-v/check-dll-v.ss
$EX paper-v/check-mcf-2-v.ss
$EX paper-v/check-mcf-4-v.ss
$EX paper-v/check-mcf-v.ss
$EX paper-v/check-multi-tree-v.ss
$EX paper-v/check-pos-v.ss
$EX paper-v/check-sll-head-v.ss
$EX paper-v/check-sorted-2-v.ss
$EX paper-v/check-sorted-v.ss
$EX paper-v/check-tll-2-v.ss
$EX paper-v/check-tll-v.ss
$EX paper-v/check-zip-eq-v.ss
$EX paper-v/check-zip-leq-v.ss
$EX paper-v/cll-v.ss
$EX paper-v/dll-append_paper-v.ss
$EX paper-v/last-2-v.ss
$EX paper-v/qsort-2-v.ss
$EX paper-v/rose-sll-1-v.ss
$EX paper-v/set-tail-2-v.ss
$EX paper-v/single_paper-v.ss
$EX paper-v/skip0b-v.ss
$EX paper-v/skip0-v.ss
$EX paper-v/skip1-v.ss
$EX paper-v/skip-list-1-1-v.ss
$EX paper-v/skip-list-v.ss
$EX paper-v/sll-01-slls-v.ss
$EX paper-v/sll-append_paper-v.ss
$EX paper-v/sll-append-v.ss
$EX paper-v/sll-bubble.ss
$EX paper-v/sll-creat-v.ss
$EX paper-v/sll-delete-all-v.ss
$EX paper-v/sll-delete-if-v.ss
$EX paper-v/sll-dll-v.ss
$EX paper-v/sll-get-next-next-v.ss
$EX paper-v/sll-get-next-v.ss
$EX paper-v/sll-insertsort-v.ss
$EX paper-v/sll-insert-v.ss
$EX paper-v/sll-last-2-v.ss
$EX paper-v/sll-reverse-v.ss
$EX paper-v/tll-v.ss
$EX paper-v/tree-v.ss
$EX paper-v/zip_paper_eq-v.ss
$EX paper-v/zip_paper_leq-v.ss
$EX paper/zip_paper_eq.ss
$EX paper/zip_paper_leq.ss
$EX rel/imm1.ss
$EX rel/insertion_sa.ss
$EX validate/bt-search-2.ss
$EX validate/check-cdllcllsplus2.ss
$EX validate/check-cdllclls.ss
$EX validate/check-cdllcllsx2.ss
$EX validate/check-cdll.ss
$EX validate/check-cll.ss
$EX validate/check-dll.ss
$EX validate/check-mcf.ss
$EX validate/check-sll-head.ss
$EX validate/check-sorted.ss
$EX validate/check-tll-1.ss
$EX validate/cll.ss
$EX validate/cyc-lseg.ss
$EX validate/cyc-tree-1.ss
$EX validate/dll-append_paper.ss
$EX validate/ll-back.ss
$EX validate/ll-delete.ss
$EX validate/ll-parent.ss
$EX validate/ll-trav-1.ss
$EX validate/ll-trav-eq.ss
$EX validate/ll-trav.ss
$EX validate/rose-sll-1.ss
$EX validate/skip0.ss
$EX validate/skip2-list.ss
$EX validate/skip3-list.ss
$EX validate/skip-list.ss
$EX validate/sll-01-slls.ss
$EX validate/sll-dll.ss
$EX validate/sll-insertsort.ss
$EX validate/sll-reverse.ss
$EX validate/tll-parent.ss
$EX validate/tll.ss
$EX validate/tree-parent-2.ss
$EX validate/tree-parent.ss
$EX validate/zip_paper_eq.ss
$EX validate/zip-split.ss
