EX="./slk_test_ex.sh ../sleek"
$EX bugs/app1.slk
$EX bugs/app2.slk
$EX bugs/app.slk
$EX bugs/bug-app1a.slk
$EX bugs/bug-app1b1.slk
$EX bugs/bug-app1b.slk
$EX bugs/bug-app1.slk
$EX bugs/bug-app2.slk
$EX bugs/bug-app3a.slk
$EX bugs/bug-app3b.slk
$EX bugs/bug-app3n.slk
$EX bugs/bug-app3s1.slk
$EX bugs/bug-app3.slk
$EX bugs/bug-app3s.slk
$EX bugs/bug-imm.slk
$EX bugs/bug-t2.slk
$EX bugs/bug-t3a.slk
$EX bugs/bug-t3.slk
$EX bugs/cll-imm.slk
$EX bugs/contra1.slk
$EX bugs/contra2a.slk
$EX bugs/contra2b.slk
$EX bugs/contra2c.slk
$EX bugs/contra2d.slk
$EX bugs/contra2e.slk
$EX bugs/contra2.slk
$EX bugs/dll-3a.slk
$EX bugs/dll-3b1.slk
$EX bugs/dll-3b2.slk
$EX bugs/dll-3b.slk
$EX bugs/dll-3.slk
$EX bugs/dll-4a1.slk
$EX bugs/dll-4a2.slk
$EX bugs/dll-4a.slk
$EX bugs/dll-4b.slk
$EX bugs/dll-4.slk
$EX bugs/funny.slk
$EX bugs/i13a.slk
$EX bugs/i8-1.slk
$EX bugs/i-app1.slk
$EX bugs/i-app2.slk
$EX bugs/i-app3a.slk
$EX bugs/i-app3.slk
$EX bugs/i-app-r1.slk
$EX bugs/i-app-r2.slk
$EX bugs/i-app-r.slk
$EX bugs/i-app.slk
$EX bugs/i-app-w.slk
$EX bugs/i-cll2.slk
$EX bugs/i-cll.slk
$EX bugs/infer13a.slk
$EX bugs/infer13b.slk
$EX bugs/infer13c.slk
$EX bugs/infer13d.slk
$EX bugs/infer13.slk
$EX bugs/infer1.slk
$EX bugs/infer8a.slk
$EX bugs/infer8b.slk
$EX bugs/infer8.slk
$EX bugs/ll-size1.slk
$EX bugs/ll-size2.slk
$EX bugs/ll-size3.slk
$EX bugs/ll-size4.slk
$EX bugs/ll-size.slk
$EX bugs/lp1b.slk
$EX bugs/lp1.slk
$EX bugs/lseg-1.slk
$EX bugs/lsg1a1.slk
$EX bugs/lsg1a.slk
$EX bugs/lsg1b.slk
$EX bugs/lsg1c.slk
$EX bugs/lsg1.slk
$EX bugs/lsg2.slk
$EX bugs/lsg3a.slk
$EX bugs/lsg3b.slk
$EX bugs/lsg3c.slk
$EX bugs/lsg3d.slk
$EX bugs/lsg3.slk
$EX bugs/lsgB.slk
$EX bugs/lsg.slk
$EX bugs/ltail.slk
$EX bugs/mcf-type-bug-1.slk
$EX bugs/mut-1.slk
$EX bugs/norm-1.slk
$EX bugs/pure-1.slk
$EX bugs/set-tail.slk
$EX bugs/sll-1.slk
$EX bugs/sll-3a.slk
$EX bugs/sll-3b.slk
$EX bugs/sll-3.slk
$EX bugs/sll-dll2a1.slk
$EX bugs/sll-dll2a.slk
$EX bugs/sll-dll2b.slk
$EX bugs/sll-dll2-i.slk
$EX bugs/sll-dll2.slk
$EX bugs/sll-dll3.slk
$EX bugs/t1.slk
$EX bugs/t2.slk
$EX bugs/tail-2.slk
$EX bugs/tail.slk
$EX bugs/use1.slk
$EX bugs/use2.slk
$EX bugs/use3.slk
$EX bugs/x.slk
$EX checkeq/heap1.slk
$EX checkeq/ll-traverse.slk
$EX checkeq/pure1.slk
$EX checkeq/pure2.slk
$EX checkeq/pure3.slk
$EX checkeq/pure4.slk
$EX checkeq/pure5.slk
$EX checkeq/pure6.slk
$EX checkeq/test1.slk
$EX checkeq/test2a.slk
$EX checkeq/test2b.slk
$EX checkeq/test2c.slk
$EX checkeq/test2.slk
$EX checkeq/test3.slk
$EX checkeq/test4.slk
$EX checkeq/test5.slk
$EX checkeq/test6.slk
$EX checkeq/test7.slk
$EX checkeq/test8.slk
$EX demo/andr.slk
$EX demo/app5-bug-1.slk
$EX demo/app.slk
$EX demo/assert-1-bug1.slk
$EX demo/assert-1-bug3.slk
$EX demo/assert-1-bug4.slk
$EX demo/assert-1-bug-5.slk
$EX demo/assert-1-bug.slk
$EX demo/assert-2-bug-1.slk
$EX demo/assert-2-bug.slk
$EX demo/bug-classic.slk
$EX demo/bug-swl-0a.slk
$EX demo/bug-swl-0b.slk
$EX demo/bug-swl-1a.slk
$EX demo/bug-swl-1.slk
$EX demo/bug-swl-2.slk
$EX demo/bug-swl-3.slk
$EX demo/class-1a.slk
$EX demo/class-1b.slk
$EX demo/class-1c.slk
$EX demo/class-1d.slk
$EX demo/class-1.slk
$EX demo/class-2.slk
$EX demo/class-dll-app.slk
$EX demo/cll-1a.slk
$EX demo/cll-1b.slk
$EX demo/cll-1c.slk
$EX demo/cll-1.slk
$EX demo/conseq1.slk
$EX demo/cyc-lseg.slk
$EX demo/div-swl-i3.slk
$EX demo/dll-1.slk
$EX demo/dll-2.slk
$EX demo/dll-app3a1.slk
$EX demo/dll-app3a.slk
$EX demo/dll-app-bug1a.slk
$EX demo/dll-app-bug1b.slk
$EX demo/dll-app-bug1c.slk
$EX demo/dll-app-bug1d1.slk
$EX demo/dll-app-bug1d2.slk
$EX demo/dll-app-bug1d3.slk
$EX demo/dll-app-bug1d.slk
$EX demo/dll-app-bug1.slk
$EX demo/dll-app-bug2.slk
$EX demo/dll-app-bug.slk
$EX demo/dll-append2.slk
$EX demo/dll-mw-1.slk
$EX demo/dll-pap-1.slk
$EX demo/dll-pap-2.slk
$EX demo/du-1.slk
$EX demo/du-2.slk
$EX demo/foo.slk
$EX demo/heap-bug-1.slk
$EX demo/heap-bug-2.slk
$EX demo/heap-bug-3a.slk
$EX demo/heap-bug-3b.slk
$EX demo/heap-bug-3.slk
$EX demo/heap-bug-4.slk
$EX demo/h-sorted-2.slk
$EX demo/id.slk
$EX demo/l-1.slk
$EX demo/last-1.slk
$EX demo/last-2a.slk
$EX demo/last-2b.slk
$EX demo/last-2.slk
$EX demo/ll-b-4a.slk
$EX demo/ll-back1.slk
$EX demo/ll-back2.slk
$EX demo/ll-back4.slk
$EX demo/ll-back5.slk
$EX demo/ll-back.slk
$EX demo/ll-parent.slk
$EX demo/loop1.slk
$EX demo/loop-3a.slk
$EX demo/loop-3b1.slk
$EX demo/loop-3b2.slk
$EX demo/loop-3b3.slk
$EX demo/loop-3b4.slk
$EX demo/loop-3b.slk
$EX demo/loop-3c1.slk
$EX demo/loop-3c.slk
$EX demo/loop-3d1a.slk
$EX demo/loop-3d1.slk
$EX demo/loop-3d.slk
$EX demo/loop-3.slk
$EX demo/loop.slk
$EX demo/lseg-3a.slk
$EX demo/mcf-1a.slk
$EX demo/mcf-1b.slk
$EX demo/mcf-1.slk
$EX demo/mcf-2.slk
$EX demo/mcf-3a1.slk
$EX demo/mcf-3a.slk
$EX demo/mcf-3b.slk
$EX demo/mcf-3.slk
$EX demo/mcf-4a.slk
$EX demo/mcf-4.slk
$EX demo/mt-1.slk
$EX demo/mt-2.slk
$EX demo/mt-3.slk
$EX demo/multi-tree-1.slk
$EX demo/multi-tree-2a.slk
$EX demo/multi-tree-2b.slk
$EX demo/multi-tree-2.slk
$EX demo/multi-tree-3.slk
$EX demo/ni.slk
$EX demo/null.slk
$EX demo/pair2-bug1.slk
$EX demo/pair2-bug2.slk
$EX demo/pair-bug2a.slk
$EX demo/pair-bug2.slk
$EX demo/pos-1a.slk
$EX demo/pos-1b.slk
$EX demo/pos-1c.slk
$EX demo/pos-1.slk
$EX demo/post-1a.slk
$EX demo/post-1b.slk
$EX demo/post-1c.slk
$EX demo/post-1d.slk
$EX demo/post-1.slk
$EX demo/post-2a.slk
$EX demo/post-2.slk
$EX demo/post-3.slk
$EX demo/post-4.slk
$EX demo/post-5.slk
$EX demo/pre-1.slk
$EX demo/pre-2a.slk
$EX demo/pre-2.slk
$EX demo/pre-3.slk
$EX demo/rose-1.slk
$EX demo/single-a1.slk
$EX demo/single-a.slk
$EX demo/single-b1.slk
$EX demo/single-b.slk
$EX demo/single-bug-1.slk
$EX demo/single-bug-2.slk
$EX demo/single-bug-3.slk
$EX demo/single-bug-4.slk
$EX demo/single-bug-5.slk
$EX demo/single.slk
$EX demo/skip0-bug-1.slk
$EX demo/skip0-bug-2.slk
$EX demo/sll-bug-1.slk
$EX demo/sll-dll-2-bug-1.slk
$EX demo/sll-dll-2.slk
$EX demo/sll-dll-bug1.slk
$EX demo/sll-dll-bug2.slk
$EX demo/sll-dll-bug3.slk
$EX demo/sll-dll.slk
$EX demo/sll-rev-3.slk
$EX demo/sorted-2a.slk
$EX demo/sorted-2b.slk
$EX demo/sorted-2c.slk
$EX demo/sorted-2.slk
$EX demo/sorted-3.slk
$EX demo/sorted-4a.slk
$EX demo/sorted-4b.slk
$EX demo/sorted-4c.slk
$EX demo/sorted-4.slk
$EX demo/srev-3a.slk
$EX demo/st-bug-1.slk
$EX demo/st-bug-2.slk
$EX demo/swl-i1a.slk
$EX demo/swl-i1.slk
$EX demo/swl-i2a.slk
$EX demo/swl-i2b0.slk
$EX demo/swl-i2b1.slk
$EX demo/swl-i2b2.slk
$EX demo/swl-i2b.slk
$EX demo/swl-i2-old.slk
$EX demo/swl-i2.slk
$EX demo/swl-i3a1.slk
$EX demo/swl-i3a.slk
$EX demo/swl-i3b.slk
$EX demo/swl-i3c1.slk
$EX demo/swl-i3c.slk
$EX demo/swl-i3-old.slk
$EX demo/swl-i3.slk
$EX demo/swl-i6.slk
$EX demo/swl-i-ob1.slk
$EX demo/swl-t1.slk
$EX demo/swl-t2.slk
$EX demo/swl-t3a.slk
$EX demo/swl-t3.slk
$EX demo/tail-bug-1.slk
$EX demo/t-field-1.slk
$EX demo/tll-1a.slk
$EX demo/tll-1.slk
$EX demo/tll-bug-1.slk
$EX demo/tll-bug-2.slk
$EX demo/tll-if1.slk
$EX demo/tll-if2.slk
$EX demo/tll-if3.slk
$EX demo/tll-if-conquer-pre.slk
$EX demo/tll-if-conquer.slk
$EX demo/tll-if-divide-all.slk
$EX demo/tll-if-divide-pre-1.slk
$EX demo/tll-if-divide-pre.slk
$EX demo/tll-if-divide.slk
$EX demo/tll-if.slk
$EX demo/tree-1-bug-1a.slk
$EX demo/tree-1-bug-1.slk
$EX demo/tree-1.slk
$EX demo/tree-2-bug-1.slk
$EX demo/tree-2-bug-2.slk
$EX demo/tree-3.slk
$EX demo/tree-4a.slk
$EX demo/tree-4b.slk
$EX demo/tree-4c.slk
$EX demo/tree-4d.slk
$EX demo/tree-4e.slk
$EX demo/tree-4f.slk
$EX demo/tree-4.slk
$EX demo/tree-5a.slk
$EX demo/tree-5.slk
$EX demo/tree-6a.slk
$EX demo/tree-6b.slk
$EX demo/tree-6c1.slk
$EX demo/tree-6c2.slk
$EX demo/tree-6c3.slk
$EX demo/tree-6c4.slk
$EX demo/tree-6c5.slk
$EX demo/tree-6c6.slk
$EX demo/tree-6c7.slk
$EX demo/tree-6c8.slk
$EX demo/tree-6c.slk
$EX demo/tree-6.slk
$EX demo/tree-bug-1.slk
$EX demo/tree-bug1.slk
$EX demo/tree-bug-2.slk
$EX demo/tree-conj-bug-1a.slk
$EX demo/tree-conj-bug-1b.slk
$EX demo/tree-conj-bug-1.slk
$EX demo/tree-conj-bug-2.slk
$EX demo/tree.slk
$EX demo/t.slk
$EX demo/two-1a.slk
$EX demo/two-1.slk
$EX demo/two-2a.slk
$EX demo/two-2.slk
$EX demo/two-bug-1.slk
$EX demo/two.slk
$EX demo/view-1.slk
$EX demo/view-2a.slk
$EX demo/view-2b.slk
$EX demo/view-2c.slk
$EX demo/view-2.slk
$EX demo/view-3.slk
$EX demo/view-4.slk
$EX demo/view_simp.slk
$EX demo/xisa-bug-1.slk
$EX demo/xisa-bug-2.slk
$EX demo/xisa-bug-3.slk
$EX demo/zip1b1.slk
$EX demo/zip1b2.slk
$EX demo/zip1b3.slk
$EX demo/zip1b4.slk
$EX demo/zip1b5.slk
$EX demo/zip1b.slk
$EX demo/zip1c1.slk
$EX demo/zip1c2.slk
$EX demo/zip1c.slk
$EX demo/zip1d.slk
$EX demo/zip1e.slk
$EX demo/zip1f.slk
$EX demo/zip1.slk
$EX demo/zip1z.slk
$EX demo/zip-bug1a.slk
$EX demo/zip-bug1b.slk
$EX demo/zip-bug1c.slk
$EX demo/zip-bug1.slk
$EX demo/zip-bug2.slk
$EX demo/zip-bug3.slk
$EX demo/zip-bug4.slk
$EX demo/zip-bug5a.slk
$EX demo/zip-bug5b.slk
$EX demo/zip-bug5c.slk
$EX demo/zip-bug5.slk
$EX demo/zip-dnc.slk
$EX demo/zip.slk
$EX demo/zip-sp.slk
$EX derive/der-1a.slk
$EX derive/der-1b.slk
$EX derive/der-1c.slk
$EX derive/der-1.slk
$EX derive/der-2a.slk
$EX derive/der-2b.slk
$EX derive/der-2c.slk
$EX derive/der-2d.slk
$EX derive/der-2.slk
$EX derive/der-3.slk
$EX derive/der-4.slk
$EX derive/der-5.slk
$EX derive/der-6a.slk
$EX derive/der-6b.slk
$EX derive/der-6c.slk
$EX derive/der-6d.slk
$EX derive/der-6.slk
$EX derive/der-7.slk
$EX derive/derive-pred-simp.slk
$EX derive/derive-pred.slk
$EX derive/err-1-der-5.slk
$EX derive/err-2-der-2.slk
$EX derive/err-print-tw.slk
$EX derive/spec-1a.slk
$EX derive/spec-1.slk
$EX errors/ex1.slk
$EX errors/ex2a1.slk
$EX errors/ex2a.slk
$EX errors/ex2.slk
$EX errors/ex3.slk
$EX errors/v-next3.slk
$EX errors/v-next6.slk
$EX errors/v-next7b.slk
$EX errors/v-next7c.slk
$EX errors/v-next7d2.slk
$EX errors/v-next7d.slk
$EX errors/v-next7e.slk
$EX errors/v-next7.slk
$EX errors/v-next.slk
$EX hip2/cll-d1a.slk
$EX hip2/cll-d1.slk
$EX hip2/cll-d2a.slk
$EX hip2/cll-d2b.slk
$EX hip2/cll-d2.slk
$EX hip2/cll-d3a1.slk
$EX hip2/cll-d3a2.slk
$EX hip2/cll-d3a.slk
$EX hip2/cll-d3b.slk
$EX hip2/cll-d3.slk
$EX hip2/cll-d4.slk
$EX hip2/cll-del.slk
$EX hip2/cll-d.slk
$EX hip2/cll-imm.slk
$EX hip2/cll-type.slk
$EX hip2/foo.slk
$EX hip2/ll-d1a.slk
$EX hip2/ll-d1b.slk
$EX hip2/ll-d1.slk
$EX hip2/ll-d2.slk
$EX hip2/ll-d3.slk
$EX hip2/ll-del1a.slk
$EX hip2/ll-del1b1.slk
$EX hip2/ll-del1b2.slk
$EX hip2/ll-del1b3.slk
$EX hip2/ll-del1b.slk
$EX hip2/ll-del1c.slk
$EX hip2/ll-del-1.slk
$EX hip2/ll-del1.slk
$EX hip2/ll-del2.slk
$EX hip2/ll-del.slk
$EX hip2/ll-getnext2-1.slk
$EX hip2/ll-getnext2a1.slk
$EX hip2/ll-getnext2a2.slk
$EX hip2/ll-getnext2a3.slk
$EX hip2/ll-getnext2a.slk
$EX hip2/ll-getnext2c.slk
$EX hip2/ll-getnext2.slk
$EX hip2/ll-getnext-a.slk
$EX hip2/ll-getnext.slk
$EX hip2/loc-1a.slk
$EX hip2/loc-1b1.slk
$EX hip2/loc-1b2.slk
$EX hip2/loc-1b3.slk
$EX hip2/loc-1b.slk
$EX hip2/loc-1c2.slk
$EX hip2/loc-1c.slk
$EX hip2/loc-1d.slk
$EX hip2/loc-1e.slk
$EX hip2/loc-1.slk
$EX hip2/loc-2a.slk
$EX hip2/loc-2.slk
$EX hip2/loc-3a.slk
$EX hip2/loc-4a1.slk
$EX hip2/loc-4a2.slk
$EX hip2/loc-4a3.slk
$EX hip2/loc-4a.slk
$EX hip2/loc.slk
$EX hip2/pre-1.slk
$EX hip2/pre-2a.slk
$EX hip2/pre-2b.slk
$EX hip2/pre-2c1.slk
$EX hip2/pre-2c.slk
$EX hip2/pre-2d.slk
$EX hip2/pre-2e.slk
$EX hip2/pre-2f.slk
$EX hip2/pre-2.slk
$EX hip2/sante-1.slk
$EX hip2/sb-1.slk
$EX hip2/sb-2.slk
$EX hip2/sb-3.slk
$EX hip2/sb-4a.slk
$EX hip2/sb-4.slk
$EX hip2/s_conseq-1.slk
$EX hip2/sconseq-1.slk
$EX hip2/test.slk
$EX hip/app4-1.slk
$EX hip/app4.slk
$EX hip/aux_1.slk
$EX hip/get-next.slk
$EX hip/ll-append9-1.slk
$EX hip/ll-app.slk
$EX hip/ll-get-next.slk
$EX hip/ll-traverse.slk
$EX hip/sleek_test.slk
$EX hip/t.slk
$EX lemma/bt-left.slk
$EX lemma/eq-view-1.slk
$EX lemma/ll-insert-last.slk
$EX lemma/sem-mat.slk
$EX lemma/subsume-lem.slk
$EX norm/bug-classic-4a.slk
$EX norm/classic-bug-1a.slk
$EX norm/classic-bug-1b.slk
$EX norm/eq-1.slk
$EX norm/eq-2.slk
$EX norm/eq-3.slk
$EX norm/eq-4.slk
$EX norm/fix-2a.slk
$EX norm/fix-2b.slk
$EX norm/fix-2.slk
$EX norm/fix-3.slk
$EX norm/ll-app-1.slk
$EX norm/ll.slk
$EX norm/ls3.slk
$EX norm/ls-lem-1a1.slk
$EX norm/ls-lem-1a2b.slk
$EX norm/ls-lem-1a2c2.slk
$EX norm/ls-lem-1a2c.slk
$EX norm/ls-lem-1a2.slk
$EX norm/ls-lem-1a.slk
$EX norm/ls-lem-1.slk
$EX norm/ls-lem-2.slk
$EX norm/ls.slk
$EX norm/null.slk
$EX norm/rlseg.slk
$EX norm/sp-11.slk
$EX norm/sp-1a.slk
$EX norm/sp-1.slk
$EX norm/sp-2a.slk
$EX norm/sp-2b.slk
$EX norm/sp-2c.slk
$EX norm/sp-2d1.slk
$EX norm/sp-2d.slk
$EX norm/sp-2f.slk
$EX norm/sp-2.slk
$EX norm/sp-3a.slk
$EX norm/sp-3.slk
$EX norm/sp-4a1.slk
$EX norm/sp-4a2.slk
$EX norm/sp-4a.slk
$EX norm/sp-4.slk
$EX norm/sp-5a.slk
$EX norm/sp-5.slk
$EX norm/sp-6.slk
$EX norm/sp-7a.slk
$EX norm/sp-7b1.slk
$EX norm/sp-7b2.slk
$EX norm/sp-7c.slk
$EX norm/sp-7d.slk
$EX norm/sp-7e1.slk
$EX norm/sp-7e.slk
$EX norm/sp-7.slk
$EX norm/split-1a.slk
$EX norm/split-1b.slk
$EX norm/split-1c.slk
$EX norm/split-1d.slk
$EX norm/split-1e.slk
$EX norm/split-1.slk
$EX norm/split1.slk
$EX norm/split-2.slk
$EX norm/split-seg.slk
$EX norm/split.slk
$EX norm/udisj-1.slk
$EX norm/zip-1a.slk
$EX norm/zip-1b.slk
$EX norm/zip-1c.slk
$EX norm/zip-1d.slk
$EX norm/zip-1e2.slk
$EX norm/zip-1e3.slk
$EX norm/zip-1e3v1.slk
$EX norm/zip-1e3v.slk
$EX norm/zip-1e6.slk
$EX norm/zip-1e-fix1.slk
$EX norm/zip-1e-fix2.slk
$EX norm/zip-1e.slk
$EX norm/zip-1.slk
$EX norm/zip-2a.slk
$EX norm/zip-2b1.slk
$EX norm/zip-2b.slk
$EX norm/zip-2c.slk
$EX norm/zip-2.slk
$EX norm/zip-3a.slk
$EX norm/zip-3.slk
$EX norm/zip-fix-eq-1.slk
$EX norm/zip-fix-eq-2.slk
$EX norm/zp-1a1.slk
$EX norm/zp-1a2.slk
$EX norm/zp-1a.slk
$EX norm/zp-1b.slk
$EX norm/zp-1c.slk
$EX norm/zp-1.slk
$EX nov2013/ll-last.slk
$EX paper/c-cll.slk
$EX paper/cm2a.slk
$EX paper/last-obl2.slk
$EX paper/last-obl3.slk
$EX paper/last-obl.slk
$EX paper/tll-guard.slk
$EX sleek/ex1a.slk
$EX sleek/ex1.slk
$EX sleek/ex2.slk
$EX sleek/ex3.slk
$EX sleek/ex4.slk
$EX sleek/ll-append.slk
$EX sleek/test1.slk
$EX validate/ll-parent-1.slk
$EX validate/ll-parent-2.slk
$EX validate/ll-parent.slk
$EX validate/tree-parent.slk
