EX="./slk_override_one.sh"
$EX demo/zip.slk
$EX demo/zip-sp.slk
$EX derive/der-1a.slk
$EX derive/der-1b.slk
$EX derive/der-1c.slk
$EX derive/der-1.slk
$EX derive/der-2a.slk
$EX derive/der-2b.slk
$EX derive/der-2c.slk
$EX derive/der-2d.slk
$EX derive/der-2.slk
$EX derive/der-3.slk
$EX derive/der-4.slk
$EX derive/der-5.slk
$EX derive/der-6a.slk
$EX derive/der-6b.slk
$EX derive/der-6c.slk
$EX derive/der-6d.slk
$EX derive/der-6.slk
$EX derive/der-7.slk
$EX derive/derive-pred-simp.slk
$EX derive/derive-pred.slk
$EX derive/err-1-der-5.slk
$EX derive/err-2-der-2.slk
$EX derive/err-print-tw.slk
$EX derive/spec-1a.slk
$EX derive/spec-1.slk
$EX errors/ex1.slk
$EX errors/ex2a1.slk
$EX errors/ex2a.slk
$EX errors/ex2.slk
$EX errors/ex3.slk
$EX errors/v-next3.slk
$EX errors/v-next6.slk
$EX errors/v-next7b.slk
$EX errors/v-next7c.slk
$EX errors/v-next7d2.slk
$EX errors/v-next7d.slk
$EX errors/v-next7e.slk
$EX errors/v-next7.slk
$EX errors/v-next.slk
$EX hip2/cll-d1a.slk
$EX hip2/cll-d1.slk
$EX hip2/cll-d2a.slk
$EX hip2/cll-d2b.slk
$EX hip2/cll-d2.slk
$EX hip2/cll-d3a1.slk
$EX hip2/cll-d3a2.slk
$EX hip2/cll-d3a.slk
$EX hip2/cll-d3b.slk
$EX hip2/cll-d3.slk
$EX hip2/cll-d4.slk
$EX hip2/cll-del.slk
$EX hip2/cll-d.slk
$EX hip2/cll-imm.slk
$EX hip2/cll-type.slk
$EX hip2/foo.slk
$EX hip2/ll-d1a.slk
$EX hip2/ll-d1b.slk
$EX hip2/ll-d1.slk
$EX hip2/ll-d2.slk
$EX hip2/ll-d3.slk
$EX hip2/ll-del1a.slk
$EX hip2/ll-del1b1.slk
$EX hip2/ll-del1b2.slk
$EX hip2/ll-del1b3.slk
$EX hip2/ll-del1b.slk
$EX hip2/ll-del1c.slk
$EX hip2/ll-del-1.slk
$EX hip2/ll-del1.slk
$EX hip2/ll-del2.slk
$EX hip2/ll-del.slk
$EX hip2/ll-getnext2-1.slk
$EX hip2/ll-getnext2a1.slk
$EX hip2/ll-getnext2a2.slk
$EX hip2/ll-getnext2a3.slk
$EX hip2/ll-getnext2a.slk
$EX hip2/ll-getnext2c.slk
$EX hip2/ll-getnext2.slk
$EX hip2/ll-getnext-a.slk
$EX hip2/ll-getnext.slk
$EX hip2/loc-1a.slk
$EX hip2/loc-1b1.slk
$EX hip2/loc-1b2.slk
$EX hip2/loc-1b3.slk
$EX hip2/loc-1b.slk
$EX hip2/loc-1c2.slk
$EX hip2/loc-1c.slk
$EX hip2/loc-1d.slk
$EX hip2/loc-1e.slk
$EX hip2/loc-1.slk
$EX hip2/loc-2a.slk
$EX hip2/loc-2.slk
$EX hip2/loc-3a.slk
$EX hip2/loc-4a1.slk
$EX hip2/loc-4a2.slk
$EX hip2/loc-4a3.slk
$EX hip2/loc-4a.slk
$EX hip2/loc.slk
$EX hip2/pre-1.slk
$EX hip2/pre-2a.slk
$EX hip2/pre-2b.slk
$EX hip2/pre-2c1.slk
$EX hip2/pre-2c.slk
$EX hip2/pre-2d.slk
$EX hip2/pre-2e.slk
$EX hip2/pre-2f.slk
$EX hip2/pre-2.slk
$EX hip2/sante-1.slk
$EX hip2/sb-1.slk
$EX hip2/sb-2.slk
$EX hip2/sb-3.slk
$EX hip2/sb-4a.slk
$EX hip2/sb-4.slk
$EX hip2/s_conseq-1.slk
$EX hip2/sconseq-1.slk
$EX hip2/test.slk
$EX hip/app4-1.slk
$EX hip/app4.slk
$EX hip/aux_1.slk
$EX hip/get-next.slk
$EX hip/ll-append9-1.slk
$EX hip/ll-app.slk
$EX hip/ll-get-next.slk
$EX hip/ll-traverse.slk
$EX hip/sleek_test.slk
$EX hip/t.slk
$EX lemma/bt-left.slk
$EX lemma/eq-view-1.slk
$EX lemma/ll-insert-last.slk
$EX lemma/sem-mat.slk
$EX lemma/subsume-lem.slk
$EX norm/bug-classic-4a.slk
$EX norm/classic-bug-1a.slk
$EX norm/classic-bug-1b.slk
$EX norm/eq-1.slk
$EX norm/eq-2.slk
$EX norm/eq-3.slk
$EX norm/eq-4.slk
$EX norm/fix-2a.slk
$EX norm/fix-2b.slk
$EX norm/fix-2.slk
$EX norm/fix-3.slk
$EX norm/ll-app-1.slk
$EX norm/ll.slk
$EX norm/ls3.slk
$EX norm/ls-lem-1a1.slk
$EX norm/ls-lem-1a2b.slk
$EX norm/ls-lem-1a2c2.slk
$EX norm/ls-lem-1a2c.slk
$EX norm/ls-lem-1a2.slk
$EX norm/ls-lem-1a.slk
$EX norm/ls-lem-1.slk
$EX norm/ls-lem-2.slk
$EX norm/ls.slk
$EX norm/null.slk
$EX norm/rlseg.slk
$EX norm/sp-11.slk
$EX norm/sp-1a.slk
$EX norm/sp-1.slk
$EX norm/sp-2a.slk
$EX norm/sp-2b.slk
$EX norm/sp-2c.slk
$EX norm/sp-2d1.slk
$EX norm/sp-2d.slk
$EX norm/sp-2f.slk
$EX norm/sp-2.slk
$EX norm/sp-3a.slk
$EX norm/sp-3.slk
$EX norm/sp-4a1.slk
$EX norm/sp-4a2.slk
$EX norm/sp-4a.slk
$EX norm/sp-4.slk
$EX norm/sp-5a.slk
$EX norm/sp-5.slk
$EX norm/sp-6.slk
$EX norm/sp-7a.slk
$EX norm/sp-7b1.slk
$EX norm/sp-7b2.slk
$EX norm/sp-7c.slk
$EX norm/sp-7d.slk
$EX norm/sp-7e1.slk
$EX norm/sp-7e.slk
$EX norm/sp-7.slk
$EX norm/split-1a.slk
$EX norm/split-1b.slk
$EX norm/split-1c.slk
$EX norm/split-1d.slk
$EX norm/split-1e.slk
$EX norm/split-1.slk
$EX norm/split1.slk
$EX norm/split-2.slk
$EX norm/split-seg.slk
$EX norm/split.slk
$EX norm/udisj-1.slk
$EX norm/zip-1a.slk
$EX norm/zip-1b.slk
$EX norm/zip-1c.slk
$EX norm/zip-1d.slk
$EX norm/zip-1e2.slk
$EX norm/zip-1e3.slk
$EX norm/zip-1e3v1.slk
$EX norm/zip-1e3v.slk
$EX norm/zip-1e6.slk
$EX norm/zip-1e-fix1.slk
$EX norm/zip-1e-fix2.slk
$EX norm/zip-1e.slk
$EX norm/zip-1.slk
$EX norm/zip-2a.slk
$EX norm/zip-2b1.slk
$EX norm/zip-2b.slk
$EX norm/zip-2c.slk
$EX norm/zip-2.slk
$EX norm/zip-3a.slk
$EX norm/zip-3.slk
$EX norm/zip-fix-eq-1.slk
$EX norm/zip-fix-eq-2.slk
$EX norm/zp-1a1.slk
$EX norm/zp-1a2.slk
$EX norm/zp-1a.slk
$EX norm/zp-1b.slk
$EX norm/zp-1c.slk
$EX norm/zp-1.slk
$EX nov2013/ll-last.slk
$EX paper/c-cll.slk
$EX paper/cm2a.slk
$EX paper/last-obl2.slk
$EX paper/last-obl3.slk
$EX paper/last-obl.slk
$EX paper/tll-guard.slk
$EX sleek/ex1a.slk
$EX sleek/ex1.slk
$EX sleek/ex2.slk
$EX sleek/ex3.slk
$EX sleek/ex4.slk
$EX sleek/ll-append.slk
$EX sleek/test1.slk
$EX validate/ll-parent-1.slk
$EX validate/ll-parent-2.slk
$EX validate/ll-parent.slk
$EX validate/tree-parent.slk
