EX="./test_ex.sh ../hip"
$EX data/ll1 
$EX data/ll2a
$EX data/ll2 
$EX data/ll3
$EX data/ll4
$EX data/ll
$EX examples/base-1
$EX examples/base-2
$EX examples/base-3a
$EX examples/base-3b
$EX examples/base-3c
$EX examples/base-3d
$EX examples/base-4a
$EX examples/base-4b
$EX examples/base-4c
$EX examples/bool-1
$EX examples/bool-2
$EX examples/f91-rec
$EX examples/f91
$EX examples/fact-2
$EX examples/fact-case2a
$EX examples/fact-case2
$EX examples/fact-case3
$EX examples/fact-case4
$EX examples/fact-case5
$EX examples/fact-case
$EX examples/fact-c
$EX examples/fact
$EX examples/foo-fact1
$EX examples/foo-fact2
$EX examples/foo-fact3
$EX examples/loop-1
$EX examples/loop-2a
$EX examples/loop-2
$EX examples/loop-3a
$EX examples/loop-3
$EX examples/loop-4a
$EX examples/loop-4b
$EX examples/loop-4
$EX examples/mayloop-1
$EX examples/mayloop-2
$EX examples/mult-1a
$EX examples/mult-1b
$EX examples/mult-1c
$EX examples/mult-2a
$EX examples/mult-2b
$EX examples/mutual-1
$EX examples/mutual-2
$EX examples/mutual-3
$EX examples/mutual-4a
$EX examples/mutual-4
$EX examples/mutual-5a
$EX examples/mutual-5b1
$EX examples/mutual-5b2
$EX examples/mutual-5b3
$EX examples/mutual-5b
$EX examples/mutual-5c
$EX examples/mutual-5d
$EX examples/mutual-5e
$EX examples/mutual-5f
$EX examples/mutual-5
$EX examples/mutual-6
$EX examples/mutual-7
$EX examples/num-1
$EX examples/num-2a
$EX examples/num-2
$EX examples/reach-1
$EX examples/reach-2
$EX examples/rec-f91a
$EX examples/rec-f91b1
$EX examples/rec-f91b2
$EX examples/rec-f91b3
$EX examples/rec-f91b
$EX examples/rec-f91c
$EX examples/rec-f91d
$EX examples/rec-f91
$EX examples/rec-fgen0
$EX examples/rec-fgen1
$EX examples/rec-fgen2
$EX examples/rec-fgen3
$EX examples/rec-fgen
$EX examples/sc-2
$EX examples/sc
$EX hip/bigint-a
$EX hip/bigint-s
$EX hip/bubble-1
$EX hip/bubble-1-up
$EX hip/bubble-c
$EX hip/bubble-c-up-2
$EX hip/bubble-c-up-2-unsound
$EX hip/bubble-c-up-3
$EX hip/bubble-c-up-4
$EX hip/bubble-c-up
$EX hip/bubble-down
$EX hip/bubble-sorted
$EX hip/bubble
$EX hip/double_length-i
$EX hip/double_length
$EX hip/dummy-1
$EX hip/ll-length-nr-2
$EX hip/ll-length-nr
$EX hip/ll-length-n
$EX hip/ll-length-r
$EX hip/ll-sum-r
$EX hip/ll-sum-s2
$EX hip/ll-sum-s3
$EX hip/ll-sum-sr2
$EX hip/ll-sum-sr3
$EX hip/ll-sum-sr
$EX hip/ll-sum-v
$EX hip/s2l2-i
$EX hip/s2l-2
$EX hip/s2l2
$EX hip/s2l2-v2-c
$EX hip/s2l2-v2-e
$EX hip/s2l2-v2-i2
$EX hip/s2l2-v2-i
$EX hip/s2l2-v2-pi2
$EX hip/s2l2-v2-pi
$EX hip/s2l2-v2-ppi
$EX hip/s2l2-v2-p
$EX hip/s2l2-v2
$EX hip/s2l2-v3
$EX hip/s2l-i2-r
$EX hip/s2l-i2
$EX hip/s2l-i3
$EX hip/s2l-i
$EX hip/s2l
$EX hip/s2l-v2-i
$EX hip/s2l-v2
$EX paper/ex-1
$EX paper/ex-2a
$EX paper/ex-2
$EX paper/ex-3a
$EX paper/ex-3
$EX pure/lex-1r
$EX slk/case-1
$EX slk/clist-length
$EX slk/fact2a
$EX slk/fact2b
$EX slk/fact2c1
$EX slk/fact2c1-u
$EX slk/fact2c2
$EX slk/fact2c2-u
$EX slk/fact2c3
$EX slk/fact2c
$EX slk/fact2cv
$EX slk/fact2
$EX slk/fact
$EX slk/invalid-1a
$EX slk/invalid-1b
$EX slk/invalid-1
$EX slk/ll-length-1
$EX slk/ll-length
$EX slk/mult1b1
$EX slk/mult1b2
$EX slk/mult1b3
$EX slk/mult1b
$EX slk/mult1
$EX slk/mult2
$EX slk/mult3a
$EX slk/mult3
$EX slk/mult4-1
$EX slk/mult4-2a
$EX slk/mult4-2
$EX slk/mult4-3a
$EX slk/mult4-3
$EX slk/mult4a
$EX slk/mult4b
$EX slk/mult4
$EX slk/mult-c1
$EX slk/mult-c2
$EX slk/mult
$EX slk/termu-1c2
$EX slk/termu-1c3
$EX slk/termu-1c4
$EX slk/termu-1c
$EX slk/termu-2d
$EX slk/termu-2e
$EX slk/termu-2
$EX slk/termu-5a
$EX slk/termu-5b
$EX slk/termu-5
$EX slk/termu-5s
$EX slk/termu-6
