../../sleek 1.slk > 1.res
../../sleek 2a.slk > 2a.res
../../sleek 2b.slk > 2b.res
../../sleek 2c.slk > 2c.res
../../hip ll-app.ss > ll-app.res
../../hip ll-const.ss > ll-const.res
../../hip ll-len.ss > ll-len.res
../../hip ll-len2.ss > ll-len2.res
../../hip ll-reverse.ss > ll-reverse.res
../../hip ll-rev2.ss > ll-rev2.res
../../hip ll-del.ss > ll-del.res
../../hip num-app.ss > num-app.res
../../hip num-del.ss > num-del.res
../../hip num-del-a.ss > num-del-a.res
../../hip --abdfpost cll-count1.ss > cll-count1.res
../../hip cll-count2.ss > cll-count2.res
../../hip cll-del.ss > cll-del.res
../../hip cll-insert.ss > cll-insert.res
../../hip dll-app.ss > dll-app.res
../../hip dll-del.ss > dll-del.res
../../hip dll-insert.ss > dll-insert.res
../../hip r1-i.ss > r1-i.res
../../hip r2a-i.ss > r2a-i.res
../../hip bug-3c.ss > bug-3c.res
../../hip bug-del2.ss > bug-del2.res
../../hip bug-num-del.ss > bug-num-del.res
../../hip bsort-1.ss > bsort-1.res
../../hip bsort-3.ss > bsort-3.res
../../hip bsort-4.ss > bsort-4.res
../../hip bst-del.ss > bst-del.res
../../hip bst-del-a.ss > bst-del-a.res
../../hip bst-del-b.ss > bst-del-b.res
../../hip bst-del-c.ss > bst-del-c.res
../../hip bst-insert.ss > bst-insert.res
../../hip bst-insert-a.ss > bst-insert-a.res
../../hip bst-insert-b.ss > bst-insert-b.res
#../../hip bst-insert-c.ss > bst-insert-c.res
../../hip bst-remove-min.ss > bst-remove-min.res

