../../sleek 1.slk > 1.n
../../sleek 2a.slk > 2a.n
../../sleek 2b.slk > 2b.n
../../sleek 2c.slk > 2c.n
../../hip ll-app.ss > ll-app.n
../../hip ll-const.ss > ll-const.n
../../hip ll-len.ss > ll-len.n
../../hip ll-len2.ss > ll-len2.n
../../hip ll-reverse.ss > ll-reverse.n
../../hip ll-rev2.ss > ll-rev2.n
../../hip ll-del.ss > ll-del.n
../../hip num-app.ss > num-app.n
../../hip num-del.ss > num-del.n
../../hip num-del-a.ss > num-del-a.n
../../hip cll-count1.ss > cll-count1.n
../../hip cll-count2.ss > cll-count2.n
../../hip cll-del.ss > cll-del.n
../../hip cll-insert.ss > cll-insert.n
../../hip dll-app.ss > dll-app.n
../../hip dll-del.ss > dll-del.n
../../hip dll-insert.ss > dll-insert.n
../../hip r1-i.ss > r1-i.n
../../hip r2a-i.ss > r2a-i.n
../../hip bug-3c.ss > bug-3c.n
../../hip bug-del2.ss > bug-del2.n
../../hip bug-num-del.ss > bug-num-del.n
../../hip bsort-1.ss > bsort-1.n
../../hip bst-del.ss > bst-del.n
../../hip bst-insert.ss > bst-insert.n
../../hip bst-remove-min.ss > bst-remove-min.n
