../../sleek 1.slk > 1.res
../../sleek 2.slk > 2.res
../../sleek 3.slk > 3.res
../../sleek 3a.slk > 3a.res
../../sleek 3b.slk > 3b.res
../../sleek 3c.slk > 3c.res
../../sleek t2.slk > t2.res
../../sleek t3.slk > t3.res
../../sleek frac.slk > frac.res
../../sleek insidious.slk > insidious.res
../../sleek todo.slk > todo.res
