../../sleek 1.slk > 1.n
../../sleek 2.slk > 2.n
../../sleek 3.slk > 3.n
../../sleek 3a.slk > 3a.n
../../sleek 3b.slk > 3b.n
../../sleek 3c.slk > 3c.n
../../sleek t2.slk > t2.n
../../sleek t3.slk > t3.n
../../sleek frac.slk > frac.n
../../sleek insidious.slk > insidious.n
../../sleek todo.slk > todo.n
../../sleek 2a.slk > 2a.n
../../sleek 3f.slk > 3f.n
../../sleek 3g.slk > 3g.n
../../sleek 3h.slk > 3h.n
../../sleek t3a.slk > t3a.n
