
Processing file "append-tail.ss"
Parsing append-tail.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure append$node~node~node~node... 
Procedure append$node~node~node~node SUCCESS
Stop Omega... 826 invocations 
0 false contexts at: ()

Total verification time: 10.548658 second(s)
	Time spent in main process: 8.220513 second(s)
	Time spent in child processes: 2.328145 second(s)
