
Processing file "avl-orig-2.ss"
Parsing avl-orig-2.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure get_max$int~int... 
Procedure get_max$int~int SUCCESS
Checking procedure rotate_left_child$node... 
Procedure rotate_left_child$node SUCCESS
Checking procedure rotate_right_child$node... 
Procedure rotate_right_child$node SUCCESS
Checking procedure double_left_child$node... 
Procedure double_left_child$node SUCCESS
Checking procedure double_right_child$node... 
Procedure double_right_child$node SUCCESS
Checking procedure height$node... 
Procedure height$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Stop Omega... 3325 invocations 
0 false contexts at: ()

Total verification time: 13.95287 second(s)
	Time spent in main process: 8.000499 second(s)
	Time spent in child processes: 5.952371 second(s)
