
Processing file "avl-bind.ss"
Parsing avl-bind.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure build_avl1$node~node... 
Procedure build_avl1$node~node SUCCESS
Checking procedure build_avl2$node~node~node... 
Procedure build_avl2$node~node~node SUCCESS
Checking procedure get_max$int~int... 
Procedure get_max$int~int SUCCESS
Checking procedure height$node... 
Procedure height$node SUCCESS
Checking procedure rotate_double_left$node~node~node~node~int~int~int... 
Procedure rotate_double_left$node~node~node~node~int~int~int SUCCESS
Checking procedure rotate_double_right$node~node~node~node~int~int~int... 
Procedure rotate_double_right$node~node~node~node~int~int~int SUCCESS
Checking procedure rotate_left$node~node~node... 
Procedure rotate_left$node~node~node SUCCESS
Checking procedure rotate_right$node~node~node... 
Procedure rotate_right$node~node~node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Stop Omega... 1749 invocations 
4 false contexts at: ( (215,4)  (210,6)  (192,11)  (187,6) )

Total verification time: 15.932995 second(s)
	Time spent in main process: 6.88843 second(s)
	Time spent in child processes: 9.044565 second(s)
