
Processing file "avl.ss"
Parsing avl.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure build_avl1$node~node... 
Procedure build_avl1$node~node SUCCESS
Checking procedure build_avl2$node~node~node... 
Procedure build_avl2$node~node~node SUCCESS
Checking procedure get_max$int~int... 
Procedure get_max$int~int SUCCESS
Checking procedure height$node... 
Procedure height$node SUCCESS
Checking procedure rotate_double_left$node~node~node~node~int~int~int... 
Procedure rotate_double_left$node~node~node~node~int~int~int SUCCESS
Checking procedure rotate_double_right$node~node~node~node~int~int~int... 
Procedure rotate_double_right$node~node~node~node~int~int~int SUCCESS
Checking procedure rotate_left$node~node~node... 
Procedure rotate_left$node~node~node SUCCESS
Checking procedure rotate_right$node~node~node... 
Procedure rotate_right$node~node~node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure insert_inline$node~int... 
Procedure insert_inline$node~int SUCCESS
Checking procedure merge$node~node... 
Procedure merge$node~node SUCCESS
Stop Omega... 4279 invocations 
20 false contexts at: ( (465,17)  (465,24)  (469,3)  (469,22)  (469,10)  (468,15)  (468,27)  (468,8)  (467,14)  (467,25)  (467,8)  (467,3)  (344,4)  (340,6)  (284,4)  (280,6)  (211,4)  (207,6)  (190,11)  (186,6) )

Total verification time: 31.505968 second(s)
	Time spent in main process: 14.200887 second(s)
	Time spent in child processes: 17.305081 second(s)
