
Processing file "bll.ss"
Parsing bll.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure delete$node... 
Procedure delete$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Stop Omega... 120 invocations 
0 false contexts at: ()

Total verification time: 0.412024 second(s)
	Time spent in main process: 0.204012 second(s)
	Time spent in child processes: 0.208012 second(s)
