
Processing file "bubble.ss"
Parsing bubble.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure bubble$node... 
Procedure bubble$node SUCCESS
Checking procedure bsort$node... 
Procedure bsort$node SUCCESS
Checking procedure id2$node... 
Procedure id2$node SUCCESS
Checking procedure id3$node... 
Procedure id3$node SUCCESS
Stop Omega... 629 invocations 
0 false contexts at: ()

Total verification time: 2.492155 second(s)
	Time spent in main process: 1.628101 second(s)
	Time spent in child processes: 0.864054 second(s)
