
Processing file "cll.ss"
Parsing cll.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure count_rest$node~node... 
Procedure count_rest$node~node SUCCESS
Checking procedure count$node... 
Procedure count$node SUCCESS
Checking procedure delete$node... 
Procedure delete$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure test$... 
Procedure test$ SUCCESS
Stop Omega... 257 invocations 
0 false contexts at: ()

Total verification time: 0.780048 second(s)
	Time spent in main process: 0.372023 second(s)
	Time spent in child processes: 0.408025 second(s)
