
Processing file "global-mutual-rec.ss"
Parsing global-mutual-rec.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure decrease2$int~int~int... 
Procedure decrease2$int~int~int SUCCESS
Checking procedure decrease1$int~int~int... 
Procedure decrease1$int~int~int SUCCESS
Checking procedure main$int~int... 
Procedure main$int~int SUCCESS
Stop Omega... 171 invocations 
2 false contexts at: ( (9,3)  (30,3) )

Total verification time: 0.424025 second(s)
	Time spent in main process: 0.220013 second(s)
	Time spent in child processes: 0.204012 second(s)
