
Processing file "global5.ss"
Parsing global5.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure decrease$int... 
Procedure decrease$int SUCCESS
Checking procedure increase$int~int~int... 
Procedure increase$int~int~int SUCCESS
Stop Omega... 37 invocations 
0 false contexts at: ()

Total verification time: 0.204011 second(s)
	Time spent in main process: 0.120007 second(s)
	Time spent in child processes: 0.084004 second(s)
