
Processing file "global4.ss"
Parsing global4.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure increase_n$int~int... 
Procedure increase_n$int~int SUCCESS
Checking procedure main$int~int... 
Procedure main$int~int SUCCESS
Stop Omega... 37 invocations 
0 false contexts at: ()

Total verification time: 0.204012 second(s)
	Time spent in main process: 0.124007 second(s)
	Time spent in child processes: 0.080005 second(s)
