
Processing file "global2.ss"
Parsing global2.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure increase$int~int... 
Procedure increase$int~int SUCCESS
Stop Omega... 31 invocations 
0 false contexts at: ()

Total verification time: 0.204011 second(s)
	Time spent in main process: 0.128007 second(s)
	Time spent in child processes: 0.076004 second(s)
