
Processing file "global-ll.ss"
Parsing global-ll.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure delete_last_rec$node... 
Procedure delete_last_rec$node SUCCESS
Checking procedure delete_last$node~int... 
Procedure delete_last$node~int SUCCESS
Checking procedure insert_rec$node~int... 
Procedure insert_rec$node~int SUCCESS
Checking procedure insert$int~node~int... 
Procedure insert$int~node~int SUCCESS
Checking procedure main$node~int... 
Procedure main$node~int SUCCESS
Stop Omega... 318 invocations 
0 false contexts at: ()

Total verification time: 0.82005 second(s)
	Time spent in main process: 0.432027 second(s)
	Time spent in child processes: 0.388023 second(s)
