
Processing file "global3.ss"
Parsing global3.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure increase$int~int... 
Procedure increase$int~int SUCCESS
Checking procedure increase_n$int~int... 
Procedure increase_n$int~int SUCCESS
Stop Omega... 39 invocations 
0 false contexts at: ()

Total verification time: 0.208011 second(s)
	Time spent in main process: 0.128007 second(s)
	Time spent in child processes: 0.080004 second(s)
