
Processing file "insertion.ss"
Parsing insertion.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure insertion_sort$node~node... 
Procedure insertion_sort$node~node SUCCESS
Stop Omega... 313 invocations 
0 false contexts at: ()

Total verification time: 0.868053 second(s)
	Time spent in main process: 0.444027 second(s)
	Time spent in child processes: 0.424026 second(s)
