
Processing file "ll.ss"
Parsing ll.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure append$node~node... 
Procedure append$node~node SUCCESS
Checking procedure append2$node~node... 
Procedure append2$node~node SUCCESS
Checking procedure create_list$int... 
Procedure create_list$int SUCCESS
Checking procedure delete$node~int... 
Procedure delete$node~int SUCCESS
Checking procedure get_next$node... 
Procedure get_next$node SUCCESS
Checking procedure get_next_next$node... 
Procedure get_next_next$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure ret_first$node... 
Procedure ret_first$node SUCCESS
Checking procedure reverse$node~node... 
Procedure reverse$node~node SUCCESS
Checking procedure set_next$node~node... 
Procedure set_next$node~node SUCCESS
Checking procedure set_null$node... 
Procedure set_null$node SUCCESS
Checking procedure set_null2$node... 
Procedure set_null2$node SUCCESS
Stop Omega... 450 invocations 
2 false contexts at: ( (90,11)  (90,2) )

Total verification time: 1.276078 second(s)
	Time spent in main process: 0.612038 second(s)
	Time spent in child processes: 0.66404 second(s)
