
Processing file "merge.ss"
Parsing merge.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure count$node... 
Procedure count$node SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure merge$node~node... 
assert:merge.ss:104: 4:  : ok


Procedure merge$node~node SUCCESS
Checking procedure split_func$node~int... 
Procedure split_func$node~int SUCCESS
Checking procedure merge_sort$node... 
Procedure merge_sort$node SUCCESS
Stop Omega... 541 invocations 
4 false contexts at: ( (96,3)  (96,10)  (92,2)  (92,9) )

Total verification time: 1.540096 second(s)
	Time spent in main process: 0.772048 second(s)
	Time spent in child processes: 0.768048 second(s)
