
Processing file "perfect.ss"
Parsing perfect.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure create$int... 
Procedure create$int SUCCESS
Checking procedure maxim$int~int... 
Procedure maxim$int~int SUCCESS
Checking procedure height$node2... 
Procedure height$node2 SUCCESS
Checking procedure simple_insert$node2~int... 
Procedure simple_insert$node2~int SUCCESS
Checking procedure insert$node2~int... 
Procedure insert$node2~int SUCCESS
Stop Omega... 345 invocations 
0 false contexts at: ()

Total verification time: 0.944057 second(s)
	Time spent in main process: 0.484029 second(s)
	Time spent in child processes: 0.460028 second(s)
