
Processing file "selection.ss"
Parsing selection.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure delete_min$node~int... 
Procedure delete_min$node~int SUCCESS
Checking procedure find_min$node... 
Procedure find_min$node SUCCESS
Checking procedure selection_sort$node... 
Procedure selection_sort$node SUCCESS
Stop Omega... 357 invocations 
9 false contexts at: ( (31,3)  (31,10)  (29,3)  (29,10)  (28,12)  (28,6)  (27,8)  (27,17)  (27,2) )

Total verification time: 0.828049 second(s)
	Time spent in main process: 0.456027 second(s)
	Time spent in child processes: 0.372022 second(s)
