
Processing file "sll.ss"
Parsing sll.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure delete$node~int... 
Procedure delete$node~int SUCCESS
Checking procedure get_tail$node... 
Procedure get_tail$node SUCCESS
Checking procedure id$int... 
Procedure id$int SUCCESS
Checking procedure insert$node~int... 
Procedure insert$node~int SUCCESS
Checking procedure insert2$node~node... 
Procedure insert2$node~node SUCCESS
Checking procedure insertion_sort$node~node... 
Procedure insertion_sort$node~node SUCCESS
Stop Omega... 558 invocations 
0 false contexts at: ()

Total verification time: 1.348083 second(s)
	Time spent in main process: 0.716044 second(s)
	Time spent in child processes: 0.632039 second(s)
