
Processing file "trees.ss"
Parsing trees.ss ...
Parsing /home2/loris/hg/sl_infer/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure append$node2~node2... 
Procedure append$node2~node2 SUCCESS
Checking procedure count$node2... 
Procedure count$node2 SUCCESS
Checking procedure remove_min$node2... 
Procedure remove_min$node2 SUCCESS
Checking procedure delete$node2~int... 
assert:trees.ss:276: 20:  : ok


Procedure delete$node2~int SUCCESS
Checking procedure flatten$node2... 
Procedure flatten$node2 SUCCESS
Checking procedure insert$node2~int... 
Procedure insert$node2~int SUCCESS
Stop Omega... 868 invocations 
0 false contexts at: ()

Total verification time: 2.60016 second(s)
	Time spent in main process: 1.272078 second(s)
	Time spent in child processes: 1.328082 second(s)
