EX="./slk_diff_one.sh"
$EX field/field1.slk
$EX field/field2.slk
$EX field/field3.slk
$EX field/field.slk
$EX flow/flow1.slk
$EX flow/flow2.slk
$EX flow/flow3a.slk
$EX flow/flow3.slk
$EX flow/flow4.slk
$EX flow/flow5r.slk
$EX flow/flow5.slk
$EX t/exc6e.slk
$EX t/len1.slk
$EX t/loop2a.slk
$EX t/loop2b.slk
$EX t/loop2.slk
$EX t/pre-1a.slk
$EX t/pre-1.slk
$EX t/sexc1a.slk
$EX t/sexc1b.slk
$EX t/sexc1.slk
$EX t/sexc2.slk
$EX t/sexc3i.slk
$EX t/sexc3.slk
$EX t/slk-exc3a.slk
$EX t/slk-exc3.slk
$EX t/str1.slk
$EX t/str.slk
$EX t/termu-6.slk