
Processing file "t1.ss"
Parsing t1.ss ...
Parsing /home/thaitm/hg-repository/new/sleekex/prelude.ss ...
Starting Reduce... 
Starting Omega...oc
Translating global variables to procedure parameters...
Checking procedure foo1$int... 
Procedure foo1$int SUCCESS
Checking procedure foo2$int... 
Procedure foo2$int SUCCESS
Stop Omega... 39 invocations 
0 false contexts at: ()

Total verification time: 0.09 second(s)
	Time spent in main process: 0.07 second(s)
	Time spent in child processes: 0.02 second(s)
