../../hip t1-i.ss > t1-i.res
../../hip t2-i.ss > t2-i.res
../../hip t3-i.ss > t3-i.res
../../hip t4-i.ss > t4-i.res
../../hip t5-i.ss > t5-i.res
../../hip t6-i.ss > t6-i.res
../../hip t8-i.ss > t8-i.res
../../hip t1.ss > t1.res
../../hip todo.ss > todo.res
../../hip bug1.ss > bug1.res
../../hip bug2.ss > bug2.res
../../hip bugt5.ss > bugt5.res
../../hip ll-a2.ss > ll-a2.res
../../hip ll-b.ss > ll-b.res
../../hip ll-c.ss > ll-c.res
