echo "ll-append3.ss"
../../hip ll-append3.ss
echo "ll-append4.ss"
../../hip ll-append4.ss
echo "ll-append5.ss"
../../hip ll-append5.ss
echo "ll-append6.ss"
../../hip ll-append6.ss
echo "ll-append7.ss"
../../hip ll-append7.ss
echo "ll-append8.ss"
../../hip ll-append8.ss
echo "ll-append9.ss"
../../hip ll-append9.ss
echo "ll-append10.ss"
../../hip ll-append10.ss
echo "ll-app3.ss"
../../hip ll-app3.ss
echo "ex1.ss"
../../hip ex1.ss
echo "ex1a.ss"
../../hip ex1a.ss
echo "ll-get-next"
../../hip ll-get-next.ss
echo "ll-get-next-next"
../../hip ll-get-next-next.ss
echo "ll-next2"
../../hip ll-next2.ss
echo "ll-next3"
../../hip ll-next3.ss
echo "ll-next4"
../../hip ll-next4.ss
echo "ll-next5"
../../hip ll-next5.ss
echo "ll-next6"
../../hip ll-next6.ss
echo "ll-delete"
../../hip ll-delete.ss
echo "ll-delete2"
../../hip ll-delete2.ss
echo "ll-get_size"
../../hip ll-get-size.ss
echo "ll_all1"
../../hip ll_all1.ss
echo "ll_all3"
../../hip ll_all3.ss
echo "ll_all4"
../../hip ll_all4.ss
echo "ll_all5"
../../hip ll_all5.ss
echo "ll_all7"
../../hip ll_all7.ss
echo "ll_all8"
../../hip ll_all8.ss
echo "ll_all10"
../../hip ll_all10.ss
echo "ll_all_13"
../../hip ll_all_13.ss
echo "ll_all_13a"
../../hip ll_all_13a.ss
echo "ll_all_13b"
../../hip ll_all_13b.ss
echo "ll_all_13c"
../../hip ll_all_13c.ss
echo "ll_all_13c1"
../../hip ll_all_13c1.ss
echo "ll_all_13e"
../../hip ll_all_13e.ss
echo "ll_all_14"
../../hip ll_all_14.ss
echo "ll-ret-first"
../../hip ll-ret-first.ss
echo "ll-ret-first1"
../../hip ll-ret-first1.ss
echo "ll-ret-first2"
../../hip ll-ret-first2.ss
