(* auto-generated by gt *)

let parsed =
  let file_name = Sys.argv.(1) in
  (* let _ = print_endline file_name in *)
  let in_channel = open_in file_name in
  let lexbuf = Lexing.from_channel in_channel in
  Smtlib_parse.main Smtlib_lex.token lexbuf;;
match parsed with
    None -> ()
  | Some(x) -> Smtlib_translate.trans x;;

print_string "\n";;
