(* auto-generated by gt *)

open Smtlib_syntax;;

let rec dummy () = () 
and eq_an_option = function 
   |AnOptionAttribute (_ , attribute1_1),AnOptionAttribute (_ , attribute1_2)-> true && eq_attribute(attribute1_1 , attribute1_2)
and eq_attribute = function 
   |AttributeKeyword (_ , str1_1),AttributeKeyword (_ , str1_2)-> true && str1_1 = str1_2
   |AttributeKeywordValue (_ , str1_1 , attributevalue2_1),AttributeKeywordValue (_ , str1_2 , attributevalue2_2)-> true && str1_1 = str1_2 && eq_attributevalue(attributevalue2_1 , attributevalue2_2)
   | _ -> false

and eq_attributevalue = function 
   |AttributeValSpecConst (_ , specconstant1_1),AttributeValSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |AttributeValSymbol (_ , symbol1_1),AttributeValSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |AttributeValSexpr (_ , attributevalsexpr_attributevalue_sexpr52_1),AttributeValSexpr (_ , attributevalsexpr_attributevalue_sexpr52_2)-> true && eq_attributevalsexpr_attributevalue_sexpr5(attributevalsexpr_attributevalue_sexpr52_1 , attributevalsexpr_attributevalue_sexpr52_2)
   |AttributeValSexpr1 (_ , attributevalsexpr1_attributevalue_sexpr72_1),AttributeValSexpr1 (_ , attributevalsexpr1_attributevalue_sexpr72_2)-> true && eq_attributevalsexpr1_attributevalue_sexpr7(attributevalsexpr1_attributevalue_sexpr72_1 , attributevalsexpr1_attributevalue_sexpr72_2)
   | _ -> false

and eq_command = function 
   |CommandSetLogic (_ , symbol3_1),CommandSetLogic (_ , symbol3_2)-> true && eq_symbol(symbol3_1 , symbol3_2)
   |CommandSetOption (_ , an_option3_1),CommandSetOption (_ , an_option3_2)-> true && eq_an_option(an_option3_1 , an_option3_2)
   |CommandSetInfo (_ , attribute3_1),CommandSetInfo (_ , attribute3_2)-> true && eq_attribute(attribute3_1 , attribute3_2)
   |CommandDeclareSort (_ , symbol3_1 , str4_1),CommandDeclareSort (_ , symbol3_2 , str4_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && str4_1 = str4_2
   |CommandDefineSort (_ , symbol3_1 , commanddefinesort_command_symbol135_1 , sort7_1),CommandDefineSort (_ , symbol3_2 , commanddefinesort_command_symbol135_2 , sort7_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddefinesort_command_symbol13(commanddefinesort_command_symbol135_1 , commanddefinesort_command_symbol135_2) && eq_sort(sort7_1 , sort7_2)
   |CommandDeclareFun (_ , symbol3_1 , commanddeclarefun_command_sort155_1 , sort7_1),CommandDeclareFun (_ , symbol3_2 , commanddeclarefun_command_sort155_2 , sort7_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddeclarefun_command_sort15(commanddeclarefun_command_sort155_1 , commanddeclarefun_command_sort155_2) && eq_sort(sort7_1 , sort7_2)
   |CommandDefineFun (_ , symbol3_1 , commanddefinefun_command_sortedvar175_1 , sort7_1 , term8_1),CommandDefineFun (_ , symbol3_2 , commanddefinefun_command_sortedvar175_2 , sort7_2 , term8_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_commanddefinefun_command_sortedvar17(commanddefinefun_command_sortedvar175_1 , commanddefinefun_command_sortedvar175_2) && eq_sort(sort7_1 , sort7_2) && eq_term(term8_1 , term8_2)
   |CommandPush (_ , str3_1),CommandPush (_ , str3_2)-> true && str3_1 = str3_2
   |CommandPop (_ , str3_1),CommandPop (_ , str3_2)-> true && str3_1 = str3_2
   |CommandAssert (_ , term3_1),CommandAssert (_ , term3_2)-> true && eq_term(term3_1 , term3_2)
   |CommandCheckSat (_),CommandCheckSat (_)-> true
   |CommandGetAssert (_),CommandGetAssert (_)-> true
   |CommandGetProof (_),CommandGetProof (_)-> true
   |CommandGetUnsatCore (_),CommandGetUnsatCore (_)-> true
   |CommandGetValue (_ , commandgetvalue_command_term264_1),CommandGetValue (_ , commandgetvalue_command_term264_2)-> true && eq_commandgetvalue_command_term26(commandgetvalue_command_term264_1 , commandgetvalue_command_term264_2)
   |CommandGetAssign (_),CommandGetAssign (_)-> true
   |CommandGetOption (_ , str3_1),CommandGetOption (_ , str3_2)-> true && str3_1 = str3_2
   |CommandGetInfo (_ , infoflag3_1),CommandGetInfo (_ , infoflag3_2)-> true && eq_infoflag(infoflag3_1 , infoflag3_2)
   |CommandExit (_),CommandExit (_)-> true
   | _ -> false

and eq_commands = function 
   |Commands (_ , commands_commands_command321_1),Commands (_ , commands_commands_command321_2)-> true && eq_commands_commands_command32(commands_commands_command321_1 , commands_commands_command321_2)
and eq_identifier = function 
   |IdSymbol (_ , symbol1_1),IdSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |IdUnderscoreSymNum (_ , symbol3_1 , idunderscoresymnum_identifier_numeral354_1),IdUnderscoreSymNum (_ , symbol3_2 , idunderscoresymnum_identifier_numeral354_2)-> true && eq_symbol(symbol3_1 , symbol3_2) && eq_idunderscoresymnum_identifier_numeral35(idunderscoresymnum_identifier_numeral354_1 , idunderscoresymnum_identifier_numeral354_2)
   | _ -> false

and eq_infoflag = function 
   |InfoFlagKeyword (_ , str1_1),InfoFlagKeyword (_ , str1_2)-> true && str1_1 = str1_2
and eq_qualidentifier = function 
   |QualIdentifierId (_ , identifier1_1),QualIdentifierId (_ , identifier1_2)-> true && eq_identifier(identifier1_1 , identifier1_2)
   |QualIdentifierAs (_ , identifier3_1 , sort4_1),QualIdentifierAs (_ , identifier3_2 , sort4_2)-> true && eq_identifier(identifier3_1 , identifier3_2) && eq_sort(sort4_1 , sort4_2)
   | _ -> false

and eq_sexpr = function 
   |SexprSpecConst (_ , specconstant1_1),SexprSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |SexprSymbol (_ , symbol1_1),SexprSymbol (_ , symbol1_2)-> true && eq_symbol(symbol1_1 , symbol1_2)
   |SexprKeyword (_ , str1_1),SexprKeyword (_ , str1_2)-> true && str1_1 = str1_2
   |SexprInParen (_ , sexprinparen_sexpr_sexpr432_1),SexprInParen (_ , sexprinparen_sexpr_sexpr432_2)-> true && eq_sexprinparen_sexpr_sexpr43(sexprinparen_sexpr_sexpr432_1 , sexprinparen_sexpr_sexpr432_2)
   | _ -> false

and eq_sort = function 
   |SortIdentifier (_ , identifier1_1),SortIdentifier (_ , identifier1_2)-> true && eq_identifier(identifier1_1 , identifier1_2)
   |SortIdSortMulti (_ , identifier2_1 , sortidsortmulti_sort_sort463_1),SortIdSortMulti (_ , identifier2_2 , sortidsortmulti_sort_sort463_2)-> true && eq_identifier(identifier2_1 , identifier2_2) && eq_sortidsortmulti_sort_sort46(sortidsortmulti_sort_sort463_1 , sortidsortmulti_sort_sort463_2)
   | _ -> false

and eq_sortedvar = function 
   |SortedVarSymSort (_ , symbol2_1 , sort3_1),SortedVarSymSort (_ , symbol2_2 , sort3_2)-> true && eq_symbol(symbol2_1 , symbol2_2) && eq_sort(sort3_1 , sort3_2)
and eq_specconstant = function 
   |SpecConstsDec (_ , str1_1),SpecConstsDec (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstNum (_ , str1_1),SpecConstNum (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstString (_ , str1_1),SpecConstString (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstsHex (_ , str1_1),SpecConstsHex (_ , str1_2)-> true && str1_1 = str1_2
   |SpecConstsBinary (_ , str1_1),SpecConstsBinary (_ , str1_2)-> true && str1_1 = str1_2
   | _ -> false

and eq_symbol = function 
   |Symbol (_ , str1_1),Symbol (_ , str1_2)-> true && str1_1 = str1_2
   |SymbolWithOr (_ , str1_1),SymbolWithOr (_ , str1_2)-> true && str1_1 = str1_2
   | _ -> false

and eq_term = function 
   |TermSpecConst (_ , specconstant1_1),TermSpecConst (_ , specconstant1_2)-> true && eq_specconstant(specconstant1_1 , specconstant1_2)
   |TermQualIdentifier (_ , qualidentifier1_1),TermQualIdentifier (_ , qualidentifier1_2)-> true && eq_qualidentifier(qualidentifier1_1 , qualidentifier1_2)
   |TermQualIdTerm (_ , qualidentifier2_1 , termqualidterm_term_term583_1),TermQualIdTerm (_ , qualidentifier2_2 , termqualidterm_term_term583_2)-> true && eq_qualidentifier(qualidentifier2_1 , qualidentifier2_2) && eq_termqualidterm_term_term58(termqualidterm_term_term583_1 , termqualidterm_term_term583_2)
   |TermLetTerm (_ , termletterm_term_varbinding604_1 , term6_1),TermLetTerm (_ , termletterm_term_varbinding604_2 , term6_2)-> true && eq_termletterm_term_varbinding60(termletterm_term_varbinding604_1 , termletterm_term_varbinding604_2) && eq_term(term6_1 , term6_2)
   |TermForAllTerm (_ , termforallterm_term_sortedvar624_1 , term6_1),TermForAllTerm (_ , termforallterm_term_sortedvar624_2 , term6_2)-> true && eq_termforallterm_term_sortedvar62(termforallterm_term_sortedvar624_1 , termforallterm_term_sortedvar624_2) && eq_term(term6_1 , term6_2)
   |TermExistsTerm (_ , termexiststerm_term_sortedvar644_1 , term6_1),TermExistsTerm (_ , termexiststerm_term_sortedvar644_2 , term6_2)-> true && eq_termexiststerm_term_sortedvar64(termexiststerm_term_sortedvar644_1 , termexiststerm_term_sortedvar644_2) && eq_term(term6_1 , term6_2)
   |TermExclimationPt (_ , term3_1 , termexclimationpt_term_attribute664_1),TermExclimationPt (_ , term3_2 , termexclimationpt_term_attribute664_2)-> true && eq_term(term3_1 , term3_2) && eq_termexclimationpt_term_attribute66(termexclimationpt_term_attribute664_1 , termexclimationpt_term_attribute664_2)
   | _ -> false

and eq_varbinding = function 
   |VarBindingSymTerm (_ , symbol2_1 , term3_1),VarBindingSymTerm (_ , symbol2_2 , term3_2)-> true && eq_symbol(symbol2_1 , symbol2_2) && eq_term(term3_1 , term3_2)
and eq_termexclimationpt_term_attribute66 = function 
   |(_,[]),(_,[])-> true
   | (d , (attribute1_1)::termexclimationpt_term_attribute662_1), (d' , (attribute1_2)::termexclimationpt_term_attribute662_2)-> true && eq_attribute(attribute1_1 , attribute1_2) && eq_termexclimationpt_term_attribute66((d,termexclimationpt_term_attribute662_1) , (d',termexclimationpt_term_attribute662_2))
   | _ -> false

and eq_termexiststerm_term_sortedvar64 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::termexiststerm_term_sortedvar642_1), (d' , (sortedvar1_2)::termexiststerm_term_sortedvar642_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_termexiststerm_term_sortedvar64((d,termexiststerm_term_sortedvar642_1) , (d',termexiststerm_term_sortedvar642_2))
   | _ -> false

and eq_termforallterm_term_sortedvar62 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::termforallterm_term_sortedvar622_1), (d' , (sortedvar1_2)::termforallterm_term_sortedvar622_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_termforallterm_term_sortedvar62((d,termforallterm_term_sortedvar622_1) , (d',termforallterm_term_sortedvar622_2))
   | _ -> false

and eq_termletterm_term_varbinding60 = function 
   |(_,[]),(_,[])-> true
   | (d , (varbinding1_1)::termletterm_term_varbinding602_1), (d' , (varbinding1_2)::termletterm_term_varbinding602_2)-> true && eq_varbinding(varbinding1_1 , varbinding1_2) && eq_termletterm_term_varbinding60((d,termletterm_term_varbinding602_1) , (d',termletterm_term_varbinding602_2))
   | _ -> false

and eq_termqualidterm_term_term58 = function 
   |(_,[]),(_,[])-> true
   | (d , (term1_1)::termqualidterm_term_term582_1), (d' , (term1_2)::termqualidterm_term_term582_2)-> true && eq_term(term1_1 , term1_2) && eq_termqualidterm_term_term58((d,termqualidterm_term_term582_1) , (d',termqualidterm_term_term582_2))
   | _ -> false

and eq_sortidsortmulti_sort_sort46 = function 
   |(_,[]),(_,[])-> true
   | (d , (sort1_1)::sortidsortmulti_sort_sort462_1), (d' , (sort1_2)::sortidsortmulti_sort_sort462_2)-> true && eq_sort(sort1_1 , sort1_2) && eq_sortidsortmulti_sort_sort46((d,sortidsortmulti_sort_sort462_1) , (d',sortidsortmulti_sort_sort462_2))
   | _ -> false

and eq_sexprinparen_sexpr_sexpr43 = function 
   |(_,[]),(_,[])-> true
   | (d , (sexpr1_1)::sexprinparen_sexpr_sexpr432_1), (d' , (sexpr1_2)::sexprinparen_sexpr_sexpr432_2)-> true && eq_sexpr(sexpr1_1 , sexpr1_2) && eq_sexprinparen_sexpr_sexpr43((d,sexprinparen_sexpr_sexpr432_1) , (d',sexprinparen_sexpr_sexpr432_2))
   | _ -> false

and eq_idunderscoresymnum_identifier_numeral35 = function 
   |(_,[]),(_,[])-> true
   | (d , (str1_1)::idunderscoresymnum_identifier_numeral352_1), (d' , (str1_2)::idunderscoresymnum_identifier_numeral352_2)-> true && str1_1 = str1_2 && eq_idunderscoresymnum_identifier_numeral35((d,idunderscoresymnum_identifier_numeral352_1) , (d',idunderscoresymnum_identifier_numeral352_2))
   | _ -> false

and eq_commands_commands_command32 = function 
   |(_,[]),(_,[])-> true
   | (d , (command1_1)::commands_commands_command322_1), (d' , (command1_2)::commands_commands_command322_2)-> true && eq_command(command1_1 , command1_2) && eq_commands_commands_command32((d,commands_commands_command322_1) , (d',commands_commands_command322_2))
   | _ -> false

and eq_commandgetvalue_command_term26 = function 
   |(_,[]),(_,[])-> true
   | (d , (term1_1)::commandgetvalue_command_term262_1), (d' , (term1_2)::commandgetvalue_command_term262_2)-> true && eq_term(term1_1 , term1_2) && eq_commandgetvalue_command_term26((d,commandgetvalue_command_term262_1) , (d',commandgetvalue_command_term262_2))
   | _ -> false

and eq_commanddefinefun_command_sortedvar17 = function 
   |(_,[]),(_,[])-> true
   | (d , (sortedvar1_1)::commanddefinefun_command_sortedvar172_1), (d' , (sortedvar1_2)::commanddefinefun_command_sortedvar172_2)-> true && eq_sortedvar(sortedvar1_1 , sortedvar1_2) && eq_commanddefinefun_command_sortedvar17((d,commanddefinefun_command_sortedvar172_1) , (d',commanddefinefun_command_sortedvar172_2))
   | _ -> false

and eq_commanddeclarefun_command_sort15 = function 
   |(_,[]),(_,[])-> true
   | (d , (sort1_1)::commanddeclarefun_command_sort152_1), (d' , (sort1_2)::commanddeclarefun_command_sort152_2)-> true && eq_sort(sort1_1 , sort1_2) && eq_commanddeclarefun_command_sort15((d,commanddeclarefun_command_sort152_1) , (d',commanddeclarefun_command_sort152_2))
   | _ -> false

and eq_commanddefinesort_command_symbol13 = function 
   |(_,[]),(_,[])-> true
   | (d , (symbol1_1)::commanddefinesort_command_symbol132_1), (d' , (symbol1_2)::commanddefinesort_command_symbol132_2)-> true && eq_symbol(symbol1_1 , symbol1_2) && eq_commanddefinesort_command_symbol13((d,commanddefinesort_command_symbol132_1) , (d',commanddefinesort_command_symbol132_2))
   | _ -> false

and eq_attributevalsexpr1_attributevalue_sexpr7 = function 
   |(_,[]),(_,[])-> true
   | (d , (sexpr1_1)::attributevalsexpr1_attributevalue_sexpr72_1), (d' , (sexpr1_2)::attributevalsexpr1_attributevalue_sexpr72_2)-> true && eq_sexpr(sexpr1_1 , sexpr1_2) && eq_attributevalsexpr1_attributevalue_sexpr7((d,attributevalsexpr1_attributevalue_sexpr72_1) , (d',attributevalsexpr1_attributevalue_sexpr72_2))
   | _ -> false

and eq_attributevalsexpr_attributevalue_sexpr5 = function 
   |(_,[]),(_,[])-> true
   | (d , (sexpr1_1)::attributevalsexpr_attributevalue_sexpr52_1), (d' , (sexpr1_2)::attributevalsexpr_attributevalue_sexpr52_2)-> true && eq_sexpr(sexpr1_1 , sexpr1_2) && eq_attributevalsexpr_attributevalue_sexpr5((d,attributevalsexpr_attributevalue_sexpr52_1) , (d',attributevalsexpr_attributevalue_sexpr52_2))
   | _ -> false
;;
let eq e = eq_commands e;;