#!/bin/bash
set -ev
yes "" | opam init --compiler=4.07.0
eval $(opam env)
sudo mkdir -p /usr/local/etc
sudo cp -r dependencies/mona_1.4-18 /usr/local
sudo cp -r dependencies/reduce /usr/local/etc
ln -s /usr/local/mona_1.4-18/bin/mona dependencies/mona
OPAMYES=true rake dependencies:install
rake
sudo cpanm File::NCopy Spreadsheet::WriteExcel Spreadsheet::ParseExcel
