function two
{
diff tests/slk/$1.out ref/slk/$1.out -b  > _XYZ
if [ -s _XYZ ]
then
echo =============
echo "tmp_cp $1  "
echo =============
cat _XYZ
fi
}
two app5-bug-1.slk
two app.slk
two assert-1-bug1.slk
two assert-1-bug3.slk
two assert-1-bug4.slk
two assert-1-bug-5.slk
two assert-1-bug.slk
two assert-2-bug-1.slk
two assert-2-bug.slk
two class-1a.slk
two class-1b.slk
two class-1c.slk
two class-1d.slk
two class-1.slk
two class-2.slk
two class-dll-app.slk
two cll-1a.slk
two cll-1b.slk
two cll-1c.slk
two cll-1.slk
two conseq1.slk
two dll-app3a1.slk
two dll-app3a.slk
two dll-app-bug1a.slk
two dll-app-bug1b.slk
two dll-app-bug1c.slk
two dll-app-bug1d1.slk
two dll-app-bug1d2.slk
two dll-app-bug1d3.slk
two dll-app-bug1d.slk
two dll-app-bug1.slk
two dll-app-bug2.slk
two dll-app-bug.slk
two dll-append2.slk
two dll-pap-1.slk
two dll-pap-2.slk
two du-1.slk
two du-2.slk
two foo.slk
two heap-bug-1.slk
two heap-bug-2.slk
two heap-bug-3a.slk
two heap-bug-3b.slk
two heap-bug-3.slk
two heap-bug-4.slk
two id.slk
two last-1.slk
two last-2a.slk
two last-2b.slk
two last-2.slk
two loop1.slk
two loop.slk
two null.slk
two pair2-bug1.slk
two pair2-bug2.slk
two pair-bug2a.slk
two pair-bug2.slk
two post-1a.slk
two post-1b.slk
two post-1c.slk
two post-1d.slk
two post-1.slk
two post-2a.slk
two post-2.slk
two post-3.slk
two post-4.slk
two post-5.slk
two pre-1.slk
two pre-2a.slk
two pre-2.slk
two pre-3.slk
two single-a1.slk
two single-a.slk
two single-b1.slk
two single-b.slk
two single-bug-1.slk
two single-bug-2.slk
two single-bug-3.slk
two single-bug-4.slk
two single-bug-5.slk
two single.slk
two sll-bug-1.slk
two sll-dll-2-bug-1.slk
two sll-dll-2.slk
two sll-dll-bug1.slk
two sll-dll-bug2.slk
two sll-dll-bug3.slk
two sll-dll.slk
two st-bug-1.slk
two st-bug-2.slk
two tail-bug-1.slk
two tll-1a.slk
two tll-1.slk
two tll-bug-1.slk
two tll-bug-2.slk
two tll-if1.slk
two tll-if2.slk
two tll-if3.slk
two tll-if-conquer-pre.slk
two tll-if-conquer.slk
two tll-if-divide-all.slk
two tll-if-divide-pre.slk
two tll-if-divide.slk
two tll-if.slk
two tree-1-bug-1a.slk
two tree-1-bug-1.slk
two tree-1.slk
two tree-2-bug-1.slk
two tree-2-bug-2.slk
two tree-3.slk
two tree-4a.slk
two tree-4b.slk
two tree-4c.slk
two tree-4d.slk
two tree-4e.slk
two tree-4f.slk
two tree-4.slk
two tree-5a.slk
two tree-5.slk
two tree-6a.slk
two tree-6b.slk
two tree-6c1.slk
two tree-6c2.slk
two tree-6c3.slk
two tree-6c4.slk
two tree-6c5.slk
two tree-6c6.slk
two tree-6c7.slk
two tree-6c8.slk
two tree-6c.slk
two tree-6.slk
two tree-bug-1.slk
two tree-bug1.slk
two tree-bug-2.slk
two tree-conj-bug-1a.slk
two tree-conj-bug-1b.slk
two tree-conj-bug-1.slk
two tree-conj-bug-2.slk
two tree.slk
two two-1a.slk
two two-1.slk
two two-2a.slk
two two-2.slk
two two-bug-1.slk
two two.slk
two zip1b1.slk
two zip1b2.slk
two zip1b3.slk
two zip1b4.slk
two zip1b5.slk
two zip1b.slk
two zip1c1.slk
two zip1c2.slk
two zip1c.slk
two zip1d.slk
two zip1e.slk
two zip1f.slk
two zip1.slk
two zip1z.slk
two zip-bug1a.slk
two zip-bug1b.slk
two zip-bug1c.slk
two zip-bug1.slk
two zip-bug2.slk
two zip-bug3.slk
two zip-bug4.slk
two zip-bug5a.slk
two zip-bug5b.slk
two zip-bug5c.slk
two zip-bug5.slk
two zip.slk


