EX="./test_ex.sh ../../../sleek"
$EX app5-bug-1.slk
$EX app.slk
$EX assert-1-bug1.slk
$EX assert-1-bug3.slk
$EX assert-1-bug4.slk
$EX assert-1-bug-5.slk
$EX assert-1-bug.slk
$EX assert-2-bug-1.slk
$EX assert-2-bug.slk
$EX class-1a.slk
$EX class-1b.slk
$EX class-1c.slk
$EX class-1d.slk
$EX class-1.slk
$EX class-2.slk
$EX class-dll-app.slk
$EX cll-1a.slk
$EX cll-1b.slk
$EX cll-1c.slk
$EX cll-1.slk
$EX conseq1.slk
$EX dll-app3a1.slk
$EX dll-app3a.slk
$EX dll-app-bug1a.slk
$EX dll-app-bug1b.slk
$EX dll-app-bug1c.slk
$EX dll-app-bug1d1.slk
$EX dll-app-bug1d2.slk
$EX dll-app-bug1d3.slk
$EX dll-app-bug1d.slk
$EX dll-app-bug1.slk
$EX dll-app-bug2.slk
$EX dll-app-bug.slk
$EX dll-append2.slk
$EX dll-pap-1.slk
$EX dll-pap-2.slk
$EX du-1.slk
$EX du-2.slk
$EX foo.slk
$EX heap-bug-1.slk
$EX heap-bug-2.slk
$EX heap-bug-3a.slk
$EX heap-bug-3b.slk
$EX heap-bug-3.slk
$EX heap-bug-4.slk
$EX id.slk
$EX last-1.slk
$EX last-2a.slk
$EX last-2b.slk
$EX last-2.slk
$EX loop1.slk
$EX loop.slk
$EX null.slk
$EX pair2-bug1.slk
$EX pair2-bug2.slk
$EX pair-bug2a.slk
$EX pair-bug2.slk
$EX post-1a.slk
$EX post-1b.slk
$EX post-1c.slk
$EX post-1d.slk
$EX post-1.slk
$EX post-2a.slk
$EX post-2.slk
$EX post-3.slk
$EX post-4.slk
$EX post-5.slk
$EX pre-1.slk
$EX pre-2a.slk
$EX pre-2.slk
$EX pre-3.slk
$EX single-a1.slk
$EX single-a.slk
$EX single-b1.slk
$EX single-b.slk
$EX single-bug-1.slk
$EX single-bug-2.slk
$EX single-bug-3.slk
$EX single-bug-4.slk
$EX single-bug-5.slk
$EX single.slk
$EX sll-bug-1.slk
$EX sll-dll-2-bug-1.slk
$EX sll-dll-2.slk
$EX sll-dll-bug1.slk
$EX sll-dll-bug2.slk
$EX sll-dll-bug3.slk
$EX sll-dll.slk
$EX st-bug-1.slk
$EX st-bug-2.slk
$EX tail-bug-1.slk
$EX tll-1a.slk
$EX tll-1.slk
$EX tll-bug-1.slk
$EX tll-bug-2.slk
$EX tll-if1.slk
$EX tll-if2.slk
$EX tll-if3.slk
$EX tll-if-conquer-pre.slk
$EX tll-if-conquer.slk
$EX tll-if-divide-all.slk
$EX tll-if-divide-pre.slk
$EX tll-if-divide.slk
$EX tll-if.slk
$EX tree-1-bug-1a.slk
$EX tree-1-bug-1.slk
$EX tree-1.slk
$EX tree-2-bug-1.slk
$EX tree-2-bug-2.slk
$EX tree-3.slk
$EX tree-4a.slk
$EX tree-4b.slk
$EX tree-4c.slk
$EX tree-4d.slk
$EX tree-4e.slk
$EX tree-4f.slk
$EX tree-4.slk
$EX tree-5a.slk
$EX tree-5.slk
$EX tree-6a.slk
$EX tree-6b.slk
$EX tree-6c1.slk
$EX tree-6c2.slk
$EX tree-6c3.slk
$EX tree-6c4.slk
$EX tree-6c5.slk
$EX tree-6c6.slk
$EX tree-6c7.slk
$EX tree-6c8.slk
$EX tree-6c.slk
$EX tree-6.slk
$EX tree-bug-1.slk
$EX tree-bug1.slk
$EX tree-bug-2.slk
$EX tree-conj-bug-1a.slk
$EX tree-conj-bug-1b.slk
$EX tree-conj-bug-1.slk
$EX tree-conj-bug-2.slk
$EX tree.slk
$EX two-1a.slk
$EX two-1.slk
$EX two-2a.slk
$EX two-2.slk
$EX two-bug-1.slk
$EX two.slk
$EX zip1b1.slk
$EX zip1b2.slk
$EX zip1b3.slk
$EX zip1b4.slk
$EX zip1b5.slk
$EX zip1b.slk
$EX zip1c1.slk
$EX zip1c2.slk
$EX zip1c.slk
$EX zip1d.slk
$EX zip1e.slk
$EX zip1f.slk
$EX zip1.slk
$EX zip1z.slk
$EX zip-bug1a.slk
$EX zip-bug1b.slk
$EX zip-bug1c.slk
$EX zip-bug1.slk
$EX zip-bug2.slk
$EX zip-bug3.slk
$EX zip-bug4.slk
$EX zip-bug5a.slk
$EX zip-bug5b.slk
$EX zip-bug5c.slk
$EX zip-bug5.slk
$EX zip.slk

