EX="./slk_override_one.sh"
$EX t/app1.slk
$EX t/app-inv2.slk
$EX t/app-inv.slk
$EX t/avl.slk
$EX t/baga1.slk
$EX t/baga2.slk
$EX t/baga-test-2.slk
$EX t/baga-test-eps.slk
$EX t/baga-test.slk
$EX t/bug-under1.slk
$EX t/bug-under2.slk
$EX t/cll-d.slk
$EX t/eps-1.slk
$EX t/eps-ll-1.slk
$EX t/err1-1.slk
$EX t/err1-2.slk
$EX t/err1-3.slk
$EX t/err1-4.slk
$EX t/inf2a.slk
$EX t/inf2.slk
$EX t/infer10.slk
$EX t/infer4.slk
$EX t/infer5a.slk
$EX t/infer5.slk
$EX t/infer8.slk
$EX t/infer9.slk
$EX t/infer-ll1a.slk
$EX t/infer-ll1b.slk
$EX t/infer-tree1a.slk
$EX t/infer-under1.slk
$EX t/infer-under2.slk
$EX t/infer-under3.slk
$EX t/infer-under4.slk
$EX t/infer-under5.slk
$EX t/infer-under.slk
$EX t/inflem.slk
$EX t/kk.slk
$EX t/label-basic.slk
$EX t/label-dll.slk
$EX t/label.slk
$EX t/ll-1.slk
$EX t/ll-2.slk
$EX t/ll-ex1.slk
$EX t/ll-ex2.slk
$EX t/ll-inv.slk
$EX t/ll.slk
$EX t/ll-under1a.slk
$EX t/ll-under1b.slk
$EX t/ll-under1c.slk
$EX t/ll-under1d.slk
$EX t/ll-under1e.slk
$EX t/ll-under1f.slk
$EX t/ll-under1.slk
$EX t/ll-under2.slk
$EX t/ll-under.slk
$EX t/ll-under-test.slk
$EX t/lst-under0a.slk
$EX t/lst-under0.slk
$EX t/lst-under1.slk
$EX t/lst-under2.slk
$EX t/lst-under3.slk
$EX t/pr2a.slk
$EX t/pr2.slk
$EX t/pr3.slk
$EX t/pr.slk
$EX t/sleek10.slk
$EX t/sleek12-lend.slk
$EX t/sm-1.slk
$EX t/test-under.slk
