Entail (1) : Valid. 
Entail (2) : Fail.
Entail (3) : Valid. 
Entail (4) : Valid. 
Entail (5) : Valid. 
Entail (6) : Valid. 
Entail (7) : Valid. 
Entail (8) : Valid. 
Entail (9) : Fail.
Entail (10) : Valid. 
Entail (11) : Valid. 
Entail (12) : Fail.
Entail (13) : Valid. 
Entail (14) : Valid. 
Entail (15) : Valid. 
Entail (16) : Fail.
Entail (17) : Fail.
Entail (18) : Valid. 
Entail (19) : Valid. 
Entail (20) : Valid. 
Entail (21) : Fail.
Entail (22) : Valid. 
Entail (23) : Valid. 
Entail (24) : Valid. 
Entail (25) : Valid. 
Entail (26) : Valid. 
Entail (27) : Valid. 
