#!/bin/sh
#
# see muh-check on how to put this in your crontab
# make sure this corresponds with your muhrc-settings
#
# $Id: muh-rotatelog,v 1.1.1.1 2008-03-15 06:55:01 nguyenh2 Exp $
#

LOGDIR=$HOME/muh-logs

mkdir -p `date +$LOGDIR/%b-%y/`
kill -USR2 `cat $HOME/.muh/pid`
