#!/bin/sh
#
# see muh-check on how to put this in your crontab
# make sure this corresponds with your muhrc-settings
#
# $Id: muh-rotatelog,v 1.2 2009-02-17 08:55:21 chinwn Exp $
#

LOGDIR=$HOME/muh-logs

mkdir -p `date +$LOGDIR/%b-%y/`
kill -USR2 `cat $HOME/.muh/pid`
