#create a list of expected results
cp simple.ss website/1.ss
cp forkjoin.ss website/2.ss
cp double-acquire.ss website/3.ss
cp no-deadlock1.ss website/4.ss
cp no-deadlock2.ss website/5.ss
cp no-deadlock3.ss website/6.ss
cp deadlock1.ss website/7.ss
cp deadlock2.ss website/8.ss
cp deadlock3.ss website/9.ss
cp disj-no-deadlock1.ss website/10.ss
cp disj-no-deadlock2.ss website/11.ss
cp disj-no-deadlock3.ss website/12.ss
cp disj-deadlock.ss website/13.ss
cp ordered-locking.ss website/14.ss
cp unordered-locking.ss website/15.ss
cp multicast.ss website/16.ss
cp oracle.ss website/17.ss
cp owicki-gries.ss website/18.ss
