NL_STR=$'\n'
echo "sll.slk"
../../sleek sll.slk --inv-baga | grep "infered baga"
echo " sll.slk delay"
../../sleek sll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "dll.slk"
../../sleek dll.slk --inv-baga | grep "infered baga"
echo " dll.slk delay"
../../sleek dll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "cll.slk"
../../sleek cll.slk --inv-baga | grep "infered baga"
echo " cll.slk delay"
../../sleek cll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "ell.slk"
../../sleek ell.slk --inv-baga | grep "infered baga"
echo "ell.slk delay"
../../sleek ell.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "oll.slk"
../../sleek oll.slk --inv-baga | grep "infered baga"
echo "oll.slk delay"
../../sleek oll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "sortll.slk"
../../sleek sortll.slk --inv-baga | grep "infered baga"
echo "sortll.slk delay"
../../sleek sortll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "bndll.slk"
../../sleek bndll.slk --inv-baga | grep "infered baga"
echo "bndll.slk delay"
../../sleek bndll.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "lseg.slk"
../../sleek lseg.slk --inv-baga | grep "infered baga"
echo "lseg.slk delay"
../../sleek lseg.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "btree.slk"
../../sleek btree.slk --inv-baga | grep "infered baga"
echo "btree.slk delay"
../../sleek btree.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "bst.slk"
../../sleek bst.slk --inv-baga | grep "infered baga"
echo "bst.slk delay"
../../sleek bst.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "rose-tree.slk"
../../sleek rose-tree.slk --inv-baga | grep "infered baga"
echo "rose-tree.slk delay"
../../sleek rose-tree.slk --inv-baga --en-delay-eelim | grep "infered baga"
echo "$NL_STR"
echo "tll.slk"
../../sleek tll.slk --inv-baga | grep "infered baga"
echo "tll.slk delay"
../../sleek tll.slk --inv-baga --en-delay-eelim | grep "infered baga"