../../../hip --eps append.ss > append.res
../../../hip --eps append-tail.ss > append-tail.res
../../../hip --eps avl-bind.ss > avl-bind.res
../../../hip --eps avl.ss > avl.res
../../../hip --eps avl-orig-2.ss > avl-orig-2.res
../../../hip --eps avl-orig3.ss > avl-orig3.res
../../../hip --eps bll.ss > bll.res
../../../hip --eps bubble.ss > bubble.res
../../../hip --eps cll.ss > cll.res
../../../hip --eps complete.ss > complete.res
../../../hip --eps dll.ss > dll.res
../../../hip --eps heaps.ss > heaps.res
../../../hip --eps insertion.ss > insertion.res
../../../hip --eps ll.ss > ll.res
../../../hip --eps merge.ss > merge.res
../../../hip --eps perfect.ss > perfect.res
../../../hip --eps qsort.ss > qsort.res
../../../hip --eps qsort-tail.ss > qsort-tail.res
../../../hip --eps selection.ss > selection.res
../../../hip --eps sll.ss > sll.res
../../../hip --eps trees.ss > trees.res
../../../hip --eps rb.ss > rb.res
../../../hip --eps global1.ss > global1.res
../../../hip --eps global2.ss > global2.res
../../../hip --eps global3.ss > global3.res
../../../hip --eps global4.ss > global4.res
../../../hip --eps global5.ss > global5.res
../../../hip --eps global-ll.ss > global-ll.res
../../../hip --eps global-mutual-rec.ss > global-mutual-rec.res

